desktop/libs/libopenid/src/libopenid/templates/openid-login.html

Quick fix, for missing csrf token from the openid plugin

The csrf_token was missing from the openid login template

---

apps/beeswax/src/beeswax/server/dbms.py

Submitting a pull request as requested in ticket HUE-2707 for allowing the showing of samples in partitioned tables.
Reworked the patch to include in Romain's code improvement suggestions.

HUE-2707 Allow sample on partitioned tables in strict mode.

---

apps/spark/java/livy-yarn/src/main/scala/com/cloudera/hue/livy/yarn/Client.scala

The code in Client.scala shows that yarnClient init with default YarnConfiguation which's yarn.resourcemanager.address is 0.0.0.0:8032. For can't get application status, the batch status will keep in 'running'. So it need to reload the yarn-site.conf by env['HADOOP_CONF_DIR']

Iivy server get application report failed.

---

apps/oozie/src/oozie/models2.py

This patch sets by default credentials `hive2` on Hive2 actions and `hcat` on Hive actions so user that drops these actions in workflow does not need to remember to select them every time.

[Oozie] Default credentials in hive actions

---

desktop/core/ext-py/parquet-python/parquet/bitstring.py

It looks like this file has an extra ] and a missing (.  
This file doesn't compile under Python 2.7:
```
$ python desktop/core/ext-py/parquet-python/parquet/bitstring.py
File "desktop/core/ext-py/parquet-python/parquet/bitstring.py", line 4
]
^
SyntaxError: invalid syntax
$ python desktop/core/ext-py/parquet-python/parquet/bitstring.py
File "desktop/core/ext-py/parquet-python/parquet/bitstring.py", line 19
byte_index, bit_offset = divmod(self.offset + key), 8)
^
SyntaxError: invalid syntax
```
Interestingly, the ] bracket was deleted [upstream](https://github.com/jcrobak/parquet-python/commit/a11b59454e9e0f01338814225a97ea30b085c6fc), but the ( paren wasn't added?
I've started a pull request upstream.

fixing extra bracket and missing paren in ext-py/parquet/bitstring.py

---

desktop/core/ext-py/pyopenssl/OpenSSL/crypto/crl.c

This fix allows pyopenssl == 0.13 build against OpenSSL library headers >= 1.0.2a.
More information can be found [here](https://github.com/cloudera/hue/issues/205).
Let me know if you have any questions!
Chris Stephens
Netflix, Inc

Fix to allow build w/ OpenSSL >= 1.0.2a

---

desktop/libs/liboozie/src/liboozie/types.py

1. create some workflows in some coordinators inside a bundle.
2. mark the coordinators for a startTime of sometime in the future.
3. submit the jobs to oozie.
4. go to hue -> bundles
5. click on the bundle you just submitted.
Expected result:
you see the bundle with all of its coordinators.
Actual result:
you get this situation: https://community.cloudera.com/t5/Web-UI-Hue-Beeswax/HTTP-500-error-launching-Oozie-bundle/td-p/26967
I'm not 100% familiar with the hue codebase but based on that stacktrace above (and my identical ones) it looks like to calculate progress it expects to either have a currently running action or one that has happened already. Since a coordinator in prep mode wont have either, you get a None for lastAction.
Solved it locally (CDH5.4.1) by just setting progress to …

[oozie] untriggered oozie coordinators break hue

---

apps/spark/java/livy-server/pom.xml
apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/Main.scala

Mount MetricsAdminServlet under "/" which gives 4 new contexts: /healthcheck, /metrics, /ping, and /threads
The admin servlet also gives a small html page with links to the above.  Additional metrics and checks can be added easily in the future.

Add scalatra-metrics support to livy

---

desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py

The `cluster` uri in the `cluster()` method from `desktop/libs/hadoop/src/hadoop/yarn/resource_manager_api.py` redirects to `cluster/info` for information about cluster. In this fix we set uri to 'cluster/info' to avoid redirect failing on standby resourcemanager.

setting cluster information uri to /cluster/info

---

apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/batch/BatchSessionProcess.scala
apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/batch/BatchSessionYarn.scala
apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/batch/CreateBatchRequest.scala
apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/interactive/CreateInteractiveRequest.scala
apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/interactive/InteractiveSessionProcess.scala
apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/interactive/InteractiveSessionYarn.scala

Current Livy API implementation lacks support for YARN queues when running spark.

Support for queues in Livy

---

apps/spark/java/livy-yarn/src/main/scala/com/cloudera/hue/livy/yarn/Client.scala

Currently the code assumes HADOOP_CONF_DIR always ends up with a trailing '/'. So it just appends yarn-site.xml to the path. In case the / is missing, it won't be able locate the yarn-site.xml file. That will cause it not able to find the yarn endpoints to get job status thus things start to fail.
In other places, code always adds a file separator ('/' in this case) so the files can be found. Doing the same here.

Add file separator for accessing yarn-site.xml.

---

apps/zookeeper/src/zookeeper/rest.py

Zookeeper REST API return empty string without sending http header "Accept" "application/json" or "application/xml"

Update rest.py - set default http header to accept "application/json"

---

desktop/libs/librdbms/src/librdbms/server/mysql_lib.py

Need to add the backticks in the code, because adding it in hue.ini will create another problem.
https://issues.cloudera.org/browse/HUE-3087

added backticks to handle database name that use reserved keyword.

---

apps/beeswax/src/beeswax/create_table.py

Explicitly use TextFile format when creating a table from a CSV file. Otherwise, hive.default.fileformat is used, which could lead to the resulting table not being accessible.

Force TextFile file_format in table import

---

apps/oozie/src/oozie/templates/editor2/workflow_editor.mako

We need a way to exclude ozzie's shared libs for jobs written in Spark that is incompatible with the one distributed along with oozie. There is a setting for doing this: 'oozie.use.system.libpath' but Hue hides it immediately when found on Workflow Settings view. This change prevents hiding and shows the setting back.

Uncover ability to set the oozie.use.system.libpath variable on the Workflow Settings view

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/settings.py

This is a simple patch to configure Django clickjacking middleware with an X-Frame-Options header from hue.ini
This is not really useful, because Hue escapes any frame I tried to use it in. Still, having it is better than not.

X-Frame-Options value can be set in hue.ini config.

---

desktop/core/src/desktop/lib/export_csvxls.py

Making the openpyxl Workbook write-only greatly decreases memory usage during generation of the .xlsx file.
See also https://openpyxl.readthedocs.org/en/2.3.3/optimized.html#write-only-mode

Use .xlsx write-only optimization in export_csvxls.py

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py

It is possible to bypass the existing whitelist to redirect to a URL of an attacker's choosing using a schemaless URL. e.g. //github.com. This is because the current default regex whitelist checks only to ensure that the first character of the location header in the redirect request is a '/'. This has been assigned CVE-2015-8094, although no details have been released on it.
The changed regex is tightened to allow for '/' alone, but if more characters are found in the string, then the second character must be alphanumeric. No further restrictions are in place. 
I'd like to encourage testing of this to ensure that the fix works as expected.

Default regex tightened to address open URL redirection issue

---

apps/pig/src/pig/templates/app.mako

Currently, forms in Pig app do not carry csrf_token. If a user loses the cookie, using Pig becomes impossible because of error 403. We encounter this constantly and the enclosed patch fixes it.

Add csrf_token to Pig app template

---

README.md

`PostGresl` is not correct, the true name should be `PostgreSQL` that I found it on http://www.postgresql.org/
I created an issue on it: https://github.com/cloudera/hue/issues/371

Fix postgresql spelling in README.md

---

apps/rdbms/src/rdbms/templates/execute.mako

if RDBMS result has XML column, the XML data will not display in HTML.
add `toString().htmlEscape()` to escape the result.

Rdbms result escape xml

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py

This is fix for this [issue](https://github.com/cloudera/hue/issues/381).
If you trying to run your scala snippet, you can't see syntax error or error in your SQL request in web UI 
The problem is in [spark_shell.py](https://github.com/cloudera/hue/blob/74040cb987b290ddb8dcf2f2da7e26fba0c4cb25/desktop/libs/notebook/src/notebook/connectors/spark_shell.py#L266)
where I found wrong comparison operator for 'traceback' variable.
If you have exception where 'traceback' variable is not equal None, but it is 'traceback': [] then this line if tb is None: is not work and you can see QueryError with empty message (because on line [273](https://github.com/cloudera/hue/blob/74040cb987b290ddb8dcf2f2da7e26fba0c4cb25/desktop/libs/notebook/src/notebook/connectors/spark_shell.py#L273) you can see join with …

ISSUES-381 fix rules for stderror in spark_shell

---

Makefile.vars

I added python 2/3 compatible changes to Makefile.vars, because some code is executed before configuring SYS_PYTHON and causes failures when python 3 is the default "python". I added parenthesis for calls to print so that the code works equally well under python 2 and 3.

Avoid make failure when default python is python3

---

desktop/libs/librdbms/src/librdbms/jdbc.py

Using [this documentation](http://gethue.com/custom-sql-query-editors/) I failed to connect Hue to my [JDBC-compatible tool](https://github.com/mozafari/verdict). When I investigated the source code I found that the CLASSPATH variable and the JDBC driver class name are not used anywhere in the code. So, my JDBC driver class is not loaded at all.
This PR fixes that and makes sure that the JDBC driver class is loaded.

Use CLASSPATH value for creating JavaGateway and load JDBC driver class

---

desktop/core/src/desktop/static/desktop/js/ko.hue-bindings.js

Ctrl-E is meant to move the cursor to the end of the line on macOS.

Removed Ctrl-E keybinding (editor.create.new) on macOS

---

apps/search/src/search/static/search/js/search.ko.js

The code was comparing the result of `typeof` with a variable named `undefined`. As typeof returns a string it should compare to `'undefined'`.
What we really want is to check if `callback` is a function, so I changed the nature of the `if` condition.

Correct check for undefined variable

---

apps/filebrowser/src/filebrowser/views.py

Absolute URLs don't work when Hue is hidden behind a gateway/reverse proxy.
In the file browser, use relative URLs instead.

Use relative URLs in file browser

---

apps/beeswax/src/beeswax/conf.py
apps/beeswax/src/beeswax/models.py
apps/beeswax/src/beeswax/server/hive_server2_lib.py
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/models.py
desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

Allow multiple concurrent HiveServer2 sessions per user.
When using Tez, this prevents a new query to kill a currently running operation.
Note: I'm already in the contributor list.

Multiple Hive sessions for Tez

---

README.md

It is just a really minor detail, but the current Django link takes to a 404
Changed the link to point to base Django URL that redirects to current version

Updates 404 on Django version URL

---

apps/oozie/src/oozie/models2.py

When Oozie workflow submitted in Hue and the workflow name contains non-english characters, Hue replaced all non-english characters to underscores which seriously affected later displays.
XML standards demands proper escaping of only 5 special characters in attribute string, so there is no need to be so strict.

fix non-english oozie workflow name mangling problem

---

apps/beeswax/src/beeswax/server/hive_server2_lib.py

We had occasional cases of document2 objects of type 'query-hive' in the DB missing a 'snippets' field and throwing an exception in hive_server2_lib.
With this change, the exception is caught and the document is ignored.

Catch missing 'snippets' field in document2 data in hive_server2_lib

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/libs/aws/src/aws/client.py
desktop/libs/aws/src/aws/conf.py

This is done by exposing the following configuration options:
* proxy_address - address of the endpoint
* proxy_port - port to use on the endpoint
* is_secure - determine whether we're using https or http
* calling_format - allow OrdinaryCallingFormat since not all endpoints have DNS
setup to support `<bucket-name>.domain/<file>`.

[HUE-5420] Support alternative s3 endpoints.

---

desktop/libs/notebook/src/notebook/connectors/spark_batch.py

cannot spark submit jar or python due to incorrect params to create livy session.
The Spark Livy create batch session api does not accept 'pyFiles' == null or 'files' == null params.

HUE-5169 [spark] cannot spark submit jar or python

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/libs/notebook/src/notebook/conf.py
desktop/libs/notebook/src/notebook/connectors/base.py
desktop/libs/notebook/src/notebook/monkey_patches.py
desktop/libs/notebook/src/notebook/tests.py
desktop/libs/notebook/src/notebook/views.py

Copying the description from the JIRA:
Currently the ordering for which interpreters to show on the notebook wheel just takes the top 5 interpreters. We should allow users to configure which interpreters they want shown first regardless of ordering in hue.ini. This patch adds a setting interpreters_shown_on_wheel which takes a list of interpreters to show on the notebook wheel. If unset, this will still default to the top 5 interpreters.

HUE-5478 Allow users to specify interpreters on Notebook selection wheel

---

desktop/libs/notebook/src/notebook/static/notebook/js/notebook.ko.js

From the commit  LIVY-213 in the Livy Rest server see: [https://github.com/cloudera/livy/commit/b4642b193956b287bb1c1b32bafe4c5a15e71eac](https://github.com/cloudera/livy/commit/b4642b193956b287bb1c1b32bafe4c5a15e71eac)
They have added a new status "waiting" for jobs that have been submitted but are waiting to be executed this pull requests fixes a minor bug that the notebook would not recheck the status in the same way as it does for "starting" and "running" if it receives the status waiting
tested against
Hue commit bbe6acb (25.01.2016)
Livy commit [https://github.com/cloudera/livy/commit/69462b9315cb652a5d19aa4d5104b210d06fb10f](https://github.com/cloudera/livy/commit/69462b9315cb652a5d19aa4d5104b210d06fb10f) (25.01.2016)
Spark 2.1.0
Hadoop 2.7.3

Notebook will not recheck status when received status "waiting"

---

desktop/core/src/desktop/static/desktop/js/sqlAutocompleter3.js

If you type this into the hive query editor: 
select x.* from (select * from (select 1) y) x where x.`_c0` = "asd"
You will get a strange repeated insertion of the token in between the quotes (`asd`) every time you hit any key. This fixes it.

Fixed a bug where autocompletion would break on subqueries

---

apps/beeswax/src/beeswax/server/hive_server2_lib.py

Add EXTERNAL_TABLE to the list of DEFAULT_TABLE_TYPES in hive_server2_lib so Hue will show external tables in database meta info

HUE-6066 - Add EXTERNAL_TABLE to the list of DEFAULT_TABLE_TYPES

---

apps/oozie/src/oozie/views/dashboard.py

Fixes Issue https://github.com/cloudera/hue/issues/637 (JIRA Link: https://issues.cloudera.org/browse/HUE-7810)
Adds ACL permissions validation to allow users to manage Oozie jobs if granted using `oozie.job.acl` parameter

[HUE-7810] Fix Oozie Dashboard ignores ACL permissions

---

apps/useradmin/src/useradmin/middleware.py

When idle_session_timeout used and jobbrowser app is enabled, jobbrowser/api/jobs schedule requests does not allow the user session to expire.

[useradmin] Fix last activity update for jobbrowser/api/jobs requests

---

desktop/core/src/desktop/auth/backend.py

Now the code "username = username.replace('%', '').replace('_', '')" in function filter_users_by_claims(self, claims): has a bug.
If user has a username like "test_with_under_score", then when openid to login into HUE,
every time HUE will recognize the user as a new user, 
which will end in an exception of "Duplicate entry '****' for key 'username'".
The field lookups that equate to LIKE SQL statements (iexact, contains, icontains, startswith, istartswith, endswith and iendswith) will automatically escape the two special characters used in LIKE statements – the percent sign and the underscore. (In a LIKE statement, the percent sign signifies a multiple-character wildcard and the underscore signifies a single-character wildcard.)
I've already tested in hue embedded django console line:
And …

HUE-8321 [oidc] Remove filter query from filter_users_by_claims

---

docs/admin-manual/manual.md

- add Homebrew installation as a build prerequisite for MacOS
- add dependencies installation instruction using Homebrew
- also add `libffi` package as a dependency

[docs] Update installation guide for MacOS

---

tools/docker/README.md

No spaces were between the markdown header tags and the header text, causing the markdown to not render properly.

Edited markdown headers

---

apps/oozie/src/oozie/models2.py

Here are my reappearance steps:
1. create a shell or spark workflow ,(type as Pig/Sqoop/Dist/Shell/MapReduce/Java/Spark , also met issues)
2. create a schedule of this workflow.
3. submit schedule
would get HUE-7919 problem.
In Class Coordinator of hue/apps/oozie/src/oozie/models2.py , 
```
@property
def workflow(self)
```
initialize a Workflow without 'user' parameter, then the workflow.user=None, when passing to check can_read/write_or_exception(), would  raise  'NoneType' object has no attribute 'is_superuser'
--
ps: i'm not sure its exactly correct

[HUE-7919] oozie error 'NoneType' object has no attribute 'is_superuser'

---

apps/oozie/src/oozie/models2.py
apps/oozie/src/oozie/templates/dashboard/list_oozie_workflow_graph.mako

Currently, Oozie graph widgets are using the last 4 characters of the action name appending with UUID to generate the widget id. At rendering time, after the AJAX call from refreshView() is made, the JS code is using the last 4 characters of the action name, returned from the AJAX call, to find the matching widgets to update its status (process, completion, etc.)
This causes trouble when multiple action names have the same last 4 digits. I've fixed it by constructing the widget ID more appropriately by appending the full action name + the UUID. I've tried to retain the semantics of the UUID as much as possible (the final ID will have the same length as the UUID) to fix the bug. After this fix, Oozie workflow should be rendered and updated correctly.
More importantly, without this change, …

Fix Oozie workflow widget id colliding bug

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/libs/notebook/src/notebook/connectors/base.py
desktop/libs/notebook/src/notebook/connectors/jdbc_clickhouse.py
desktop/libs/notebook/src/notebook/templates/editor_components.mako

Now, we can connect to ClickHouse servers with jdbc driver.
1. download all related jars (see https://github.com/yandex/clickhouse-jdbc)
2. add above jars into `CLASSPATH`
3. configure **hue.ini** as  follows
```
[notebook]
[[interpreters]]
[[[clickhouse]]]
name=ClickHouse
interface=jdbc
options='{"url": "jdbc:clickhouse://localhost:8123", "driver": "ru.yandex.clickhouse.ClickHouseDriver", "user": "readonly", "password": ""}'
```
Since I'm very new to Hue, I mainly refer to `jdbc_teradata.py`.
Best regards,

[editor] Add a ClickHouse connector using jdbc

---

desktop/libs/hadoop/src/hadoop/fs/webhdfs.py
desktop/libs/hadoop/src/hadoop/hdfs_site.py

Currently, Hue is hard coded to http for webhdfs (return "http://%s:%s/webhdfs/v1" % (host, port)).  This PR makes it dynamically pull SSL from hdfs-site settings with the ability to override the port from hue.ini
Note -> i just moved the port into the hdfs-site.py so i need to test that and make sure it works since previously i was injecting it in webhdfs.py (this seemed cleaner though it does seem to break the convention of no hue.ini settings in hdfs-site.py).

Adding HTTPS options for WebHDFS

---

desktop/core/src/desktop/templates/document_browser.mako

Fix an annoying UI bug where the search result of the user search function in notebook sharing is not displayed correctly. You can reproduce this bug in v4.4 in http://demo.gethue.com. 
Attached are the screenshots before and after this simple fix.

Fix notebook user's searching not displaying

---

apps/sqoop/src/sqoop/client/config.py

Tested within an HDP 2.5 environment, with Sqoop 1.99.6 built from source. 
After some combination of changes and errors (I started with 1.99.5 release, then tried the CDH release, then maybe tried MapR release...), I eventually was able to search this stacktrace piece
```
NullPointerException 
at "org.apache.sqoop.json.util.ConfigInputSerialization.restoreConfig(ConfigInputSerialization.java:160)"
```
[Which lead me here](http://www.cnblogs.com/fillPv/p/5458677.html), (in Chinese, but mostly translatable) which says something about Hue not correctly POST-ing or PUT-ing to the Sqoop endpoint. 
This change seems to fix the issue, as I am able to create, update, and run jobs successfully via Hue.  
---
I am unsure of the implications of this change otherwise. 
The `size` field itself …

HUE-5128 [sqoop] Allows job creation and updates

---

apps/hbase/src/hbase/api.py

[[HBase Brower] api error throw when search hbase with rowkey startwith '0'](https://github.com/cloudera/hue/issues/894)

pull request to fix hue-894

---

apps/hbase/src/hbase/api.py
desktop/core/src/desktop/js/ko/bindings/ko.highlight.js

add a try { } catch {} block in line 73 of ko.highlight.js to fix issue [[SQL Editor] failed to list query history where there're some chinese in comment](https://github.com/cloudera/hue/issues/896)

[FIX] fix Hue-896

---

desktop/core/src/desktop/js/ko/components/assist/ko.assistStoragePanel.js

Currently there is a problem when refreshing the assist panel. The problem begins by first clicking the files category on the assist panel and then going to one of the filesystems (HDFS, S3, ADLS). If the manual refresh button is pushed, it causes an error. This is just a minor change that fixes that problem.

Fixed manual reload for side panel on Hue

---

desktop/core/src/desktop/js/api/apiHelper.js

Fix bug  related to table browser module:  Unable  adding hive table column description  in table browser mode.Occurring render unexpected form data.

[fix] fix bug -- table browser can not add description

---

desktop/libs/azure/src/azure/abfs/__init__.py
desktop/libs/azure/src/azure/abfs/abfs.py
desktop/libs/azure/src/azure/abfs/abfsstats.py

It fixes the issue where users that do not have the configuration for ABFS cannot run Hue.
It also adds changes that may be used in later commits.

Fix for systems that do not have ABFS Configuration 

---

desktop/core/src/desktop/js/sql/sqlFunctions.js

Current description of `from_unixtime` function is apparently for `unix_timestamp`.
I have no idea these descriptions are taken from, so I copied this text from [this page](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-Built-inFunctions).
If it is not acceptable for license, please let me know.

Fix description doc of from_unixtime 

---

apps/beeswax/src/beeswax/server/hive_server2_lib.py

see detail description in https://issues.cloudera.org/browse/HUE-9083

HUE-9083 Fix concurrent query with Hive on Tez when `max_number_of_sessions > 1`

---

apps/hbase/src/hbase/hbase_site.py

This PR looks for the `hbase.thrift.spnego.principal` config and uses it if it is set in hbase-site.xml. If not it falls back to the previous logic.

HUE-9121 [hbase] Hue should handle HBase Thrift SPNEGO HTTP/hostname principal

---

tools/docker/hue/Dockerfile

In our company product environment, kerberos is a necessary authentication mechanism. So kerberos related dependencies(such as krb5-config) need to be add in Dockerfile

HUE-9165 [tool] Supported kerberos config when use hue on docker

---

docs/gethue/config.toml
docs/gethue/themes/stack-hue-theme/layouts/_default/single.html

Showing it just in case it's different and newer than the publish date. With this we now also have access to the [.GitInfo object](https://gohugo.io/variables/git/)

HUE-8888 [gethue] Add last modified date from git info

---

desktop/core/src/desktop/auth/forms.py

~~For our use case, 30 characters is too short and is not allowing some users
to access Hue (it seems that is also the case of the original reporter
on the linked issue).~~
~~I've added a new configuration value which allows tweak this length and,
by default, it maintains the previous behavior (30 characters per
username). I'm not sure if having this as a parametrizable configuration
is the way to go or if you prefer to just increase the max length of
this field.~~
The max length for a username on Django 1.11 is 150 (was increased from
30): https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.username
I've checked the size of the username field on `auth_user` and the field
is a `varchar(150)`, so it should be safe to increase.

HUE-8020 - Increase username length on auth form

---

desktop/libs/notebook/src/notebook/templates/editor_components.mako

The snippet 'Markdown' was not rendering in notebook because of missing parenthesis. Just added the parenthesis and it's working.
See Issue #1116

Fix markdown rendering (Issue #1116)

---

desktop/libs/aws/src/aws/s3/__init__.py
desktop/libs/aws/src/aws/s3/s3_test.py

Hi!
Fix parse time like: `2020-03-27T19:15:42.462Z`..
This is [minio](http://minio.io/) timestamp format.
Error trace:
```
hue_1       |   File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py", line 321, in listdir_stats
hue_1       |     res.append(self._stats_key(item, self.fs))
hue_1       |   File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3fs.py", line 207, in _stats_key
hue_1       |     return S3Stat.from_key(key, is_dir=is_directory_name, fs=fs)
hue_1       |   File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3stat.py", line 90, in from_key
hue_1       |     mtime = s3datetime_to_timestamp(s3_date) if s3_date else None
hue_1       |   File "/usr/share/hue/desktop/libs/aws/src/aws/s3/__init__.py", line 140, in s3datetime_to_timestamp
hue_1       |     assert datetime[-5:] == …
```

fix(aws): s3datetime_to_timestamp parse timestamp with Z(minio.io)

---

tools/jenkins/build-functions

`CDH_URL` -> `HADOOP_URL`
`CDH_TGZ` -> `HADOOP_TGZ`
`CDH_VERSION` -> `HADOOP_VERSION`
`CDH_SHORT_VERSION` -> `HADOOP_SHORT_VERSION`
`CDH_CACHE` -> `HADOOP_CACHE`

changed the variable names to more general in build-functions

---

desktop/core/src/desktop/auth/views_test.py
desktop/core/src/desktop/templates/login.mako

bugfix: the deactivate login error's form doesn't have 'username'. (related to #1164)

---

apps/filebrowser/src/filebrowser/views_test.py

related #1171 
added `builtin str`, especially for https://github.com/cloudera/hue/blob/d3cc8ff366620b90670121eea0bad013cfd74dc1/apps/filebrowser/src/filebrowser/views_test.py#L1286
I tested test cases with OK in the file. `apps/filebrowser/src/filebrowser/views_test.py `
``` sh
./build/env/bin/hue test specific filebrowser.views_test:TestFileBrowserWithHadoop
```

added builtin str for compatiblity with python2 and python3

---

apps/beeswax/src/beeswax/tests.py

[beeswax tests] test_select_query_server: set localhost for default expected value

---

docs/docs-site/content/developer/development/_index.md

Added instructions to setup a Hive 2.3.2 demo instance locally using docker, and connect Hue to the new instance.

HUE-9368. Documentation changes (sree)

---

desktop/core/src/desktop/auth/views.py
desktop/core/src/desktop/views.py
desktop/libs/libsaml/src/libsaml/backend.py
desktop/libs/libsaml/src/libsaml/tests.py
tools/container/hue/hueconf/saml_attributes/cldr.py

"attribute_map_dir": "attribute-maps" Points to a directory that has the attribute maps in Python modules.

HUE-9398 [core] Add attribute_map_dir saml configuration.

---

desktop/libs/notebook/src/notebook/views.py

notebook/views.py: `SparkApi.get_properties` renamed to `SparkApi.to_properties`
Fix issue: cloudera/hue#1206

Fix [notebook] cloudera/hue#1206

---

apps/useradmin/src/useradmin/forms.py
apps/useradmin/src/useradmin/test_ldap.py
apps/useradmin/src/useradmin/tests.py

On https://github.com/cloudera/hue/pull/1104 (HUE-8020), username length
was increased up to 150 characters. Anyway, some backends (at least,
LDAP) are still validating that username is up to 30 characters.
This increases the validation lenght to match with the size of the field
on the DB and the max input lenght on the authentication form.

Increase username length to 150 characters

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py

Hello!
Add configuration options `numExecutors` (Number of executors to launch for the session) to livy.
https://livy.incubator.apache.org/docs/latest/rest-api.html

[livy] Add numExecutors options

---

desktop/core/src/desktop/auth/backend.py
desktop/core/src/desktop/lib/wsgiserver.py

List of changes:
- in backend.py: the kwargs not properly stated lead to the password being
passed as username, causing LDAP authentication to fail. Not sure why this
present iself in py3, but adding username= and password= fixes.
- wsgiserver.py: a misindentation after an if causes a syntax error.

[desktop] Fix code not compatible with py3 (#1239)

---

apps/oozie/src/oozie/importlib/workflows.py

When an header like `<?xml version="1.0" encoding="UTF-8"?>` is used
at the top of an Oozie workflow, the etree.fromstring() function refuses
to work since the workflow_definition variable is not encoded.

[oozie] Fix workflow graph rendering with Python 3 (#1262)

---

desktop/libs/notebook/src/notebook/views.py

What changes were proposed in this pull request?
HUE-9487 [editor] Open in Editor Option Redirects to Default DB rather than expected one
How was this patch tested?
Tested manually in Local hue, the Fix works well

HUE-9487 [editor] Open in Editor Option Redirects to Default DB rather than expected one

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/libs/libsaml/src/libsaml/conf.py
desktop/libs/libsaml/src/libsaml/saml_settings.py

HUE-9493 [libsaml] allow accepted_time_diff configure for pysaml
Tested manually in hue server the time difference is there, the Config change works well and no error or exception.

HUE-9493 [libsaml] allow accepted_time_diff configure for pysaml

---

tools/kubernetes/helm/hue/templates/deployment-hue.yaml
tools/kubernetes/helm/hue/values.yaml

This is required if one wants to use certain operators that need specific labels to be applied to the pods.

[k8s] Add podLabels to values (#1305)

---

desktop/core/src/desktop/js/catalog/dataCatalogEntry.js

HUE-9500 [ui] Comment is not shown when view the table info from table browser first time
Tested manually in master branch, if comment is set , its getting preference rather than from navigatorMeta .

HUE-9500 [ui] Comment is not shown when view the table info from table browser first time

---

desktop/core/src/desktop/lib/thrift_/TSSLSocketWithWildcardSAN.py
desktop/core/src/desktop/lib/thrift_util.py

What changes were proposed in this pull request?
HUE-9508 [querybrowser] Hue does not work with Hive/Impala enforced to TLS 1.2 
How was this patch tested?
Tested manually in for Imapla and Hive for TLSv1.2 and TLSv1.0

HUE-9508 [querybrowser] Hue does not work with Hive/Impala enforced to TLS 1.2 

---

apps/beeswax/src/beeswax/server/hive_server2_lib.py

SparkSQL hiveserver2 interface does not work with Hue 4.7.1 and gives following error:
```
[05/Oct/2020 15:22:03 -0700] access       INFO     10.30.84.249 hadoop - "POST /notebook/api/execute/sql HTTP/1.1" returned in 233ms 200 67
[05/Oct/2020 15:22:03 -0700] decorators   ERROR    Error running execute
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
return f(*args, **kwargs)
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 225, in execute
response = _execute_notebook(request, notebook, snippet)
File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 153, in _execute_notebook
response['handle'] = interpreter.execute(notebook, snippet)
File …
```

"DoesNotExist: Session matching query does not exist" when using SparkSQL hiveserver2 interface

---

desktop/libs/notebook/src/notebook/conf.py

Set user to None so Hue will initialize INTERPRETERS_CACHE to have all interpreters

Get full list of interpreters for INTERPRETERS_CACHE

---

desktop/core/src/desktop/auth/views.py

HUE-9538 [core] user home directories are not created for Newly Logged in User
Tested manually in master branch, if once code change is pushed, user home directory will be created for newly logged in user i LDAP
```
[30/Oct/2020 04:21:34 -0700] backend      DEBUG    Creating Django user user106
[30/Oct/2020 04:21:34 -0700] backend      DEBUG    Populating Django user user106
[30/Oct/2020 04:21:35 -0700] resource     DEBUG    GET http://asnaikCdp01.example.com:9870/webhdfs/v1 returned in 0ms
[30/Oct/2020 04:21:35 -0700] resource     DEBUG    PUT None http://asnaikCdp01.example.com:9870/webhdfs/v1//user/user106?permission=0755&op=MKDIRS&user.name=hue&doas=hdfs  returned in 8ms 200 16 {"boolean":true}
```

HUE-9538 [core] user home directories are not created for Newly Logged in User

---

desktop/core/src/desktop/js/components/Tabs.vue

Because of the margin, the alignment wasn't looking proper on using this component. Hence this patch.

HUE-9485 [frontend] Remove side margins of Tab for better alignment

---

desktop/libs/notebook/src/notebook/connectors/base.py

To avoid error when connector does not support it yet.

[notebook] Adding default explain() function

---

desktop/core/src/desktop/kt_renewer.py

On python3, if kinit fails to renew then the kt_renewer.py dies due
to a error handling logging not supporting binary strings.

[core] Fix error handling in kt_renewer.py for python3

---

desktop/core/src/desktop/js/utils/hueUtils.js

HUE-9552 [fb] Folder Fails to Load when the foldername contains #
Tested Manually by Creating an Folder with # and testing out the fix of the issue

HUE-9552 [fb] Folder Fails to Load when the foldername contains #

---

apps/oozie/src/oozie/templates/dashboard/list_oozie_workflow_graph.mako

HUE-9564 [oozie] Oozie Jobs Submitted via Filebrowser Execute Options  Doesn't Show Logs Button in workflow
Tested the Scenarios 
- Workflow Triggered via Scheduler 
- Workflow Triggered via wF-manager
- Workflow Triggered via Filebrowser.
The Fix Works Fine.

HUE-9564 [oozie] Oozie Jobs Submitted via Filebrowser Execute Options  Doesn't Show Logs Button in workflow

---

desktop/core/src/desktop/models.py

As the query data does not necessary comes from YARN but also from
the Query Processor DB.

[jobbrowser] Show Hive Query Browser even if yarn not configured

---

apps/jobbrowser/src/jobbrowser/api2.py
apps/jobbrowser/src/jobbrowser/apis/hive_query_api.py
apps/jobbrowser/src/jobbrowser/apis/hive_query_api_tests.py
apps/jobbrowser/src/jobbrowser/apis/query_api.py
desktop/libs/notebook/src/notebook/models.py

Call is done as the logged-in user making the call and will
go throught the user existing HiveServer2 session or create
a new session.
```
$.post("/jobbrowser/api/job/action/queries-hive/kill", {
"operation": JSON.stringify({'action': 'kill'}),
"interface": JSON.stringify('queries-hive'),
"app_ids": JSON.stringify(['d94d2fb4815a05c4:b1ccec1500000000'])
}, function(data) {
console.log(JSON.stringify(data));
});
```
Using the notebook API is a good skeleton example for when we could
have spefici actions like kill for other SQL dialects.
Note: not compatible with connectors.

[jobbrowser] Add Hive kill query via Notebook call

---

package.json
webpack.config.npm.js

This is a Webpack 4 bug and more about it can be found @ https://medium.com/@JakeXiao/window-is-undefined-in-umd-library-output-for-webpack4-858af1b881df

GH-1390 [parser] Fix window is not defined bug when parser used on node

---

desktop/core/src/desktop/js/utils/hueUtils.js
desktop/core/src/desktop/js/utils/hueUtils.test.js
desktop/core/src/desktop/js/utils/multiLineEllipsisHandler.js
package-lock.json
package.json

HUE-9570 [ui] Rewramp deXSS with sanitize-html package
- Tested the Function hueUtils.deXSS for many scenarios .
-  The function should sanitize the onerror onclick and another harmfull tags , The function should sanitize script tag 
-  Verified the UI works Fine with Desired Output For Tags Like <str'ong/>, <h1'/>  <p'/>
**The Fix Works Fine.**

HUE-9570 [ui] Rewramp deXSS with sanitize-html package

---

tools/kubernetes/helm/hue/templates/configmap-hue.yaml
tools/kubernetes/helm/hue/values.yaml

This makes it possible to avoid storing passwords in `values.yml` and using `echo ${SOME_VAR}` as a script to obtain the password via environment variables.

[k8s] Add password_script to database configuration

---

desktop/core/src/desktop/auth/backend.py
desktop/core/src/desktop/models.py

Otherwise clicking on the HDFS icon will land on S3 for example.

[hdfs] Do not use object store home as home when not HDFS

---

desktop/libs/notebook/src/notebook/api.py

Instead of all statements.
Note: opening up the query properly loads all the statements already.
To clean-up when simplifying the API with Editor 2.

[editor] Only display executed statement in query history

---

desktop/libs/notebook/src/notebook/api_tests.py
desktop/libs/notebook/src/notebook/conf.py
desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py

Note: new tests coming to handle better when connectors are off or not
Fix
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 99, in decorator
    return func(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py", line 230, in execute
    if self.interpreter.get('dialect_properties', {}).get('has_use_statement') and snippet.get('database'):
AttributeError: 'NoneType' object has no attribute 'get'
[10/Dec/2020 06:53:30 -0800] decorators   ERROR    Error running execute
  File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File …

[sqlalchemy] 'NoneType' object has no attribute 'get'

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/lib/connectors/types.py

First approach to solve #1480 (in parts).
This PR adds a first draft for a dask-sql type, basically copying the presto one, except for the risks - I guess I want `has_optimizer_risks` turned off - but I am not 100% sure I understand it correctly: dask-sql has (so far), no real risk model and no optimization hints, it exposes.
I would be very happy for comments :-)

Add a dask-sql connector type

---

docs/docs-site/content/administrator/configuration/connectors/_index.md

Step 3. in #1480
I tried to follow the convention in other paragraphs: a sentence of description ("what is dask-sql" with a link to the docu) and then some installation instructions.

Add dask-sql to the docs

---

desktop/core/requirements.txt

Hardcoded six version is too old, better to just auto pull it.

[docker] Thrift sasl Python module needed for plain SASL sessions

---

apps/jobbrowser/src/jobbrowser/api2.py
apps/jobbrowser/src/jobbrowser/apis/hive_query_api.py

The signature was bad and breaking all the APIs.
request object can actually be half mocked.

[jb] Kill any running "jobs" in job browser errors

---

desktop/core/src/desktop/models.py

File "/hue/desktop/core/src/desktop/models.py", line 1792, in get_main_quick_action
user_default_app = json.loads(user_preference)
File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

[core] Avoid failure of loading back the user starred app

---

desktop/core/ext-py/boto-2.46.1/boto/s3/multipart.py

Goal: reduce confusion when dealing with access denied or other issues creating multipart uploads.

Raise exception if s3 mpu request fails

---

apps/filebrowser/src/filebrowser/templates/listdir_components.mako
desktop/core/src/desktop/js/ko/bindings/ko.dropzone.js

HUE-9653 [filebrowser] Issue with fileupload when Large Files are uploaded
Tested the Scenarios 
- Drag and drop works well for Long files
- No other impact on any other places
Source of the Fix : https://www.dropzonejs.com/#config-timeout
The Fix Works Fine.

HUE-9653 [filebrowser] Issue with fileupload when Large Files are uploaded

---

tools/docker/hue/Dockerfile.py3

Collecting gevent
Downloading gevent-20.12.1.tar.gz (5.9 MB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /usr/share/hue/build/env/bin/python3.6 /usr/share/hue/build/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpdrdp1zjb
cwd: /tmp/pip-install-7lbwjz70/gevent_0275bc262bde4bf9afddae86774d9edc
Complete output (4 lines):
File "/usr/share/hue/build/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 15, in <module>
from glob import glob
ModuleNotFoundError: No module …

[py3] Avoid missing glob module

---

desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py

- [presto] Avoid progress report exception when query just stopped
- [presto] Avoid exception when no progress stats

[presto] Avoid exception when no progress stats

---

docs/user-guide/user-guide.md

PrestoSQL has been rebranded as Trino. See https://trino.io/blog/2020/12/27/announcing-trino.html

Rename Presto to Trino

---

desktop/core/src/desktop/js/apps/notebook2/execution/api.ts

Will need to double check the logic of running vs streaming as
currently does not work with streaming.

[editor2] Avoid disabling cancel button in stream queries

---

tools/kubernetes/helm/hue/templates/servicemonitor-hue.yaml

When deploying Hue on K8's i observed that enabling monitoring with prometheus works fine, That is service discovery works fine.
But the Target labels gets dropped because of the possible wrong selector in place. 
All services have the labels pod:hue. Having app:hue results in targetlabes getting dropped. 
Without the targetlabel , having this monitoring is not that useful because we can't write any alerting.
[service-hue](https://github.com/cloudera/hue/blob/master/tools/kubernetes/helm/hue/templates/service-hue.yaml#L6) also follows up with a label called pod: hue. 
Unsure why app: hue is mentioned here but definitely  when using this , Target labels get dropped. 
I also see that a change done on  [Sep 17, 2019](https://github.com/cloudera/hue/commit/8f055acbc890339745e8bec3715e183af21d5 …

Update ServiceMonitor Label

---

apps/beeswax/data/queries.json

Will then auto show up on https://demo.gethue.com/hue/editor/?type=10 and be available in the install samples admin section of Hue.
Note: seems like the `CREATE MODEL` is not available in dasksql latest image, e.g.
```
CREATE MODEL fare_estimator WITH (
model_class = 'sklearn.ensemble.GradientBoostingClassifier',
wrap_predict = True,
target_column = 'fare_amount'
) AS (
SELECT trip_distance, fare_amount
FROM "nyc-taxi"
LIMIT 100
)```
```
'message': 'Can not parse the given SQL: Incorrect syntax near the keyword \'CREATE\' at line 1, column 1.\nWas expecting one of:\n "CREATE"...
```

[dasksql] Adding NYC taxi data query example

---

desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

To avoid:
[16/Jan/2021 13:40:45 -0800] decorators   ERROR    Error running describe
File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
return f(*args, **kwargs)
File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 1035, in describe
describe = get_api(request, snippet).describe(notebook, snippet, database, table, column=column)
File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 627, in describe
describe_table = self.describe_table(notebook, snippet, database, table)
File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 929, in describe_table
db = self._get_db(snippet, self.interpreter)
File …

[hive] Fix wrong use of positional argument in describe table

---

desktop/core/src/desktop/js/apps/notebook2/editorViewModel.js
desktop/libs/notebook/src/notebook/api.py
desktop/libs/notebook/src/notebook/templates/editor_components2.mako

All the links (e.g. from menu) will auto load the samples, but we should
still allow a blank editor.
This is only affecting when auto load samples is true (i.e. on
demo.gethue.com).
Did not see a simpler way to do. Could have gone the other way around
and changed the URLs of the editor with the new parameters in
get_config() but this feels shorter and less intrusive.

[editor] Do not auto load sample when creating a brand new editor

---

desktop/libs/notebook/src/notebook/connectors/flink_sql.py

#1685 - The DB assist panel lists wrong list of columns for flink table's .
- Tested manually, the DB assist panel should show correct data on autocomplete.

[flink] #1685 - The DB assist panel lists wrong list of columns for flink table's

---

desktop/core/src/desktop/manage_entry.py

Same as in 1.11, different in 2.1
https://docs.djangoproject.com/en/2.0/_modules/django/core/management/base/

[django] CommandParser still requires cmd argument in 2.0

---

desktop/libs/notebook/src/notebook/templates/editor2.mako

'?' moved above in the top-right dropdown menu below 'Queries' and renamed as 'Help' in the editor.
- Patch was manually tested
- UI Changes screenshot below
- On hover, it shows "Show Editor Help".

[editor] '?' moved in top-right dropdown menu as "Help"

---

apps/oozie/src/oozie/templates/dashboard/list_oozie_workflow_graph.mako

The change that was brought in with HUE-9110 is causing Oozie not to show the logs and the progress bar is moved to the bottom.  Just by replacing the '-' with '@' addresses the issue.
A text patch was provided to a customer with this fix and it worked on their env and I have tested the same on a local 7.2.x cluster as well.

fix progress bar and logs icon in oozie wf when run

---

desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/lib/botserver/__init__.py
desktop/core/src/desktop/lib/botserver/admin.py
desktop/core/src/desktop/lib/botserver/apps.py
desktop/core/src/desktop/lib/botserver/migrations/__init__.py
desktop/core/src/desktop/lib/botserver/models.py
desktop/core/src/desktop/lib/botserver/tests.py
desktop/core/src/desktop/lib/botserver/urls.py
desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/urls.py

- Bot server integration with existing Hue server currently serving /slack/events.

Huebot django app integrate with Hue Server

---

desktop/core/src/desktop/js/ko/components/assist/ko.rightAssistPanel.js
desktop/core/src/desktop/js/sql/reference/flink/udfReference.ts

- #GH-1629 - [flink] adding Flink to right assist Function panel
- Tested manually in local, The Right assist panel has to show flink and associated group window functions

[flink] adding Flink to right assist Function panel

---

desktop/core/src/desktop/js/components/sidebar/Sidebar.vue

- The un-expand menu action is full-width clickable now.

[frontend] Make un-expand menu full width clickable

---

docs/docs-site/content/administrator/configuration/_index.md

- Typo in the Configuration page in the docs.

[docs] Fix typo

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/requirements.txt
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/settings.py

First:
./build/env/bin/pip install django-cors-headers==3.7.0
Then in ini:
[desktop]
cors_enabled=true

[core] Setting to turn off CORS

---

desktop/core/requirements.txt

- Mako upgraded to the latest version (1.1.4). And djangomako package removed as it is not giving an error (ModuleNotFoundError: No module named 'djangomako') like before.
- after Mako up-gradation table_browser opens perfectly.

[Mako] Opening table browser error need Mako upgradation

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/requirements.txt
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/lib/botserver/urls.py
desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/botserver/views_tests.py
desktop/core/src/desktop/settings.py
desktop/libs/metadata/src/metadata/conf.py

Botserver integrated with existing Hue server and is now serving at /slack/events/ for event from Hue App. The App greets user when user messages "hello hue".
Some points to note:
1. All secret keys need to me exported as environment variables for now.
2. ngrok is used to tunnel the incoming http post request (event) from slack to localhost/slack/events/
3. To use ngrok - 
- Download ngrok
- Run `ngrok http 8000` since hue dev server listens at port 8000
- Update the Request URL in "Enable Events" in the slack api. Append /slack/events/ as that is our endpoint.
4. Free version of ngrok's public URL session expires and also you need to keep terminal open else you have to generate other and update.
5. Config flag is set false by default for slack endpoint and it is enabled in the ini files. …

[slack] Botserver update with Hue App greeting

---

desktop/core/src/desktop/auth/backend.py
desktop/core/src/desktop/auth/backend_tests.py

- GH-1807 - [Django Upgrade] LDAP auth error: authenticate() missing 1 required positional argument: 'request'
- `request` argument is added

GH-1807 [Django Upgrade] LDAP auth error: authenticate() missing 1 required positional argument: 'request'

---

desktop/core/src/desktop/lib/thrift_/http_client.py

This PR addresses the issue described in HUE-1698 https://github.com/cloudera/hue/issues/1698
Namely an error seen whilst using thrift over HTTP 
`TypeError: string argument expected, got 'bytes'`
This error is only seen whilst using python 3.x and no issues seen in python 2.7.
Due to StringIO differences in py2 -> py3  we must use BytesIO module.
We reason that this is acceptable since the Thrift HTTP client also uses BytesIO in their THttpClient https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/http.py#L195
- This PR was built as a docker image and tested on our k8s environment. We  carried out fingerprinting of  sample datasets and compared against the latest-py2 docker image

Use BytesIO for Thrift over http

---

apps/beeswax/src/beeswax/server/dbms.py
desktop/libs/indexer/src/indexer/indexers/sql_tests.py

When generating SQL for load data, update the abfs path in full path
add a unit test and manually test in CDW

[importer] Use full abfs path in load data

---

desktop/core/src/desktop/conf.py

- Remove private=True from SLACK_CLIENT_ID.

[slack] Remove private=True from SLACK_CLIENT_ID.

---

desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/botserver/views_tests.py

- Removed get_bot_id() since to check its own message we no longer need bot id. This saves us from calling a slack API method 'user.list'
- Updated the UTs and added SkipTest

[slack] Remove get_bot_id() and update UTs

---

desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/botserver/views_tests.py

- Added gist unfurling
- Refactored views.py with link_unfurl section
- Updated on_handle_message UT
To-dos:
- Add on_handle_link_shared UT -- Done
- document does not exist or no access along with query sharing permissions
- [Blow-up issue](https://github.com/cloudera/hue/pull/1824#discussion_r583096054)
Follow-up of PR #1824

[slack] Refactor link-unfurl and update UTs

---

.github/workflows/autoclose-stale.yml

WIP
Need to add some labels to prevent blind closure of everything and the legit issues, e.g. 'roadmap' for example or 'triaged'
Will see for getting (lighter) workflow from https://github.com/kubernetes/kubernetes/issues

[ci] Adding autoclose stale PRs/Issues

---

desktop/core/src/desktop/api2_tests.py
desktop/core/src/desktop/models.py

- Updated the `test_gist_directory_creation` UT to reproduce the Multiple Gist Directories Exception( `Directory.MultipleObjectsReturned` )

Test to repro multiple Gist directories

---

desktop/core/requirements.txt

It allow user can install django-babel through proxy.
- Manual tests

support clone django babel through http proxy

---

.github/workflows/autosquash.yml

To avoid errors on PR on Forks:
https://github.com/tibdex/autosquash/issues/53

[ci] Run autosquash only on the Hue repo branches

---

desktop/core/ext-py/tabulate-0.8.9/CHANGELOG
desktop/core/ext-py/tabulate-0.8.9/LICENSE
desktop/core/ext-py/tabulate-0.8.9/MANIFEST.in
desktop/core/ext-py/tabulate-0.8.9/PKG-INFO
desktop/core/ext-py/tabulate-0.8.9/README
desktop/core/ext-py/tabulate-0.8.9/README.md
desktop/core/ext-py/tabulate-0.8.9/benchmark.py
desktop/core/ext-py/tabulate-0.8.9/setup.cfg
desktop/core/ext-py/tabulate-0.8.9/setup.py
desktop/core/ext-py/tabulate-0.8.9/tabulate.py
desktop/core/ext-py/tabulate-0.8.9/test/common.py
desktop/core/ext-py/tabulate-0.8.9/test/test_api.py
desktop/core/ext-py/tabulate-0.8.9/test/test_cli.py
desktop/core/ext-py/tabulate-0.8.9/test/test_input.py
desktop/core/ext-py/tabulate-0.8.9/test/test_internal.py
desktop/core/ext-py/tabulate-0.8.9/test/test_output.py
desktop/core/ext-py/tabulate-0.8.9/test/test_regression.py
desktop/core/requirements.txt
desktop/core/src/desktop/lib/botserver/views.py

- Removing Prettytable and using Tabulate module to make tables (compatible with Py2 and almost 2x faster)
- Making pivot result table which enables us to show large number of columns of query result but we can see only 2-3 rows in preview(keeping 2 so that it does not break when lengthy fields are seen)
Much cleaner now and lot more number of columns!

[slack] Prettify result preview unfurling

---

apps/useradmin/src/useradmin/ldap_access.py
apps/useradmin/src/useradmin/tests.py
desktop/core/src/desktop/lib/i18n.py

- in python3 -> smart_text -> smart_str (the are alias in python 3 attached ss)
- in python2 -> import smart_text as smart_str

[Django40 Warning] RemovedInDjango40Warning: smart_text() is deprecated in favor of smart_str()

---

desktop/core/src/desktop/lib/botserver/views.py

- Generate and upload the .xlsx result file in link message thread
- Introduced file_status flag which will check to only upload file when **result is available** (not upload when result expired or it is a gist)
- Refactored MockRequest code snippet for better readability and availability
- File can be downloaded from the message thread

[slack] Result file in link preview message thread

---

apps/beeswax/src/beeswax/server/dbms.py
apps/beeswax/src/beeswax/templates/list_designs.mako
apps/oozie/src/oozie/models.py
apps/oozie/src/oozie/models2.py
desktop/core/src/desktop/lib/django_forms.py
desktop/core/src/desktop/lib/exceptions_renderable.py
desktop/core/src/desktop/lib/i18n.py
desktop/libs/dashboard/src/dashboard/api.py
desktop/libs/hadoop/src/hadoop/fs/hadoopfs.py

- for py3 ->
`from django.utils.encoding import force_text as force unicode` to `from django.utils.encoding import force_str`
- for py2 ->
`from django.utils.encoding import force unicode` to `from django.utils.encoding import force_unicode as force_str`
and in the code `force_unicode` is changed to `force_str`
- 
links for the above ss -> 
- https://docs.djangoproject.com/en/3.0/_modules/django/utils/encoding/
- https://docs.djangoproject.com/en/3.1/ref/utils/

[Django4_warning_force_str] RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().

---

desktop/core/src/desktop/lib/botserver/views.py

- SLACK.IS_ENABLED is enough for new gist sharing
- We should not mix the old gist sharing with new

[slack] Remove ENABLE_GIST_PREVIEW config flag

---

desktop/core/src/desktop/middleware.py

- for py3 -> `from django.utils.http import url_has_allowed_host_and_scheme`
- for py2 -> `from django.utils.http import is_safe_url as url_has_allowed_host_and_scheme`
- 
- link -> https://docs.djangoproject.com/en/3.0/_modules/django/utils/http/
and in Django1.11 url_has_allowed_host_and_scheme is not present.
- link -> https://docs.djangoproject.com/en/1.11/_modules/django/utils/http/

[Django4 Warning] RemovedInDjango40Warning: django.utils.http.is_safe_url() is deprecated in favor of url_has_allowed_host_and_scheme()

---

desktop/core/src/desktop/lib/export_csvxls.py
desktop/core/src/desktop/middleware.py

- for python 3 -> `from urllib.parse import quote`
- fro python 2 -> `from django.utils.http import urlquote as quote`
For python3
- 
- 
for python2
- 
links ->
1-> https://docs.djangoproject.com/en/3.0/_modules/django/utils/http/
2 -> https://docs.djangoproject.com/en/1.11/_modules/django/utils/http/

[Django4.0 Warning] RemovedInDjango40Warning: django.utils.http.urlquote() is deprecated in favor of urllib.parse.quote()

---

desktop/core/src/desktop/js/apps/editor/EditorViewModel.js

Quick grepping: seems like a big bug where we should rename 'sharing_enabled --> enable_sharing'
sharing_enabled does not exist anywhere
In get_config
--> 'enable_sharing': ENABLE_SHARING.get()

[core] Sharing document is always turned off

---

desktop/core/src/desktop/js/jquery/plugins/jquery.notify.js
desktop/core/src/desktop/static/desktop/js/jquery.notify.js

- GH-1942 - Error message shown in UI should sanitised to prevent Html injection
- Tested manually with possible error / warn messages that can be shown in UI , it shouldnt have XSS injection possible.

[editor] jHueNotify Error message shown in UI should sanitised to prevent Html injection

---

desktop/core/src/desktop/middleware.py
desktop/core/src/desktop/middleware_test.py

821c7478f7 Upgrading pre-Django 1.10-style middleware
e6a8c0a934 HUE-9650 [Django Upgrade] Old-style middleware using settings.MIDDLEWARE_CLASSES is deprecated
manually test local dev env

[auth] Fix SpnegoMiddleware upgrade issue

---

desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/botserver/views_tests.py

- Retrieve email prefix from slack user for Hue user
- Add read perm check for link else raise PopupException
- Currently not checking for gist until sharing perms setup for gists
- Update UTs with read perm check
Ref. #1919 
- Successfully running unit tests

[slack] Add doc read permission check 

---

apps/filebrowser/src/filebrowser/templates/fb_components.mako

- #1965  -[filebrowser] GH-1965 Default Home directory button in Filebrowser should be sanitized and should trust the input from untrusted source
- Tested manually, The Fix works well.
-

Default Home directory button in Filebrowser should be sanitized and should trust the input from untrusted source

---

desktop/core/ext-py/django-axes-4.5.4/axes/migrations/0006_add_accessattempt_trusted.py

Login and Editor work fine with the unused DB column.
Add back `axes_accessattempt.trusted`:
Before:
mysql> describe axes_accessattempt;
+----------------------+---------------+------+-----+---------+----------------+
| Field                | Type          | Null | Key | Default | Extra          |
+----------------------+---------------+------+-----+---------+----------------+
| id                   | int           | NO   | PRI | NULL    | auto_increment |
| user_agent           | varchar(255)  | NO   | MUL | NULL    |                |
| ip_address           | char(39)      | YES  | MUL | NULL    |                |
| username             | varchar(255)  | YES  | MUL | NULL    |                |
| http_accept          | varchar(1025) | NO   |     | NULL    |                |
| path_info …

[lib] Revert django-axe 4.5.3 DB migration of `axes_accessattempt.trusted`

---

desktop/core/ext-py/django-axes-4.5.4/.travis.yml
desktop/core/ext-py/django-axes-4.5.4/axes/admin.py
desktop/core/ext-py/django-axes-4.5.4/axes/attempts.py
desktop/core/ext-py/django-axes-4.5.4/axes/migrations/0006_add_accessattempt_trusted.py
desktop/core/ext-py/django-axes-4.5.4/axes/models.py

Here we revert https://github.com/jazzband/django-axes/commit/60f2a8ed71698225fa93ca4047d61cfbdad0eac2
to put back the `trusted` column in the model.
But we don't delete the 0005 migration to avoid limbo in case it was
already applied.

[lib] Revert django-axe 4.5.3 Model removale of trusted column

---

desktop/core/src/desktop/redaction/engine.py
desktop/core/src/desktop/redaction/tests.py

- #1972 - redaction engine throws exception when the query is having non-ascii  character
- Tested manually in Python-3 and python-2 server , fix works well

[redaction] redaction engine throws exception when the query is having non-ascii character

---

desktop/core/src/desktop/js/api/utils.ts
desktop/core/src/desktop/js/apps/editor/components/QueryEditorWebComponents.ts
desktop/core/src/desktop/js/apps/editor/components/sqlScratchpad/SqlScratchpad.scss
desktop/core/src/desktop/js/apps/editor/components/sqlScratchpad/SqlScratchpad.vue
desktop/core/src/desktop/js/apps/editor/components/sqlScratchpad/SqlScratchpadWebComponent.d.ts
desktop/core/src/desktop/js/apps/editor/components/sqlScratchpad/SqlScratchpadWebComponent.ts
package.json
webpack.config.npm.js

One component containing everything needed to edit, execute and view the results.
Usage:
```
import sqlScratchpadComp from 'gethue/lib/components/SqlScratchpadWebComponent';
sqlScratchpadComp.setBaseUrl('http://banana');
await sqlScratchpadComp.login('hue', 'hue');
```
in html
`<sql-scratchpad dialect="mysql" />`

Expose a single sql-scratchpad component

---

desktop/core/src/desktop/js/apps/editor/components/aceEditor/autocomplete/AutocompleteResults.ts

if(path) -> if ((this.dialect() == PHOENIX_DIALECT && path == '') || path)

[Phoenix] Column autocomplete is failing for empty('') db

---

apps/filebrowser/src/filebrowser/views.py
apps/filebrowser/src/filebrowser/views_test.py
desktop/core/src/desktop/auth/backend.py
desktop/core/src/desktop/js/jquery/plugins/jquery.filechooser.js
desktop/libs/aws/src/aws/s3/s3fs.py

Fix the issue that when only S3 or ABFS is configured, file chooser won't throw exception and show a spinner inside the file chooser
1. only S3 is configured
2. only ABFS is configured
3. S3 and HDFS are configured
4. ABFS and HDFS are configured

[importer] Add default_s3_home and initiate value in  getfilesystem

---

desktop/core/src/desktop/js/ko/components/ko.editorDroppableMenu.js

- adding select sample for empty('') database only for phoenix dialect
-

[Phoenix] Drag & Drop table from assist only sets the table name and not SELECT sample

---

desktop/core/src/desktop/js/jquery/plugins/jquery.notify.js

This introduce a blacklist of error messages to avoid.
Some error will happen occasionally and will confuse the users.
Most of the ones seen are on idempotent calls, not critical (e.g. get
progress logs) and can be only logged in the consol.
Could be done here or in notifyError, but feels like we might miss some
there.
Note that the main cause is not necessary Hue itself replying with a 504, but could
be an underlying service replying with a 504 error which is not caught by the
Hue API (even if it should).
Hue has 100s of different calls possible and some main "culprits"
like get_logs could be handle on a per by case, but we need a catch all
solution too.
As these errors come the API, they are already logged (no need to

[ui] Avoid displaying any API error in a popup

---

desktop/core/src/desktop/middleware.py

After deploying Hue 4.9 I got the following error:
AttributeError: 'HueRemoteUserMiddleware' object has no attribute 'get_response'
I have Hue set up with
backend=desktop.auth.backend.RemoteUserDjangoBackend, httpd is in front
of it with Apereo Cas and passes the username as part of a remote
header. Never seen this issue before, but I suspect it is related to
libraries upgraded. The other backend have it as well, and adding it
makes everything work (as opposed to get a HTTP 500).
- Add get_response to the HueRemoteUserMiddleware class to avoid exceptions and HTTP 500 during runtime.
Tested with Hue 4.9, with httpd in front of it with Apereo CAS (passing the username via http header)
Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before …

[core] Add get_response to HueRemoteUserMiddleware

---

desktop/core/src/desktop/auth/backend.py

This patch is needed for Django 2.1+ since the
django.contrib.auth.authenticate() function requires 'request' as
positional argument. In #2004 we partially addressed the issue, but not
completely.
This commit is present only in Django 1.11's and 2.0's branches:
https://github.com/django/django/commit/3008f30f194af386c354416be4c483f0f6b15f33
There is a warning msg stating that 'request' should be moved as first
positional argument.
Add a new parameter to the RemoteUserDjangoBackend backend class since it is required by Django 2.1+.
Tested live patching a 4.9 testing release.

[core] Add request as positional arg for RemoteUserDjangoBackend

---

apps/oozie/src/oozie/models2.py

Replace ABFS path with full path in data['properties']['files']), so avoid following error from Shell-action workflow log:
```
org.apache.oozie.action.ActionExecutorException: JA009: abfs://my_container/testdata/TestLangShell.sh#TestLangShell.sh has invalid authority.
at org.apache.oozie.action.ActionExecutor.convertExceptionHelper(ActionExecutor.java:469)
at org.apache.oozie.action.ActionExecutor.convertException(ActionExecutor.java:447)
at org.apache.oozie.action.hadoop.JavaActionExecutor.submitLauncher(JavaActionExecutor.java:1181)
at org.apache.oozie.action.hadoop.JavaActionExecutor.start(JavaActionExecutor.java:1723)
at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.java:243)
at org.apache.oozie.command.wf.ActionStartXCommand.execute(ActionStartXCommand.ja …
```

[oozie] Replace ABFS path in workflow files with full path

---

desktop/core/src/desktop/lib/botserver/api.py
desktop/core/src/desktop/lib/botserver/api_tests.py
desktop/core/src/desktop/lib/botserver/slack_client.py
desktop/core/src/desktop/lib/botserver/urls.py
desktop/core/src/desktop/lib/botserver/views.py

- `get_channels` -> all channels where bot is present
- Separate api.py and api_tests.py for unit tests
- Add url
- Successfully running UTs
- Currently default limit is 100 channels, add dealing with pagination and fetching channels with [cursor](https://api.slack.com/methods/users.conversations#arg_cursor)?? @romainr

[slack] Add get_channels API and its UTs

---

desktop/core/src/desktop/js/jquery/plugins/jquery.filechooser.js

Only setup S3 file system in Hue config. When the file chooser open the very 1st time, it display S3 icon and file system. When open again, the initialPath is empty string, so file chooser only shows HDFS file system and S3 disappear.
Analysis:
The first time file chooser get called is via Plugin.prototype.init(). (fix in https://github.com/cloudera/hue/pull/1983)
After first call, file chooser get called is via Plugin.prototype.setOptions().
Tested locally with single filesystem, 2 filesystem and 3 filesystems three different setups.

[importer] Fix filechooser has no initialPath

---

desktop/core/src/desktop/js/ko/components/ko.shareGistModal.js
desktop/core/src/desktop/lib/botserver/api.py
desktop/core/src/desktop/lib/botserver/api_tests.py

- Add hue username which send the link in Slack

[slack] Add username in Slack message for author context

---

apps/oozie/src/oozie/views/dashboard.py

There are 2 issues fixed for submit_external_job
1. add '/' back to application_path due knox
2. add '@' domain for ABFS path
Tested DH clusters

[oozie] Fix application path for submit_external_job

---

tools/kubernetes/helm/hue/templates/ingress-http.yaml
tools/kubernetes/helm/hue/templates/ingress-https.yaml
tools/kubernetes/helm/hue/templates/ingress-traefik-hue.yaml
tools/kubernetes/helm/hue/values.yaml

Split of #2065
Allow defining extra hosts for ingress. This would make it possible the network ingress accepts alternative domains.
Example in values file:
```
ingress:
create: True
type: "ngnix"
domain: "hue.k8s.domain.io" # main domain zone controlled by external-dns
extraHosts:
- "hue.domain.io" # CNAME in public domain zone
``` 
- Manual testing by upgrading an existing deployment

[helm] Allow defining extra hosts for ingress

---

tools/kubernetes/helm/hue/templates/ingress-http.yaml
tools/kubernetes/helm/hue/templates/ingress-https.yaml
tools/kubernetes/helm/hue/templates/ingress-traefik-hue.yaml
tools/kubernetes/helm/hue/values.yaml

Split of #2065 (reopen #2067 in new branch)
- Support extra annotations for ingress. This would permit setting extra annotations for ingress. Example in values file:
```
ingress:
create: True
type: "ngnix-ssl"
domain: "hue.k8s.domain.io"
annotations:
nginx.ingress.kubernetes.io/force-ssl-redirect: "true" # force redirection to HTTPS
```
- Manual testing by upgrading an existing deployment

[helm] Support custom annotations for ingress

---

tools/kubernetes/helm/hue/templates/ingress-http-v1.yaml
tools/kubernetes/helm/hue/templates/ingress-http-v1beta.yaml
tools/kubernetes/helm/hue/templates/ingress-https-v1.yaml
tools/kubernetes/helm/hue/templates/ingress-https-v1beta.yaml

Split of #2065 (same as #2068 but in new PR to run CI)
- Upgrade apiVersion to networking.k8s.io/v1 in k8s 1.19+
The apiVersion networking.k8s.io/v1beta1 is deprecated in k8s 1.19+ and would be removed in k8s 1.22
To keep the templates cleaner, it was created a different file `ingress-http-v1` and rename the older ingress to `ingress-http-v1beta`, checking which version to use by a condition on the file header:
ingress-http-v1:
```
{{- if and .Values.ingress.create (eq .Values.ingress.type "nginx") (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
...
- host: {{ .Values.ingress.domain }}
http:
paths:
- backend:
service:
name: hue-balancer
port:
number: 80
pathType: ImplementationSpecific
path: /
```
ingress-http-v1beta:
``` …
```

[helm] Use apiVersion to networking.k8s.io/v1 in k8s 1.19+

---

tools/kubernetes/helm/hue/Chart.yaml

Change list:
d9fa32fe6b Double-check https ingress trailing dash
9b98a355b6 [helm] rename current ingress to v1beta
43b86d9aa8 [helm] create networking.k8s.io/v1 for k8s 1.19+
9a24301d8c [helm] support custom annotations for ingress
c40e996b26 [k8s] Ingress and deployment for Daphne
1a97eba9c2 [k8s] Add config hash to deployments
341b2e80ce [k8s] Adding daphne properties
95db44d63d Use hue service name and port for traefik
1491436f40 Allow defining extra hosts for ingress

[k8s] Bump the helm version up to 1.0.3

---

desktop/core/requirements.txt
desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/botserver/views_tests.py

- Return only those email prefixes whose email domain match with the host domain.
- Eg: Assuming host_domain as `gethue.com`
If Slack user email is alice@gethue.com, then return `alice`
If Slack user email is henry@example.com, then return None
- Patch tested by successfully updating and running unit tests

[slack] Email domain check with host domain

---

desktop/libs/indexer/src/indexer/templates/importer.mako

- adding connector id correctly to remove the 'type' error

[importer_direct_upload] adding connector in snippet to remove the 'type' error

---

desktop/core/src/desktop/js/parse/types.ts

Marks some fields of `AutocompleteParseResult` as optional to reflect that they won't always be present.
I noticed this when inspecting some result objects I got from `genericAutocompleteParser.parseSql` that a bunch of non-optional fields often weren't present:
Not tested, but since this is only a type change, as long as the project compiles, it should be fine. I just made this change in the online editor and didn't even attempt to build things locally, so not sure if there will be type errors or not - will let CI determine that for me 😆 

Update AutocompleteParseResult type

---

desktop/core/src/desktop/lib/botserver/views.py

- Changed extracting text from Slack messages from message blocks. This reduces the need of unescaping markdown and HTML characters (e.g. `<` as `&lt;` and triple backticks code block)
- Detect SELECT statements in Slack messages
- Currently seen in Slack messages, that people usually post SELECT statements in code blocks or as separate normal messages.

[slack] Detect SELECT statements in Slack messages

---

desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/exceptions_renderable.py

- By default, it is 500 status code (Internal server error). This does not acknowledge the Slack event request, thereby Slack sends request again and again.
- With status 200, Slack event request will be acknowledged and also it will not clutter logs with multiple tries now

[slack] Give status 200 with PopUpException

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/botserver/views_tests.py

- Removed ephemeral messages -- Cant be used in unfurling
- Detect SELECT statements
- Check Slack user permission to create gist
- Create gist and send link
- Can be shown in the message thread too if we don't want to clutter up the Slack channels

[slack] Give gist link for detected SELECT statements

---

desktop/core/src/desktop/views.py

File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/utils/deprecation.py", line 114, in __call__
response = response or self.get_response(request)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 49, in inner
response = response_for_exception(request, exc)
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 103, in response_for_exception
response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
File "/usr/share/hue/build/env/lib/python3.6/site-packages/django/core/hand …

[lib] Avoid infinite loop on 500 errors in file chooser popup

---

desktop/core/src/desktop/lib/thrift_sasl.py
desktop/core/src/desktop/lib/thrift_util.py

As SASL not required in standard setup anyway.

[libs] Workaround potential version `GLIBCXX_3.4.26' not found

---

desktop/core/src/desktop/js/apps/notebook/snippet.js

- self.type() is a number in case of enable_connector = true because of it we are not getting the snippet view settings?
- https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/js/apps/notebook/snippet.js#L211
- https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/templates/editor2.mako#L1060

[importer_direct_upload] correcting the dialect value when enable_connector=true

---

desktop/core/requirements.txt

Python 3 only. So that the exetensions work again with latest Django.
e.g.
./build/env/bin/hue show_urls

[libs] Upgrade django-extensions to 3.1

---

desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/botserver/views_tests.py

- `type` changes when enable_connectors is enabled. Using more trusted field for smoother `dialect` name
- Successfully running unit test
For demo.gethe.com

[slack] Fix dialect when creating gist for detected SQL

---

desktop/core/requirements.txt

Trying to avoid
File "/usr/share/hue/build/env/lib/python3.6/site-packages/rest_framework_simplejwt/backends.py", line 43, in encode
return token.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
https://github.com/jazzband/djangorestframework-simplejwt/issues/326

[libs] Bump djangorestframework-simplejwt

---

desktop/core/src/desktop/settings.py

Note: regular Hue will work like before, via SS Component
the API calls will have the allow header.
If all good, we should remove `cors_enabled` prop and have it all
the time on.

[api] Apply CORS to /api automatically

---

desktop/core/src/desktop/lib/botserver/api.py
desktop/core/src/desktop/lib/botserver/api_tests.py
desktop/core/src/desktop/lib/botserver/views.py
desktop/core/src/desktop/lib/botserver/views_tests.py

- Better error messages in message thread for end-user context
- Error message does not clutter chat window now since in message thread
- Fix Detect SQL SELECT for Slack users not Hue users by sending the copy/paste message but not the gist(requires Hue account)
- Invalid Link
- Mark not having hue account scenario
- gets no Hue account message in thread to de-clutter chat

[slack] Refactor for better end-user usability

---

tools/app_reg/registry.py

Remove the duplicated line 
```from builtins import object```
because there is another one below
```
if sys.version_info[0] > 2:
from builtins import object
```
Run canary build and passed this error

[core] Remove duplicated line that cause build issue

---

desktop/core/src/desktop/lib/rest/http_client.py
desktop/core/src/desktop/lib/rest/http_client_test.py

To disable SSL verification in http_client.py one need to pass it to the session.get(url, verify=False). The current code just sets the _session object which is not taken into account.
Verified this fix by making the change in the live cluster.

Enable disabling SSL verification in http_client.py

---

apps/filebrowser/src/filebrowser/views.py
apps/jobsub/src/jobsub/views.py
desktop/core/src/desktop/lib/metrics/views.py
desktop/core/src/desktop/lib/vcs/apis/github_api.py
desktop/core/src/desktop/lib/view_util.py
desktop/core/src/desktop/middleware.py
desktop/core/src/desktop/views.py

- request.is_ajax() -> request.headers.get('x-requested-with') == 'XMLHttpRequest'

[Django upgrade] RemovedInDjango40Warning: request.is_ajax() is deprecated in Django3.1

---

desktop/core/ext-py/boto-2.46.1/boto/connection.py
desktop/core/ext-py/boto-2.46.1/boto/s3/key.py

This enables to reuse the boto HttpRequest client with Raz signed URLs.
The Raz URLs are signed and the User Agent is part of the signature,
so this one should not be changed.

[lib] Change boto2 to not override the User Agent if already present

---

docs/gethue/themes/stack-hue-theme/layouts/partials/home.en.html

- Add Docs link instead of blog in the slack section on gethue.com

[slack] Add docs link in gethue.com Slack section

---

Makefile

Fix install PIP_MODULES in the build system when it calls "make apps docs", which is value of $(MAKECMDGOALS)
Running a canary build

[core] Fix PIP_MODULES installation on build system

---

desktop/core/requirements.txt

- when I change the Django version to 3.2 then I am hitting the [same](https://github.com/cloudera/hue/pull/1711) issue "**ModuleNotFoundError: No module named 'djangomako**'" as we were hitting earlier.
- so done all changes in my repo if approved then will transfer that to gethue.

[django_upgrade32] djangomako supporting Mako==1.1.4 now

---

desktop/core/src/desktop/js/ko/components/assist/ko.assistDbPanel.js

Note that this also enables the importer for all connectors

[assist] Only show the + in the DB assist when the importer browser is present in the config

---

docs/gethue/content/jp/posts/2021-05-18-installing-hue-slack-app-in-three-simple-steps.md
docs/gethue/content/jp/posts/2021-05-26-improved-hue-importer-select-a-file-choose-a-dialect-create-a-table.md
docs/gethue/content/jp/posts/2021-05-29-create-own-sql-editor-via-webcomponent-and-public-api.md
docs/gethue/content/jp/posts/2021-06-14-release-hue-4-10.md

Hi Hue Team,
Congratulations on the release of Hue 4.10! I translated the hue blogs into Japanese.
- Localized the blogs published in May-Jun into Japanese
- Verified on my browser using 'hugo serve'
Please let me know if you have any questions.
Regards,
--
Tatsuo

[blog] Localized blogs published in May-June 2021 into Japanese

---

desktop/core/src/desktop/js/ko/components/doc/__snapshots__/ko.linkSharing.test.js.snap
desktop/core/src/desktop/js/ko/components/doc/ko.linkSharing.js

- Fixes long sharing links issue by having default horizontal scroll than using `div` to show link.

[editor] Use gist link input field for sharing saved query

---

desktop/libs/metadata/src/metadata/metadata_sites.py

Jira: CDPD-14904
Since Nav is not being used the audit logs are not collected. Just by adding the default path to /var/log/hue addresses the issue.

Hue audit logs are no longer being collected if Nav is not in use.

---

desktop/core/src/desktop/lib/fs/__init__.py
desktop/core/src/desktop/lib/raz/clients.py
desktop/core/src/desktop/lib/raz/raz_client.py
desktop/core/src/desktop/lib/rest/http_client.py
desktop/core/src/desktop/lib/rest/raz_http_client.py
desktop/core/src/desktop/lib/rest/raz_http_client_test.py
desktop/libs/azure/src/azure/abfs/abfs.py
desktop/libs/azure/src/azure/client.py
desktop/libs/azure/src/azure/conf.py

- [aws] Do not enabled S3 when Azure Raz is enabled
- [fs] Fix left out Python 2 url lib import
- [abfs] Do not require Hue admin privileges for access if RAZ is enabled
- [abfs] Do not require credentials in client when Raz is on
- [abfs] Do not try to set credentials headers when Raz is on
- [abfs] Go through Raz when enabled

[abfs] Do not try to set credentials headers when Raz is on

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py

Fix to Issue #2274. Where hive properties would cause spark-shell to fail to start for sparksql with livy in hue
Applied this to a version of HUE running in EMR.

Fix bug in spark shell when used with hive

---

desktop/core/src/desktop/api_public.py

- Updated the _patch_operation_id_request function to decouple the snippet logic.
- Tested manually by running `show tables` query and then using APIs which call this method

[api] Refactor _patch_operation_id_request in public APIs

---

desktop/core/src/desktop/js/catalog/api.ts

TypeError: JSON.bigdataParse is not a function

[sqls] Avoid JSON.bigdataParse is not a function on result display

---

desktop/core/requirements.txt

2.4 is old and does conflict with newer libs

[pypi] Bump dateutil to 2.8.1

---

apps/beeswax/src/beeswax/server/hive_server2_lib.py

Same as for impala.
This works around/solves an issue where Spark's Thriftserver fails when a wildcard/asterisk is used as schemaName
Tested manually
Fixes part of #2252

HiveServerClient: Set schemaName to None for sparksql

---

docs/docs-site/content/administrator/configuration/connectors/_index.md

- Added the DB name change note for the error `django.db.utils.OperationalError: (1054, "Unknown column 'useradmin_huepermission.connector_id' in 'field list'")`
- Improved adding connector by UI section
- Given public REST API as option too.

[docs] Improve enabling and adding connector section

---

apps/filebrowser/src/filebrowser/templates/listdir.mako
apps/filebrowser/src/filebrowser/templates/listdir_components.mako

- adding a button to copy the URL of the selected file/folder.
- enabled when only 1 file or folder is selected.
- adding ss

[File Browser] Providing buttom 'Copy Path' for easy copy of S3 URL path in File Browser

---

desktop/core/src/desktop/auth/api_authentications.py
desktop/core/src/desktop/auth/api_authentications_tests.py

- Decode JWT token
- Find or create user from payload data
- Update tests for existing user, new user, authentication scenarios
- Token persistance
- Secret key handling and decide algorithm
- Successfully implementing and running unit tests

[api] Add JWT token decoding

---

desktop/core/requirements.txt

[libs] Bump django celery result to latest

---

desktop/core/src/desktop/js/utils/url/changeURLParameter.ts

when there is more than one params in url, the `&` between params will lost

changeURLParameter  fixbug

---

apps/impala/src/impala/conf.py
desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/libs/indexer/src/indexer/indexers/sql.py

The only way to over come this is to have the scratch dir and its underlying file to be of 777.
Exception seen when the load command fails:
QueryError: AnalysisException: Unable to LOAD DATA from hdfs://<HDFS_PATH>/.scratchdir/6749117b-f371-4bac-a2aa-b06cb45330e3/test_data.csv because Impala does not have READ permissions on this file
This fix was tested out at a customer end which worked.
Internal Jira: CDPD-28169
PR: 2374

Importer fails with READ permission due to IMPALA-10272

---

apps/filebrowser/src/filebrowser/templates/listdir.mako
desktop/core/src/desktop/js/api/urls.js
desktop/core/src/desktop/js/ko/bindings/ace/ko.aceEditor.js
desktop/core/src/desktop/models.py
desktop/core/src/desktop/templates/common_header.mako

If not we miss this checks:
if path.startswith('abfs:/') and not path.startswith('abfs://'):
path = path.replace('abfs:/', 'abfs://')
if path.startswith('s3a:/') and not path.startswith('s3a://'):
path = path.replace('s3a:/', 's3a://')

[aws] Standardize as lower case s3a:// prefix to avoid corner cases

---

docs/docs-site/content/administrator/configuration/connectors/_index.md

- This PR adds a note in the documentation for Trino connector about a configuration that must be added in Trino for Hue to work with it
- Faced this [issue](https://github.com/cloudera/hue/issues/2389) which got fixed by adding the mentioned configuration in Trino

update trino connector configuration with note about alternate headers

---

desktop/core/src/desktop/middleware.py

- If user 'hue' is not present, then auto-create it for the 'auto_login_enabled' config flag along with authenticating it.

[auto_login] Auto create 'hue' user for auto_login config flag

---

desktop/libs/notebook/src/notebook/api.py

- Removing the DRF Public API view from notebook/api.py create_session.
- Successfully executing the `create_session` public API (auth token in bearer)

[create_session] Remove public API POST view from notebook_api

---

desktop/libs/indexer/src/indexer/templates/importer.mako

- Adding column check only alphanumeric and '_' are allowed because
- as hive [not supporting](https://issues.apache.org/jira/browse/HIVE-10120) the '.' and ':'. And we also not supporting special chars as of now.
- impala only [supports](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/acreldb/n0zbh5w5ucvt2gn1t1gnpm6e0sl3.htm#:~:text=Impala%20table%20and%20column%20names,converts%20uppercase%20characters%20to%20lowercase.) the alphanumeric and '-'

[importer] adding column name check in the importer

---

apps/useradmin/src/useradmin/views.py

Jira: CDPD-28523
Based on the information from Security SME fixed the groups_filter to have multiple options based on what is provided.

Invalid attribute syntax in Hue find_groups_filter

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/auth/api_authentications.py
desktop/core/src/desktop/auth/api_authentications_tests.py
desktop/core/src/desktop/conf.py

- Defaults to True.
- If set to False, then will not verify the signature of the JWT token (recommended for testing purposes only).
- Add debug level log for `user id` and `tenant id`
- Change payload field (userId -> user)
- Since we are using `PyJWT==1.7.1`, to not verify signature we used `jwt.decode(..., verify=False)`. In latest releases and PyJWT docs, it has been changed to `jwt.decode(..., options={'verify_signature'=False})`
- Adding and successfully running unit test

[jwt] Add verification config flag for custom JWT Authentication

---

desktop/libs/indexer/src/indexer/templates/importer.mako

- Removing 'Search index' for 'Manually'  Source type input.
- So now we have three options (Table, Database, Folder) for the manual set as you can see in the attached ss.
- Need to remove the Database and Folder options also?

[importer] removing 'Search index' option from drop down menu for 'manual' setup

---

apps/filebrowser/src/filebrowser/templates/fb_components.mako

- After searching got this link -> https://css-tricks.com/fighting-the-space-between-inline-block-elements/
before commit ->

[filebrowser] removing extra whitespace between the path

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/auth/api_authentications.py
desktop/core/src/desktop/auth/api_authentications_tests.py
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/settings.py

- Much cleaner config flags and values to enable it
- Separate section [[[jwt]]] under [[auth]]
- Update unit tests
```
[[auth]]
[[[jwt]]]
```

[jwt] Refactor custom JWT authentication config

---

desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py

- Change impersonation to use principal_username parameter introduced
in PyHive 0.6.2
- Fix #1285
- This will fix #1285
- `build/env/bin/hue test specific notebook`: success
- manual test

Change impersonation to use principal_username

---

desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceEditor.vue
desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceLocationHandler.ts
desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceSyntaxDropdown.scss
desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceSyntaxDropdown.vue
desktop/core/src/desktop/js/apps/editor/components/aceEditor/__snapshots__/AceEditor.test.ts.snap
desktop/core/src/desktop/js/apps/editor/components/aceEditor/autocomplete/AutocompleteResults.ts
desktop/core/src/desktop/js/apps/editor/components/aceEditor/events.ts
desktop/core/src/desktop/js/components/dropdown/DropdownDivider.vue
desktop/core/src/desktop/js/components/dropdown/DropdownDrawer.scss
desktop/core/src/desktop/js/components/dropdown/DropdownDrawer.vue
desktop/core/src/desktop/js/components/dropdown/DropdownMenuOptions.vue
desktop/core/src/desktop/js/components/dropdown/types.ts
desktop/core/src/desktop/js/parse/types.ts
desktop/libs/notebook/src/notebook/templates/editor2.mako

Just for editor v2 and still need to wire up the web workers in the web component.

[editor] Convert the mako syntax drop down to Vue and add it to the editor web component

---

desktop/core/src/desktop/auth/api_authentications.py

Moving from using Hue's JWT token to use external auth JWT token, and adding a dummy custom API auth class for development in local dev environment where doesn't have an external authentication service available.
Use cURL command to test following config
```
[desktop]
[[auth]]
api_auth=desktop.auth.api_authentications.DummyCustomAuthentication
```

[jwt] Allow developers test API calls without token in local dev env

---

desktop/core/src/desktop/js/ko/components/assist/ko.assistDbPanel.js

- error was when click on stream logo in left assist-> 
- error gone after 'ksql' dialect

[connector] correcting the name form 'kafka sql' to 'ksql'

---

desktop/core/src/desktop/lib/rest/raz_http_client.py
desktop/core/src/desktop/lib/rest/raz_http_client_test.py

- With extra params according to Azure APIs, the SAS token appending was not working properly.
- This fix will only append `?action=getStatus` only once and wont call `self._make_url(...)` again in the [base class `HttpClient`](https://github.com/cloudera/hue/blob/c843c7a8f7880663cabe17882e309eef068a5c88/desktop/core/src/desktop/lib/rest/http_client.py#L203).
- Fixing and running unit tests

[raz] Fix SAS token appending in url

---

desktop/core/src/desktop/auth/api_authentications.py

After using external JWT auth service, it was working. But there are a few logs shows error "no authorization header." Simply add the request.path in the log to help which API call throws error.
Tested locally with/wo jwt token to see if the path get logged for cURL commands.

[jwt] Add request path to help debug API calls

---

desktop/core/src/desktop/auth/api_authentications.py
desktop/core/src/desktop/auth/api_authentications_tests.py

- Fetch RSA public key from the key_server to be used in decoding of JWT.
- If verify flag is False, then it will not be fetched.
- Update unit tests for patching request call.

[jwt] Fetch RSA public key from key_server

---

desktop/core/src/desktop/lib/rest/raz_http_client.py
desktop/core/src/desktop/lib/rest/raz_http_client_test.py

- Implementing comments after the merge of the PR: https://github.com/cloudera/hue/pull/2465
- Updated and successfully running unit tests.

[raz] Raise 503 exception for no SAS token and cleaner tests

---

desktop/libs/metadata/src/metadata/optimizer_api.py

Currently on demo.gethue:
[2021-08-28 12:04:01 +0000] [34] [DEBUG] POST /api/optimizer/query_risk/
[28/Aug/2021 05:04:01 -0700] optimizer_api ERROR    the JSON object must be str, bytes or bytearray, not 'NoneType'
File "/usr/share/hue/desktop/libs/metadata/src/metadata/optimizer_api.py", line 60, in decorator
return view_fn(*args, **kwargs)
File "/usr/share/hue/desktop/libs/metadata/src/metadata/optimizer_api.py", line 200, in query_risk
query = json.loads(request.POST.get('query'))
File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

[api] Also lookup for query in snippet in risk call

---

desktop/core/src/desktop/lib/raz/raz_client.py
desktop/core/src/desktop/lib/raz/raz_client_test.py

- Added mapping for create operations (create file and directory) and delete operations (only specific path or recursive).
- Updated and running unit tests.

[raz_adls] Add create and delete operations mapping

---

apps/useradmin/src/useradmin/ldap_access.py

#2370  - Hue Login Failed attempt should not expose bind_dn into the Login screen
-Tested Manually

GH-2370 Hue Login Failed attempt should not expose bind_dn into the Login screen

---

desktop/core/src/desktop/lib/raz/raz_client.py
desktop/core/src/desktop/lib/raz/raz_client_test.py

- Required when creating file with data and also uploading should work out of the box now.
- Creating empty file --> calls create(), stats() --> working great.
- Creating file with data  --> calls create(), stats(), _append(), flush()
- create() needs mapping --> `create-file`
- Now this _append() and flush() , both of them works with mapping —> `create-file` and also with mapping --> `write`
- And upload needs them, so choosing the mapping `write` since it looks much more logical.
- Updating and running unit tests.

[raz_adls] Add append and flush operation mapping

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/auth/api_authentications.py
desktop/core/src/desktop/auth/api_authentications_tests.py
desktop/core/src/desktop/conf.py

If the audience is not set (None), the InvalidAudienceError will be thrown. And also if issuer is set in JWT token, we should also verify it.
>>> payload = jwt.decode(access_token, public_key_pem, algorithms=["RS256"], verify=True)
File "<console>", line 1, in <module>
File "/opt/hive/build/env/lib/python2.7/site-packages/PyJWT-1.7.1-py2.7.egg/jwt/api_jwt.py", line 104, in decode
self._validate_claims(payload, merged_options, **kwargs)
File "/opt/hive/build/env/lib/python2.7/site-packages/PyJWT-1.7.1-py2.7.egg/jwt/api_jwt.py", line 140, in _validate_claims
self._validate_aud(payload, audience)
File "/opt/hive/build/env/lib/python2.7/site-packages/PyJWT-1.7.1-py2.7.egg/jwt/api_jwt.py", line 189, in _validate_aud
raise InvalidAudienceError('Invalid …

[jwt] Add issuer and audience for token verification

---

apps/beeswax/src/beeswax/server/hive_server2_lib.py

Get a wrong user 'hue' at https://github.com/cloudera/hue/blob/56a6c734b04679ad4c009d71d959d4d6325855d4/desktop/core/src/desktop/lib/thrift_util.py#L344. 
Added a condition to use the right user instead 'hue'.
Test Impala call via local dev to a DC cluster and capture tcpdump for port 28000.

[jwt] Fix thrift_util to use the right user

---

.circleci/config.yml

This is the first part of https://github.com/cloudera/hue/pull/2531
This PR changes the version of CircleCI config from `2.0` to `2.1`. This is needed to be able to use [reusable config](https://circleci.com/docs/2.0/reusing-config/) functionality in the next PR.
`2.1` does not allow usage of `.` (dot) in the job names.
Only CircleCI's config.yml has been modified. CircleCI jobs should still work!

CircleCI: Bump version to 2.1

---

desktop/libs/aws/src/aws/client.py
desktop/libs/aws/src/aws/conf.py
desktop/libs/aws/src/aws/conf_tests.py

- Check for RAZ URL and AWS_ACCOUNT Hostname in the config this time.
- In RAZ ADLS cluster, the AWS_ACCOUNT Hostname should not be present practically.
- Successfully updating and running unit tests.

[raz_s3] Do not enable S3 browser in ADLS

---

desktop/libs/librdbms/src/librdbms/server/mysql_lib.py

- #2373  -  disable local_infile in RDBS mysql client by default 
Currently Hue is using mysql-connector-python via SQLAlchemy and its having the value of local_infile as True which is causing the #2373 , we should disable it so that there is no security risk of accessing files of hue server via any fake SQL server
Reference : https://mysql.wisborg.dk/2019/02/07/mysql-connector-python-8-0-15-allow_local_infile-disabled-by-default/
-  Tested Manually.

GH-2373 disable local_infile in RDBS mysql client by default 

---

.circleci/config.yml

- `build-py-36` Circle CI check is failing with the following error:
```
Ign:1 https://deb.nodesource.com/node_14.x bionic InRelease
Err:2 https://deb.nodesource.com/node_14.x bionic Release                  
Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 23.62.230.111 443]
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease                    
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]    
Get:7 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages …
```

[ci] Upgrade ca-certificates for `build-py-36` Circle CI check

---

apps/jobbrowser/src/jobbrowser/apis/query_store.py

- Pass cookie info to query_store
- Disable SSL verify

[jobbrowser] Pass cookie info to query_store

---

apps/jobbrowser/src/jobbrowser/conf.py
desktop/core/src/desktop/models.py

- We should not use the `enable_hive_query_browser` flag as it is not fully completed feature.
- Jobs left assist should be enabled when there is no Hive Query browser mentioned above and YarnRM, else when the Jobbrowser is not blacklisted, then also it wont be accessible in the case of Hive VWs.
- So, when Hive VWs uses Query Store, now left Jobbrowser tab is accessible in which user can find details about Hive queries under `Queries` tab.

[jb] Enable left assist jobbrowser when Query Store is present

---

desktop/libs/notebook/src/notebook/api.py

public API call fetch_result_data is checking has_result_set from snippet/result/handle. If execute_statement get has_result_set is false, then we should update has_result_set after running check status.
tested real cluster.

[editor] Update has_result_set from check_status response for public API

---

desktop/core/ext-py/Django-1.11.29/tests/requirements/base.txt

- Having couple of CVEs ranging from high to critical in the current version.
- Version suggested by dependabot (>=8.3.2) required Python 3.6 and above.
- Used in Django 1.11.29 tests so we can remove and ignore most probably

[CVE] Remove pillow from Django 1.11.29 ext-py package

---

desktop/core/ext-py/pysaml2-4.9.0/src/saml2/sigver.py

After enable response and assertion is signed, SAML login got this error:
```
Traceback:
File "/opt/cloudera/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/exception.py" in inner
41.             response = get_response(request)
File "/opt/cloudera/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py" in _legacy_get_response
249.             response = self._get_response(request)
File "/opt/cloudera/parcels/CDH-7.1.7-1.cdh7.1.7.p0.15945976/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py" in _get_response
187.                 response = …
```

[saml] Fix key_file has no attribute 'strip' when resp assertion signed

---

desktop/core/src/desktop/api_public.py

- It is required because only one statement gets executed via the API call. So, queries like `show tables;` gets executed but since no database is mentioned so it always picks the default database.
- Therefore, with this optional param, we can mention specific database for similar queries like above.

[api] Add optional database param for /execute public API

---

desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceEditor.vue
desktop/core/src/desktop/models.py

- For notebook2 editor name changed to "HPL/SQL" and added placeholder for hplsql dialect
- ss

[hplsql] hplsql editor name HPL/SQL and placeholder

---

desktop/core/src/desktop/js/jquery/plugins/jquery.notify.js
desktop/core/src/desktop/static/desktop/js/jquery.notify.js

Similar to #2002 and #2006, some error will happen occasionally and will confuse the users. Note this error happens when Knox gateway run out of replay buffer. And this happens one of ten same call like get_logs or check_status.

[ui] Avoid displaying service connectivity error in a popup

---

apps/beeswax/src/beeswax/server/hive_server2_lib.py

- replacing connector_name beeswax to hive
- Manually

[hplsql] replace connector_name beeswax to hive

---

desktop/libs/metadata/src/metadata/catalog/atlas_client.py
desktop/libs/metadata/src/metadata/conf.py

Added basic search functionality for Atlas using a configuration and also set the default value for search_cluster to cm.
Internal Jira: CDPD-19430
Tested this manually on a CDP cluster where I can see both DSL and Basic search worked when config is enabled as they both have similar constructs.

Atlas add basic search option and set search cluster to 'cm' as default

---

desktop/core/src/desktop/middleware.py
desktop/core/src/desktop/settings.py

Hue [py3] Enable HTTP_X_FORWARDED header detection

---

desktop/core/src/desktop/lib/raz/raz_client.py
desktop/core/src/desktop/lib/raz/raz_client_test.py

(cherry picked from commit 61f095c03c46e72f4c3e8feedae3f24f662abb66)

Hue [py3] Fixing b64encode string issue

---

desktop/core/ext-py3/pysaml2-5.0.0/src/saml2/config.py
desktop/core/ext-py3/pysaml2-5.0.0/src/saml2/sigver.py

- Enable SAML certificate creation with passphrase support
- Tested on DWX server. Checked SAML login works.

Hue [py3] Enable SAML certificate creation with passphrase support.

---

desktop/core/requirements.txt

- ipython 7.16.3 to 8.1.1
- ipdb[0.13.9] requires ipython>=7.17.0
- running ./build/env/bin/hue shell

[core] upgrading ipython to latest version

---

desktop/core/requirements.txt

- upgrading celery 5.1.2 to 5.2.2

[core] upgrading celery to the latest version as older version has CVEs

---

apps/beeswax/src/beeswax/server/dbms.py
apps/beeswax/src/beeswax/server/dbms_tests.py
apps/beeswax/src/beeswax/server/hive_server2_lib.py
apps/metastore/src/metastore/tests.py
desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

Current behavior of Hue Hive with ZK, is to get the HiveServer2 information on the first try and then if there is a failover, it does not use the failed over HS2.  
Performed a complete manual test by stopping and starting Hive server multiple times and one at a time to ensure that the Hue code can replace the Old active HS2 with the new Active HS2.  
Jira: CDPD-10924

[con.hive] fix for hive failover via zk

---

tools/docker/hue/Dockerfile

- 'krb5-config', 'krb5-user' packages were missed when the py2 and py3 Dockerfiles were swapped

[docker] Add few kerberos packages in py3 Dockerfile

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py
desktop/libs/notebook/src/notebook/connectors/spark_shell_tests.py

- Reuse Livy session per user similarly to SQLAlchemy
- Add support for /autocomplete, /get_sample_data and other APIs
NOTE: In the start, 2 sessions are being created, one for /autocomplete and other for /create_session. This is because /autocomplete call is always first in the call stack from the UI, plus this will help if user just want to access other tabs like Table Browser where we don't do /create_session call. But since we are reusing the session per user, eventually we only use one of the sessions afterwards for every user activity regarding SparkSQL.

[sparksql] Enhance SparkSQL support via Apache Livy for Hue

---

tools/container/hue/Dockerfile
tools/container/huelb/Dockerfile

- Setting non-root login for Hue and Hue LB image.
- docker image inspect --format '{{json .Config.User}}' HUE_IMAGE_NAME
- docker image inspect --format '{{json .Config.User}}' HUELB_IMAGE_NAME
- Checked user id at hue terminal login in kubernetes env.

Set non-root default user for Hue images

---

desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls.py

- `/api/storage/mkdir` is the public API for create directory operation for Hue filebrowser.

[api] Port create directory filebrowser API to public

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py
desktop/libs/notebook/src/notebook/connectors/spark_shell_tests.py

- Close unused Livy sessions to free up resources
Other improvements include:
- Check for stale value when caching session value for particular user.
- Create session in /sampla_data also  if required to fix table browser corner case when switching to editor.
- Update UTs

[sparksql] Close unused Livy sessions to free up resources

---

desktop/core/src/desktop/js/hue.js
desktop/core/src/desktop/js/ko/components/assist/events.js
desktop/core/src/desktop/js/sidePanelViewModel.js
desktop/core/src/desktop/js/sidePanelViewModel.test.js
desktop/core/src/desktop/templates/common_notebook_ko_components.mako

- Added the shortcut key to toggle the visibility of the side panels (win: ctrl + . & mac: cmd + . )
- Updated shortcut docs
- Added new unit tests
- Tested using unit tests
- Manual testing in the following browsers:
Note! Not tested on windows. Waiting for WMware licence.
1. Open the editor
2. Press cmd + . (if your are one a mac) 
3. Verify that both assist panels are hidden
4. Press cmd + . (if your are one a mac) 
5. Verify that both assist panels are showing again and that they still are showing content
6. Hide one of the assist panels by using the mouse and clicking the panels chevron icon
7. Press cmd + . (if your are one a mac) 
8. Verify that both assist panels are hidden
9. etc...
after hitting cmd + .
Please review [Hue Contributing …

[frontend] Add shortcut key for toggling side panels

---

apps/beeswax/src/beeswax/server/hive_server2_lib.py

The problem AttributeError: 'Nonetype' object has not attribute 'update' was throwed when I execute query with HS2, Maybe we should ensure the attribute "properties" is not "none", thus I add the empty dict to replace 'Nonetype' if the properties is none.

fix nonetype error

---

desktop/libs/azure/src/azure/conf.py

Jira: CDPD-39592
Fix the typo:
From:  default_fs.startwith('abfs://') 
To:  default_fs.startswith('abfs://')

Addressing typo for default_fs.startwith('abfs://')

---

desktop/core/src/desktop/js/apps/notebook/snippet.js

- If there is no yarn config in Hue backend, we should not show the `application_id` on the UI for some Hive queries which use Tez.
- Manually
Before:
After:

[ui] Check for yarn config when adding application job ids

---

apps/metastore/src/metastore/templates/metastore.mako
desktop/core/src/desktop/js/catalog/DataCatalogEntry.ts
desktop/core/src/desktop/js/catalog/dataCatalogEntry.test.ts

The file location popover in the table browser failed to load while the same path could be opened in the file browser.  As @Akhilsnaik suggested in a related internal jira the issue is probably that the popover recursively checks for parent directory listing permissions while the file browser doesn't. After discussion with @JohanAhlen we decided to replace the location popover with a link to the file browser instead of changing the underlying loadDeep strategy due the to risk of introducing regressions.  
- Removed location popover for tables and databases in the Table browser
- Tables in the Table browser will now show a link to the file browser if there is a hdfs_link available and if there is no hdfs_link the text 'unknown location' will be shown
- Databases in the Table browser only …

[frontend] replace location popover with link to filebrowser

---

desktop/core/src/desktop/js/apps/notebook/snippet.js

- Previous logic failed for other job names if config is not present, now we only skip yarn jobs which start with 'application' if the config is not present. This will allow Impala job browser links to be shown in the log div.
- Tested manually with both Hive and Impala by running select and insert queries and meanwhile toggling on/off the yarn config for different scenarios.

[ui] Improve yarn config check for skipping job names in log div

---

apps/metastore/src/metastore/templates/metastore.mako

- Added "iceberg" icon after table detail in the table browser if the table is of type iceberg.
- Tested partially using unit tests
- Manual testing in the following browsers:
1. Open the Impala editor
2. Add a new iceberg table using "CREATE TABLE TempIceberg (i INT, t TIMESTAMP, j BIGINT) STORED AS ICEBERG;"
3. Go to the table browser and open the table
4. Verify that it has "iceberg" icon as shown in the screenshot 
5. Open another table and verify that the icon is not present there

[frontend] add iceberg indicator to table browser

---

desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py

For Phoenix driver use the old method if has_impersonation is set to true
Tested my change on a cluster with HUE + Phoenix.
Added a unit test as well.

Change impersonation to use principal_username broke phoenixdb

---

apps/jobbrowser/src/jobbrowser/templates/job_browser.mako

The spark application trackingUrl was pointing to the original url even
when Knox was enabled.
This change rewrites the trackingUrl with the knox url to the corresponding
YARN application url when Knox is enabled.
- Tested it by running the a spark job on Knox enabled cluster and
verifying the generated knox url
- Tested it by running the a spark job on non-Knox enabled cluster
and verified that the original url is displayed.

[ui] Spark application history links not working when Knox is enabled

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py
desktop/libs/notebook/src/notebook/connectors/spark_shell_tests.py

- Global variable are not a good option to act as a caching option specially with gunicorn server. We can either use some caching service or store the session info in the Hue db to have atomicity in operations as a tradeoff with DB calls.
- Currently we are storing it in the user profile object and in future we can see for some cache service like Memcached or Redis.

[sparksql] Store Livy session details in the UserProfile

---

.circleci/config.yml
.eslintignore
.github/workflows/commitflow.yml
.gitignore
Makefile
desktop/core/src/desktop/js/parse/sql/sqlParserRepository.ts
tools/jison/generateParserModuleImports.js
tools/jison/generateParsers.js
tools/jison/package-lock.json
tools/jison/package.json

The main thought here is that new parser files can be "plugged in" by simply adding it to the proper folder in Hue.
- Adding fixes to `generateParsers.js` to prevent it from crashing when generating new parsers
- A new file called `parserModules.ts` which contains the import statements for all available parsers is now
generated when running `make apps`. 
- The generation of the import statements has been removed from `generateParsers.js` and is now handled by the `generateParserModuleImports.js`. 
- A key difference is that the import statements are generated based on the actual available parser files rather than the available Jison parser definition files. This means that a new parser can be created and maintained in a separate project and by adding its generated parser files to the …

[autocomplete] make sql autocomplete and syntax parsers pluggable

---

desktop/core/src/desktop/settings.py

When Hue use Django to connect to Oracle database with RAC mode, a full DSN string is expected. And removing port from Django database setting makes it connect via the DSN string.
Example of a full DSN string:
```
(DESCRIPTION=(LOAD_BALANCE=off)(FAILOVER=on)(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS=(PROTOCOL=TCP)(HOST=<hostname>)(PORT=<port>))(CONNECT_DATA=(SERVICE_NAME=<service name>)))
```
- Tested on a cluster with Oracle RAC setup.

[core] Remove port from database setting for Oracle RAC

---

desktop/core/requirements.txt
desktop/core/src/desktop/auth/api_authentications.py
desktop/core/src/desktop/auth/api_authentications_tests.py

- Dependabot alerted CVE for PyJWT package: https://github.com/cloudera/hue/pull/2865
- For this, we had to change the verify JWT token flag code when decoding the token and update UTs.
- Successfully running unit tests.

[jwt] Bump PyJWT package to 2.4.0 to fix high severity CVE

---

desktop/core/requirements.txt

- Required for error: `AttributeError: 'str' object has no attribute 'decode'`
- This error comes when trying to use Hue public API via Hue's JWT access token.
- Version 4.7+ contains the fix so we upgraded to the latest. This was required because we upgraded PyJWT to 2.4.0 due to CVE.
- Manually tested the Hue public API flow.

[jwt] Bump djangorestframework-simplejwt to 5.2.0

---

Makefile.sdk

-  Skipping the fuzzy translation as after babel==2.5.2, pybabel compile exiting the code if errors were encountered.
- And we can't resolve the fuzzy translation manually we need some clients as previously we were having for localization.
- Checked with `make locales`

[localization] skipping the fuzzy translation

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py

- Currently, all Livy sessions except the cached session were getting closed when trying to go to some other dialect with Livy as interface.
- With this fix, we will only close unused session per user for particular dialect. 
- For example, if user A is on SparkSQL, then it should only close all unused session for user A for SparkSQL only.

[sparksql] Only close livy session of particular dialect per user

---

apps/filebrowser/src/filebrowser/templates/display.mako
apps/filebrowser/src/filebrowser/templates/fb_components.mako
apps/filebrowser/src/filebrowser/templates/listdir_components.mako
desktop/core/src/desktop/js/ext/fileuploader.custom.js
desktop/core/src/desktop/js/onePageViewModel.js

This PR is aimed at fixing frontend bugs related to the non ascii and non alphanumerical characters in file and folder names. 
Changes to the Filebrowser app:
- Current path correctly displayed when editing the path
- Destination folder path correctly displayed in upload modal when uploading files
- Single quotes supported in file name when viewing file
- Ampersand supported in file and folder names
- hash character in file name supported when viewing file
- plus character supported in file name
The following characters and strings where tested for the different operations related to the file browser
Manual testing done on MacOS for

[frontend] fix issues related to file path encoding in file browser

---

apps/jobbrowser/src/jobbrowser/apis/query_api.py
apps/jobbrowser/src/jobbrowser/tests.py

The query history shows the time of execution in local time instead of UTC when you click on Jobs in Hue UI or an Impala VW
performed manual tests. Changed the timezone and tested it. 

Impala Job browser - query history - query submitted time changed from UTC to local time

---

desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

Jira: CDPD-40785
Making the table external at the time of table creation instead of setting the table to external post creating the table.
Manual test case performed both on Impala and Hive editors.

Export all does not work as Hive managed table location cannot be changed

---

desktop/core/ext-py/phoenixdb-1.1.0/phoenixdb/sqlalchemy_phoenix.py
desktop/core/ext-py/phoenixdb-1.1.0/phoenixdb/tests/test_sqlalchemy.py

- get_view_names() returning view list -> https://github.com/apache/phoenix-queryserver/pull/91
- Manually and added tests like added in above PR

[phoenix] get_view_names() returning empty list

---

desktop/core/src/desktop/management/commands/rungunicornserver.py

Testing Done
- Tested with upload file size 2GB, 2.5GB, with this change it worked.

Increase Gunicorn Worker Timeout Value for Upload Large File.

---

tools/ci/check_for_python_lint.sh

- Disabling lint check for /ext-py3 folder

Disabling lint check for /ext-py3 folder

---

desktop/core/ext-py/pysaml2-4.9.0/src/saml2/xmldsig/__init__.py
desktop/core/ext-py3/pysaml2-5.0.0/src/saml2/xmldsig/__init__.py

- Update default SAML signing algorithm from SHA1 to SHA256
- Tested on Secure SAML enabled setup

Update dfault SAML signing algorithm from SHA1 to SHA256

---

desktop/libs/notebook/src/notebook/conf.py
desktop/libs/notebook/src/notebook/connectors/spark_shell.py

- Changing the snippet type from `sql` to `sparksql` for SparkSQL support.
- Type as `sql` looks too generic and can cause maintainability issues for other dialects.
- Users need to add the following config now for `[notebook]`:
```
[notebook]
[[interpreters]]
[[[sparksql]]]
name=Spark SQL
interface=livy
```
- Manually testing all Sparksql editor operations.

[sparksql] Change snippet type from 'sql to 'sparksql'

---

desktop/libs/indexer/src/indexer/templates/importer.mako

- limiting the file size to 1MB
- Simultaneously importing data in 5 tabs in different browsers

[local importer] limiting the file size to 1MB

---

apps/metastore/src/metastore/templates/metastore.mako
desktop/core/src/desktop/js/apps/tableBrowser/metastoreTable.js
desktop/core/src/desktop/js/apps/tableBrowser/metastoreTable.test.js
desktop/core/src/desktop/js/catalog/DataCatalogEntry.ts
desktop/core/src/desktop/js/catalog/dataCatalogEntry.test.ts

Move logic from mako template and create unit tests
- add additional condition for showing the import button
- refactor out logic from mako template into `metastoreTable.js`
- add isTransactionalTable() function to `dataCatalogEntry.ts`
- create relevant unit tests
- Unit tests for new and existing conditions
- Manual testing in chrome for additional condition:
1. Create transactional hive table
```
CREATE TABLE trans(id tinyint, name string)
TBLPROPERTIES ("transactional"="true");
```
2. Go to table browser and view the trans table and make sure there is no import button shown
3. Create non transactional hive table
```
CREATE TABLE nontrans(id tinyint, name string)
TBLPROPERTIES ("transactional"="false");
```
4. Go to table browser and view the nontrans table and make sure there is no …

[frontend] Hide import button for transactional hive tables

---

desktop/core/src/desktop/lib/fs/proxyfs.py

Jira: CDPD-41667
Added  self._get_fs(None) so a path is not requested when clearing trash with Empty Trash feature.
Manually by uploading files and deleting them and then going to .Trash folder and using the option Empty Trash

Empty feature fails to clear .trash

---

desktop/core/src/desktop/js/apps/tableBrowser/metastoreTable.js
desktop/core/src/desktop/js/apps/tableBrowser/metastoreTable.test.js
desktop/libs/notebook/src/notebook/api_tests.py
desktop/libs/notebook/src/notebook/conf.py

- Do not use name since it can be flaky and customizable, intead type field looks more reliable.
- Changed dialect for SparkSQL.

[interpreters] Dialect field should not have spaces

---

desktop/libs/indexer/src/indexer/indexers/sql.py

- When trying to run the latest docker image we are getting the following error:
```
File "/usr/share/hue/desktop/core/src/desktop/urls.py", line 50, in <module>
for pattern in self.url_patterns:
File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
from desktop import api_public_urls
File "/usr/share/hue/desktop/core/src/desktop/api_public_urls.py", line 20, in <module>
from desktop import api_public
res = instance.__dict__[self.name] = self.func(instance)
File "/usr/share/hue/desktop/core/src/desktop/api_public.py", line 25, in <module>
File "/usr/share/hue/build/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
from indexer import api3 as indexer_api3
File …
```

[indexer] Check whether impala conf is present or not

---

desktop/core/src/desktop/manage_entry.py

After swich Python3.8, there is error reading config file with duplicate section. And also there bytes to string conversion issue.
```
[root@yn-2 hue]# build/env/bin/hue shell --cm-managed
File "build/env/bin/hue", line 36, in <module>
sys.exit(load_entry_point('desktop', 'console_scripts', 'hue')())
File "/opt/cloudera/parcels/CDH-7.1.8-1.cdh7.1.8.p0.30052893/lib/hue/desktop/core/src/desktop/manage_entry.py", line 114, in entry
config.read(cm_config_file)
File "/usr/local/lib/python3.8/configparser.py", line 697, in read
self._read(fp, filename)
File "/usr/local/lib/python3.8/configparser.py", line 1067, in _read
raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from '/etc/cloudera-scm-agent/config.ini' …
```

[py3] Fix error when start Hue shell on command line

---

apps/impala/src/impala/server.py

Reset max_number_of_sessions, has_close_sessions & has_session_pool in ImpalaServerClient
Manually tested in a real cluster

Impala table import is failing when beeswax max_number_of_sessions != 0

---

apps/beeswax/src/beeswax/management/commands/beeswax_install_examples.py
apps/beeswax/src/beeswax/management/commands/beeswax_install_examples_tests.py

Install example tables as superuser, but the time query history is showing 53 yrs old due to missing timestamp.
Run install Hive and Impala examples locally 

[core] Fix query history timestamp of installing example tables

---

desktop/core/src/desktop/js/ko/components/assist/ko.assistEditorContextPanel.js

This takes care of an issue where the right assist is causing autocomplete API calls for tables that don't exist.
Tested manually to reproduce and after the fix to verify.

[assist] Prevent automatic opening of unknown tables in the right assist

---

apps/filebrowser/src/filebrowser/templates/display.mako
apps/filebrowser/src/filebrowser/templates/listdir_components.mako

Added fixes needed to support percentage (%) in file and folder names. 
Tested manually for HDFS, S3 and ABFS
See updated sheet with supported characters
https://docs.google.com/spreadsheets/d/1SEghz9AJDEthIxScIcQ95nGU2Xh8oQ7U-FLwWiRZ8gs/edit?usp=sharing

[frontent] add support for % in file and folder names

---

apps/beeswax/data/tables/onlyheader.csv
desktop/libs/indexer/src/indexer/indexers/sql.py
desktop/libs/indexer/src/indexer/indexers/sql_tests.py

- Separating the insert sql from create sql
- Now we will be able to create the only header tables.
- Manually
- Unit test

[importer] Fixing only headers CSV file table creation in Local File importer on Impala

---

desktop/core/src/desktop/js/ko/bindings/ko.reactWrapper.js

Since Knockout can modify the DOM and remove elements that contain react _root_ components we need to make sure those components are explicitly unmounted so that any clean up code they use is actually being executed.
Manual testing using a test react component. In the mako file:
```
<Test data-bind="reactWrapper: 'Test', props: {}"></Test>
```
and in the functional Test component we use a side effect that has a clean up call:
```
useEffect(() => {
return () => {
console.log('Cleaning up');
};
}, []);
```

[frontend] - unmount react root on DOM node disposal

---

desktop/core/requirements.txt
tools/docker/hue/Dockerfile

- When the docker image is building, it is picking up the latest protobuf pypi package for python3 because of some other dependency package.
- We are setting PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python as a workaround for image not able to run.

[docker] Revert protobuf change and set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python in Py3 image

---

desktop/core/src/desktop/settings.py

-  Increasing the value of DATA_UPLOAD_MAX_MEMORY_SIZE to 5MB.
- Manually.

[importer] increasing the value of DATA_UPLOAD_MAX_MEMORY_SIZE to 5MB  as sometime request size > 2.5MB (default value)

---

apps/oozie/src/oozie/templates/dashboard/rerun_coord_popup.mako
apps/oozie/src/oozie/templates/dashboard/rerun_workflow_popup.mako

When Knox is enabled, window.HUE_BASE_URL is not append at front because app_path is HDFS URL already contains HUE_BASE_URL. This fix is adding window.HUE_BASE_URL at the front of rerun URL. When Knox is not enabled, window.HUE_BASE_URL is an empty string.
tested on Knox enabled cluster and non-Knox cluster

[oozie] Fix rerun workflow URL when Knox is enabled

---

desktop/core/src/desktop/settings.py

The middleware is needed only on py3 and is interfering when authenticating with knox. We are stripping out the gateway host's header information and that is why it is failing the match with proxy_hosts config.

[knox] Disabled the MultipleProxyMiddleware for py2

---

desktop/core/requirements.txt

- Celery is also bumped to 5.2.3 because django-celery-result has a dependency on it.

[CVE][Py3] Bump django-celery-result to 2.4.0 to fix high severity CVE

---

desktop/core/src/desktop/js/ko/components/doc/__snapshots__/ko.shareDocModal.test.js.snap
desktop/core/src/desktop/js/ko/components/doc/ko.shareDocModal.js

Removed the fixed height of the modal body and a div in the body that caused the overflow to happen already for a small selection. The modal will now grow with its content like normal bootstrap modals. The panels for selected users and groups will grow with each selected item until they reach 20% of the viewport and then get individual scrollbars.
Manual testing in chrome by adding multiple users/groups (actually by manually modifying the DOM in the browser since my cluster only had 3 users and 1 group).
Few selections scenario:
Scenario with many users selected with read access:
Extreme scenario, many groups and users selected for different access:

[frontend] fix modal overflow for sharing saved sql queries

---

desktop/core/requirements.txt

(cherry picked from commit 51c4882b230b7b5b6273eee7faa13fe7e5865936)
- To fix CVE-2022-1941
- manual

Upgrading protobuf python module to 3.20.3 version

---

desktop/core/src/desktop/js/parse/sql/generic/sqlParseSupport.js

Add DELETE to suggestKeywords of generic parser to resolve #2983
No tests, as the change was simply to add DELETE to a keywords array.

Add DELETE to suggestKeywords of generic parser (fixes  #2983)

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/urls.py
desktop/core/src/desktop/api_public.py

- Improve the current /get_filesystem API to add user home directory for each filesystem.
- Remove response status code for cleaner API.
```json
[{"file_system": "hdfs", "user_home_directory": "/user/demo"}, {"file_system": "s3a", "user_home_directory": "s3a://<some_s3_path>"}, {"file_system": "abfs", "user_home_directory": "abfs://<some_abfs_path>"}]
```
- Manually tested in local Hue setup.

[api] Add user home directory in /get_filesystems API

---

desktop/core/src/desktop/lib/raz/raz_client.py
desktop/core/src/desktop/lib/raz/raz_client_test.py
desktop/core/src/desktop/lib/rest/raz_http_client.py
desktop/core/src/desktop/lib/rest/raz_http_client_test.py

- We are fully unquoting the relative_path now when preparing the request parameter for RAZ API call to get back SAS token. This is required for cases when there are whitespaces or non-ascii characters in the path.
<br>
- Also previously, we were partioning the signed url with the original path to get only the `/container/path?action=something%&sas_token` type of signed path. But this approach was breaking during partitioning when signed url was quoted but the original path was not.
- Because of this, operations related to non-ascii characters or containing whitespaces were failing.
- Now we only partition the signed url with `.dfs.core.windows.net` for signed path consistency.

[raz_abfs] Unquote relative_path and partition signed path with `.dfs.core.windows.net`

---

desktop/libs/azure/src/azure/abfs/__init__.py

- RAZ check is done when handling user directories, so this method is much cleaner now.
- Manually tested in local Hue setup. Needs to be tested E2E in Raz cluster setup.

[filebrowser] Check for abfs:// in remote_storage_home and remove RAZ check

---

.eslintrc.js
apps/hbase/example/documents/gethue.com.html
desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/js/apps/editor/components/resultGrid/ko.resultDownloadModal.js
desktop/core/src/desktop/js/config/types.ts
desktop/core/src/desktop/js/hue.js
desktop/core/src/desktop/js/jest/jest.init.js
desktop/core/src/desktop/js/reactComponents/ReactExampleGlobal/ReactExampleGlobal.tsx
desktop/core/src/desktop/js/types/types.ts
desktop/core/src/desktop/js/utils/hueAnalytics.test.ts
desktop/core/src/desktop/js/utils/hueAnalytics.ts
desktop/core/src/desktop/models.py
desktop/core/src/desktop/templates/common_footer_m.mako
desktop/core/src/desktop/templates/common_header_footer_components.mako
desktop/core/src/desktop/templates/common_notebook_ko_components.mako
desktop/core/src/desktop/templates/hue.mako
desktop/core/src/desktop/views.py

We can now have GA log events that we explicitly send from the Frontend. 
- Removed old GA universal code and added new for GA4
- Added global listener for clicks on elements with attribute data-hue-analytics and data-hue-analytics-prio
- Extended utils/hueAnalytics.ts to work with the new setup
- Updated secure_content_security_policy  unsafe-eval and connect-src to work with new GA address
- Updated backend log style
- Added window.hueDebugAnalytics to view GA params in the console
- Added hueAnalytics to react test component
- Added unit tests and global mock for hueAnalytics
- manually testing
- unit testing

[frontend] capture advanced events with ga and backend

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py

- Fixes download issue for SparkSQL editor:
- https://github.com/cloudera/hue/issues/2972

[sparksql] Remove start_over param for fetch_result API method

---

apps/filebrowser/src/filebrowser/views.py
apps/filebrowser/src/filebrowser/views_test.py

Currently decoding happens at least twice in views.py when requesting to view a folder, this causes an issue when files are stored with actual encoded values in the name.
An example is if a folder exists in hdfs with the name 'some%20folder', the UI would encode it and request 'some%2520folder' (% becomes %25), which if decoded once would be correct, 'some%20folder', but if it's done twice the resulting name would be 'some folder' with a space instead of %20 which is incorrect.
We can safely assume that each path contains a '/' char, so we can use that to check if a path has already been decoded. An encoded path would never contain a '/' as it would be %2F.
Tested both through the UI and with unit tests.

[fb] Prevent decoding of already decoded path in the File Browser

---

desktop/core/src/desktop/js/ko/components/assist/ko.assistDocumentsPanel.js

- Download button added in the left assist for the the documents
- Manually

[left assist] adding download option in left for the documents

---

desktop/core/src/desktop/js/utils/hueAnalytics.test.ts
desktop/core/src/desktop/js/utils/hueAnalytics.ts
desktop/core/src/desktop/views.py

Added checks in the frontend and backend to prevent incorrect UI analytics logging parameters.
- Manual testing calling `window.hueAnalytics.convert` and `window.hueAnalytics.log` functions from console
- Additional unit tests

[ui_analytics] prevent incorrect log calls to the backend and GA

---

desktop/core/src/desktop/js/vue/wrapper/index.ts

In our application `vue3-webcomponent-wrapper` triggers an error in `vue-i18n` when a web component is removed from the DOM. The problem seems to be, that `vue-i18n`'s unmounted method is unable to retrieve the current vue instance and thereby [fails with a syntax error](https://github.com/intlify/vue-i18n-next/blob/0da16ade4289d0b9b5e8eddaf9d1be53e4d0d0e9/packages/vue-i18n-core/src/mixins/next.ts#L129-L134). vue-i18n uses the `getCurrentInstance` method in their unmounted hook. The method seems to be [undocumented](https://stackoverflow.com/a/72209340/7451049) but works. The fact that vue3-webcomponent-wrapper [calls the `unmounted` methods manually](https://github.com/naltatis/hue/blob/89c23c4151d9b4ce451991b06e81b005b84edce1/desktop/core/src/desktop/js/vue/wrapper/utils.ts#L26-L32) …

Webcomponent wrapper unmounted

---

desktop/core/src/desktop/js/ko/bindings/ko.hueLink.js

This takes care of an issue where right-click and choosing "Open in a new tab" doesn't take the base url into account.
cmd/ctrl-click works as that is handled by the click event handler on the element (init function of the binding)

[frontend] Prepend the base url to the href in the hueLink binding

---

desktop/core/ext-py/thrift-0.16.0/src/transport/TSocket.py
desktop/core/ext-py/thrift-0.16.0/test/test_socket.py
desktop/core/ext-py/thrift-0.16.0/test/test_sslsocket.py

non-zero flags not allowed in calls to recv
(cherry picked from commit 9b1bc2802208f3fc401ded40ffb676f20083fc5a)

Hue - After upgrading thrift-0.16.0 version, Hue gets following error,

---

desktop/core/src/desktop/lib/rest/raz_http_client.py
desktop/core/src/desktop/lib/rest/raz_http_client_test.py

- Sometimes correct ABFS calls with correct params and having a SAS token from RAZ failed with a 403 signature mismatch error intermittently.
- This gives a bad user experience for someone browsing the ABFS file browser.
- We are now retrying such operation for one more time as a workaround time so that they execute successfully (since this issue is intermittent). 
- However, the real reason of call failure might be because of some problem with the generated SAS token from RAZ.
- Tested E2E manually in a live cluster.

[raz] Retry some failed ABFS calls once again

---

desktop/core/src/desktop/js/vue/wrapper/index.ts
desktop/core/src/desktop/js/vue/wrapper/utils.ts

In https://github.com/cloudera/hue/pull/3102 I provided a fix for the broken unmount behaviour and mentioned that we might also have an issue in the mount case. Now we ran into exactly this issue. This PR includes the fix for the case where you create a custom element, attach it to the DOM, remove and then re-add it. In our application we have situations where the host app (also Vue) decides to briefly remove a web component from the DOM and reattaches it a few moments later.
I've isolated the issue in this [Stackblitz](https://stackblitz.com/edit/vitejs-vite-syzsx9?file=src%2Fmain.js). The problem seems to be, that it's not possible to unmount and then re-mount a Vue 3 Application. Once it's unmounted you have to recreate it.
- `connectedCallback` now always creates a Vue instance and …

Webcomponent Wrapper (re-)mount fix

---

apps/filebrowser/src/filebrowser/views.py

In the files-download, we were always setting the 'Last-Modified' header for the downloaded files. Since, we were not providing the expiration, the browser was not being forced to verify for a new versions and are free to use their own heuristics. See the Caching RFC for more details https://www.rfc-editor.org/rfc/rfc7234#section-4.2.2
This commit adds the 'must-revalidate' to force the browsers to verify the files everytime.

[backend/file-browser] Force cache validation for file download

---

desktop/core/src/desktop/lib/raz/raz_client.py

- Creating a directory with non-ascii characters was throwing a signature mismatch error.
- On further investigation, found out that there was a signature mismatch for the GET requests which go through the boto2 client implementation in Hue, and the signed headers from RAZ are not matching what S3 was generating to verify them.
- This is only happening for GET requests, so most probably all GET method operations must be failing with this error.
- Next steps were to see why is this signature mismatch happening for the path, is it the path which we sent to RAZ for signed header generation or to S3 side request for actual S3 operation where S3 verifies the header?
- After narrowing down the issue, found out that we need to fully unquote the path before sending to RAZ so that signed headers …

[raz] Fix non-ascii directory creation in S3

---

desktop/core/src/desktop/js/onePageViewModel.js

- Modify the single point file download function to include knox prefix in the url
- Manually locally to make sure it works when knox is not present
- On a datahub test cluster with knox present by directly modifying the js file in the browser to use the same fix

[frontend] Add knox prefix to download url

---

tools/kubernetes/helm/hue/values.yaml

- Fix aws region attribute in values.yaml
- Manual
There seems to be a typo in helm chart values.yaml.
configmap-hue yaml has a .Values.aws.**region**
please review.

Fix aws region attribute in values.yaml

---

desktop/core/src/desktop/lib/raz/raz_client.py

- Checking python version first and then the type of prefix if its unicode or not.
- This is required because python3 doesn't recognize unicode keyword, it is only done via python2.
- So checking the python version first will short-circuit the if condition because it will be False beforehand for py3 and type check of prefix for unicode will not happen.

[raz] Check py version before unicode type check for non-ascii dir creation

---

apps/filebrowser/src/filebrowser/templates/listdir_components.mako
apps/filebrowser/src/filebrowser/views.py

Problem description:
The "next" param that is sent along with many file and folder operations from the directory listing is not encoded and the following redirect fails when the file path contains characters that requires encoding. The redirect failure is silent since
1. it is an AJAX request and not actually returning an HTTP error
2. the request is being correctly executed with a second call from the frontend (Don't ask me why it works this way)
BUT, in older Hue versions (e.g. 7.1.7) the API actually returns a 400 error and there is no follow up request. So in order not to diverge further we should add this fix to master as well.
CHANGES:
- Frontend: Encodes the file path section of the next param when sent to the API 
- Backend: Encodes the file path section of the next param when …

[filebrowser] Incorrectly encoded next-param

---

docs/docs-site/content/administrator/configuration/apps/_index.md
docs/docs-site/content/developer/development/_index.md

- The link is failing the documentation checks by giving a 403 error. Changing the link to fix the check.
- Github Preview and Hugo Serve

[docs] Remove dead MySQL JDBC connector and Font Awesome 3 links

---

desktop/core/src/desktop/js/components/styles/hue5-globals.scss
desktop/core/src/desktop/js/components/styles/variables.scss
desktop/core/src/desktop/js/reactComponents/PushDrawer/Drawer/Drawer.scss
desktop/core/src/desktop/js/reactComponents/PushDrawer/Drawer/Drawer.tsx
desktop/core/src/desktop/js/reactComponents/PushDrawer/DrawerHeader/DrawerHeader.scss
desktop/core/src/desktop/js/reactComponents/PushDrawer/DrawerHeader/DrawerHeader.tsx
desktop/core/src/desktop/js/reactComponents/PushDrawer/PushDrawer.scss
desktop/core/src/desktop/js/reactComponents/PushDrawer/PushDrawer.test.tsx
desktop/core/src/desktop/js/reactComponents/PushDrawer/PushDrawer.tsx
package-lock.json
package.json

Stateless* drawer that pushes main content to the side when open. Uses render props for drawer header, drawer content and main content. Supports smooth animations for drawers on the left and right side that can be used simultaneously.
The new Hue graph panel will use a push drawer (see [UI design](http://example.com/)). Neither cuix or Antd offers such a component so I have built one based on our needs. We can continue to build on this component when we revamp the editor and need to replace the old side panels.
*) It does use an internal state to trigger change when CSS transition finish 
```
import PushDrawer, { DrawerHeader} from './PushDrawer/PushDrawer';
const [isOpen, setIsOpen] = useState(true);
<PushDrawer
leftDrawer={
{
content: () => <div> I'm the left drawer content </div> …
```

[frontend] add reusable component PushDrawer

---

desktop/core/src/desktop/lib/rest/raz_http_client.py
desktop/core/src/desktop/lib/rest/raz_http_client_test.py
desktop/libs/azure/src/azure/abfs/abfs.py

- Fixing creation of directories and other directory operation having % in name/path for ABFS. For this, we have to double-encode such path. This is required because we do the calls to ABFS in single encoding and the underlying HTTPClient takes care of unquoting it once already. 
- For the RAZ side, we make sure that we unquote such paths once before making the RAZ request to get the SAS token.
<br>
- We are also making sure that we send correct path in-case of actual whitespaces vs actual `%20` present in directory paths. 
- This means that we only **double encode** actual %20 paths and not the paths which contain a whitespace (because encoding a whitespace gives `%20`).
<br>
- Fix rename in Py2 setup for non-ascii and % in path scenarios for ABFS.
- In case of Py2 setup, we are UTF-8 …

[raz] Fix rename and cases of % in path for RAZ ABFS

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/management/commands/rungunicornserver.py

The request header limits were hard-coded to None, resulting in gunicorn picking its own defaults. This commit extracts the three header related gunicorn params to conf while keeping the defaults. With this change, it is now possible to override the defaults.
Steps to reproduce:
1. Navigate to hue directly (without any load-balancer).
2. Keep the developer console of the browser open.
3. Select one of the GET server requests, such as `/api/editor/autocomplete/default/` and "Copy -> Copy as cURL".
4. Run the curl command from the console and it should go fine.
5. Now, edit the curl command to add a new test cookie with a 10k+ size value.
6. This request will fail.
Steps to verify:
1. Update the hue.ini to add the following 
> [desktop]
>   limit_request_field_size=0
> …

[backend/gunicorn] add configs for request header limits

---

apps/beeswax/src/beeswax/conf.py
apps/beeswax/src/beeswax/server/dbms.py
desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl

If incase ZK is slow to respond back, the default timeout is 15 seconds may not be ideal for busy cluster where the zookeeper connection can be established after 30 seconds or so. Hence set the default timeout to 30 seconds for the ZK connection.
Jira: CDPD-50059
Ref: https://kazoo.readthedocs.io/en/latest/_modules/kazoo/client.html#KazooClient.start
Adding a timeout for zookeeper connection in zk.start() as per the kazoo client doc.

Adding connection timeout for zookeeper connection to get hive znode

---

desktop/core/src/desktop/management/commands/rungunicornserver.py

The Server name response header contains gunicorn version, mask it to apache due to security issues. 
Github issue raised: https://github.com/cloudera/hue/issues/3209
Patch was tested on CDH cluster. Verified the Server response header 'Server: apache'.
Attaching screenshot

[backend] mask server response header due to security vulnerabilities

---

tools/container/hue/supervisor-files/hue_loglistener_template

- Add supervisor.conf file for the recently introduced hue log listener command
- manually, after docker creation

Hue [core] Adding supervisor conf for Hue log listener command.

---

desktop/conf/gunicorn_log.conf
desktop/conf/log.conf
desktop/core/src/desktop/loglistener.py
desktop/core/src/desktop/management/commands/rungunicornserver.py
desktop/core/src/desktop/management/commands/testloglistener.py

goes missing. After using Gunicorn base WSGI server, noticed the issue.
The Gunicorn server starts multiple worker processes to handle requests. Python logging module does not support logging to a single file from multiple processes is not supported. In Python, there is no standard way to serialize access to a single file across multiple processes in Python. If you need to log to a single file from multiple processes, one way of doing this is to have all the processes log to a SocketHandler, and have a separate process that implements a socket server that reads from the socket and logs to the file.
This change implements the fix. It uses a Unix domain socket file and logging SocketHandler.
Issues Fixed:
logfile gets rotated properly. Log messages are not overwritten. UDS is local to the …

Hue [core] Hue log file randomly gets rotated and Hue log lines

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/models.py

Improvement to https://github.com/cloudera/hue/pull/3221. Pulling the config from hue.ini rather than parsing the hue.ini file and reading configs from it. 
The Hue UI must display the virtual warehouse name(present in the case of CDW), and hue_image_version (from CDW/CDH) in the bottom left side of the sidebar. Making changes to get_config API to populate the following parameters ('vw_name', 'img_version' and 'hue_version' )
Manually Tested on a CDW and CDH hue editor. 

[backend] Pull hue_image_version from hue config

---

desktop/core/src/desktop/js/ko/components/assist/assistStorageEntry.js
desktop/core/src/desktop/js/ko/components/assist/assistStorageEntry.test.js
desktop/core/src/desktop/js/ko/components/assist/ko.assistStoragePanel.js
desktop/core/src/desktop/js/onePageViewModel.js

- Fix encoding when linking from assistpanel to Filebrowser by using the pubsub `open.filebrowserlink` and make sure all page-library workarounds are contain to one place only.
- added unit tests 
- manual testing
- passing unit tests

[frontend] fix encoding when linking from assistpanel to Filebrowser

---

tools/container/hue/Dockerfile
tools/container/hue/hueconf/gunicorn_log.conf
tools/container/hue/hueconf/log.conf

Keeping docker image up to date with Hue logfile server-related changes.
- put required log.conf files in docker images.
- manually

Hue [core] Hue needs to run under UBI8 docker.

---

tools/container/hue/Dockerfile

fixing typo
- fixing typo
- manually

Hue [core] Hue needs to run under UBI8 docker. version 2

---

.circleci/config.yml
.github/workflows/cleanup-cache.yml
.github/workflows/commitflow-ui.yml
.github/workflows/commitflow.yml
desktop/core/src/desktop/js/reactComponents/createRootElements.js

- Create a separate github workflow with the following:
Check out code
Run commit title format check
Prepare NPM (node/npm versions, caching etc)
Run JS package.json version checker
Run JS license checker
Run NPM Absolute path detection
Run JS lints
Run Style lints
Run JS tests
- When a cache is created by a workflow run triggered on a pull request, the cache is created for the merge ref (refs/pull/.../merge). Because of this, the cache will have a limited scope and can only be restored by re-runs of the pull request. It cannot be restored by the base branch or other pull requests targeting that base branch which could lead to **cache thrashing** when there are multiple PRs open. Hence added the clean up cache workflow that would be triggered when the PR is closed.
- Tested locally using …

[frontend] Create a separate upstream GitHub CI workflow for UI

---

desktop/core/src/desktop/conf.py
desktop/core/src/desktop/js/apps/editor/components/resultChart/ko.resultChart.js
desktop/core/src/desktop/js/apps/editor/notebook.test.js
desktop/core/src/desktop/js/apps/editor/snippet.js
desktop/core/src/desktop/js/apps/editor/snippet.test.js
desktop/core/src/desktop/js/apps/jobBrowser/components/impalaQueries/query-details/QueryDetails.vue
desktop/core/src/desktop/js/apps/notebook/aceAutocompleteWrapper.js
desktop/core/src/desktop/js/apps/notebook/app.js
desktop/core/src/desktop/js/hue.js
desktop/core/src/desktop/js/onePageViewModel.js
desktop/core/src/desktop/templates/global_js_constants.mako
desktop/core/src/desktop/templates/hue.mako
desktop/libs/notebook/src/notebook/conf.py
desktop/libs/notebook/src/notebook/decorators.py
desktop/libs/notebook/src/notebook/tasks.py
desktop/libs/notebook/src/notebook/views.py
docs/docs-site/content/administrator/configuration/connectors/_index.md
docs/gethue/content/en/posts/2020-09-15-sql-querying-improvements-phoenix-flink-sparksql-erd.md
docs/gethue/content/en/posts/2020-10-20-querying-live-streams-of-data-with-flink-sql.md
docs/gethue/content/en/posts/2020-10-20-querying-live-streams-of-data-with-kafka-sql.md
docs/gethue/content/jp/posts/2020-09-15-sql-querying-improvements-phoenix-flink-sparksql-erd.md
docs/gethue/content/jp/posts/2020-10-20-querying-live-streams-of-data-with-flink-sql.md
docs/gethue/content/jp/posts/2020-10-20-querying-live-streams-of-data-with-kafka-sql.md

The scope of Hue 5 has grown beyond editor/notebook v2 and instead of introducing additional feature flags I've renamed the old one and moved it up in the desktop section of the config.
The ENABLE_HUE_5 flag can be used for any features that we intend to deliver in Hue 5 only.
Manually tested with flag on and off.

[frontend] Replace ENABLE_NOTEBOOK_2 with ENABLE_HUE_5

---

apps/filebrowser/src/filebrowser/templates/listdir.mako
apps/filebrowser/src/filebrowser/templates/listdir_components.mako
desktop/core/src/desktop/lib/fs/ozone/__init__.py
desktop/core/src/desktop/lib/fs/ozone/ofs.py
desktop/core/src/desktop/lib/fs/ozone/ofs_test.py
desktop/core/src/desktop/lib/fs/ozone/ofsstat.py
desktop/core/src/desktop/lib/fs/ozone/ofsstat_test.py
desktop/core/src/desktop/lib/fs/proxyfs.py
desktop/libs/indexer/src/indexer/indexers/sql.py

- Path now changes from ofs://vol1/buck1/... to ofs://serviceID/vol1/buck1/...
- We are actually mocking LISTSTATUS and GETFILESTATUS op calls for ofs:// now to only show serviceID as an element. This enables in correct breadcrumbs and ofs valid path structure.
- On the UI side, volume and bucket operations were shifted right to incorporate service_id as path and no operations should be allowed from UI on it.
- Manually E2E and via updated unit tests.

[ozone] Add service_id in ofs path and update UI

---

apps/filebrowser/src/filebrowser/templates/listdir.mako

- Disable the Action btn for ozone volumes and buckets for the safety reasons.
- locally

[ozone] Disable the 'Action' btn for ozone volumes and buckets

---

apps/filebrowser/src/filebrowser/templates/listdir_components.mako
apps/filebrowser/src/filebrowser/views.py
desktop/core/src/desktop/lib/fs/ozone/ofs.py
desktop/libs/hadoop/src/hadoop/fs/webhdfs.py

- Copy operation uses /append API for files with size greater than the chunk size. But Ozone HttpFS APIs does not support /append API yet, so we are skipping all file sizes greater than the chunk size.
- Since the copy operation can be recursive, we are skipping file recursively from directories and showing on the UI for users to know about it.
- Increasing the chunk size value in the Hue config can allow large files to be copied without skipping.
- Tested manually.

[ozone] Skip copying files with size greater than chunk size

---

Makefile
desktop/core/base_requirements.txt

- celery 5.2.3 requires setuptools<59.7.0,>=59.1.1 and these versions have CVE-2022-40897 hence we are upgrading celery to 5.2.7 (latest)
-  virtualenv 20.16.5 was restricting setuptools to 65.3.0 [PR](https://github.com/pypa/virtualenv/pull/2405/files ) hence need to upgrade to latest.

[celery] upgrading celery and virtualenv

---

desktop/core/src/desktop/lib/export_csvxls.py

- In py3, the last file chunk is b'' and the file_reader loop never breaks!
- This is causing a wild infinite for loop and making infinite request to the connected FS for the empty chunk string.
- With the fix, it will break correctly after receiving the first empty binary string of file chunk.
- Tested in local Hue setup

[download] Check for binary empty chunk string correctly

---

apps/proxy/src/proxy/proxy_test.py
desktop/core/src/desktop/lib/wsgiserver.py
desktop/core/src/desktop/supervisor.py

- Changed from isAlive() to is_alive()
- Related PR -> https://github.com/python/cpython/issues/81985
- The isAlive() method of [threading.Thread](https://docs.python.org/3/library/threading.html#threading.Thread) has been removed. It was deprecated since Python 3.8. Use [is_alive()](https://docs.python.org/3/library/threading.html#threading.Thread.is_alive) instead.
- In python3.8 and python2.7 importing thread and tried is_alive() operation. Working fine.
- is_alive() got added in python2.6 so no problem for python2.7 and python3.8 based Hue https://docs.python.org/2.7/library/threading.html#threading.Thread.is_alive.

[Python3.9] Thread.isAlive() has been removed in Python 3.9 in favour for is_alive()

---

apps/useradmin/src/useradmin/test_ldap.py
apps/useradmin/src/useradmin/test_ldap_deprecated.py
desktop/core/src/desktop/tests.py
desktop/core/src/desktop/views.py

- Hue started using gunicorn based WSGI server. After that the Hue UI stops showing Hue logs.
- This code change fixes logs and download logs link in the Hue UI.
- Fix Hue log not found after gunicorn log file change.
- Tested hue/logs and hue/desktop/download_logs endpoints 
- Tested on local server and checked the logs and download logs link.

Hue [backend] Fix Hue log not found

---

tools/container/hue/Dockerfile
tools/container/hue/hue.sh

- Docker environment variable DESKTOP_LOG_DIR setting
- manually 

Hue [backend] Force env variable DESKTOP_LOG_DIR in docker creation

---

apps/filebrowser/src/filebrowser/views.py

This is related to ABFS in general and is reproducible in the local setup. 
From the logs, we are getting the following error from ABFS:
```
{"error":{"code":"InvalidRange","message":"The range specified is invalid for the current size of the resource.\nRequestId:87e0fcb0-201f-0042-6b7b-6cfc87000000\nTime:2023-04-11T13:41:21.7375625Z"}} (error 416)
```
Searching more, this is the expected behaviour from ABFS: https://stackoverflow.com/questions/55689719/unable-to-download-blobs-from-azure-blob-storage
So, tried catching this particular exception and simply pass to see if zero size file download actually happens after that (indicated in one of the stackoverflow answers above) and it works.
- Tested manually in the local setup.

[download] Fix zero size file downloading for ABFS

---

apps/beeswax/gen-py/TCLIService/TCLIService.py
apps/beeswax/src/beeswax/server/hive_server2_lib.py
desktop/core/src/desktop/auth/views.py
desktop/core/src/desktop/management/commands/rungunicornserver.py
desktop/core/src/desktop/middleware.py
tools/container/huelb/hue_httpd_template

Added {x-forwarded-for} header to log client's IP address in hue load balancer and gunicorn logs. 
Added {x-forwarded-for} header to Thrift call made from hue to hive/impala.
Manual tests - Logs show up on cdw and 7.1.8 clusters.
HTTP-X-FORWARDED-FOR header is logged in Hive logs (which implies Hue has sent the XFF header to hive). 

Add x-forwarded-for header in hue's request to hive/impala

---

docs/docs-site/content/releases/release-notes-4.11.0.md

the docker image gethue/4.11.0  missing hue name, should be gethue/hue:4.11.0

[release] Fix incorrect docker image url in 4.11 release notes

---

desktop/core/src/desktop/js/apps/notebook/snippet.js

**Issue:** notebook multisession errror: Session matching query does not exist
**Fix:** Type is not added on execute hence throws session matching query does not exist, adding the current type fixes the issue.
Local Testing:
* Reproduce the issue without the code change.
* Performed the same steps back to verify the fix.

notebook multisession errror: Session matching query does not exist

---

Makefile

- Allowing Hue to install virtualenv and all the python libs for >=python 3.8 
- Tested with creating creating cluster with a canary. 
- On centos7, Hue with python3.8 is working fine.
- On Redhat8, Hue with python3.8 is working fine.
- On ubuntu20, Hue with python3.8 is working fine.
- On sles12, Hue with python3.8 is working fine.

[Pyhton3.9] Allowing Hue to install virtualenv for >= python3.8

---

desktop/core/base_requirements.txt

- greenlet==0.4.15 => greenlet==2.0.2
- sasl==0.2.1 => sasl==0.3.1
- Created a canary and build a jenkins cluster with that GBN (python3.8)
- Hue is running fine.
- All the basic functions are checked

[python3.9] Upgrading greenlet and sasl as old versions are not compatible with py39

---

desktop/conf.dist/gunicorn_log.conf
desktop/conf.dist/log.conf

- Fix missing gunicorn_log.conf file in /etc/hue/conf folder.
- Checked CDH parcel containing gunicorn_log.conf file.

[log] Fix missing gunicorn_log.conf file in /etc/hue/conf folder.

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/lib/raz/raz_client.py
desktop/core/src/desktop/lib/raz/raz_client_test.py
desktop/core/src/desktop/lib/sdxaas/__init__.py
desktop/core/src/desktop/lib/sdxaas/knox_jwt.py
desktop/core/src/desktop/lib/sdxaas/knox_jwt_test.py

- Instead of directly asking RAZ for delegation token via Kerberos credentials, we are now fetching JWT from Knox host (this setup can be in HA mode) and then serve that JWT to RAZ to get back the delegation token.
- The later flow using the delegation token remains the same.
- Updated existing UTs and added new UTs.
- Tested in a live cluster - Hue is successfully able to fetch JWT from Knox and serve it to RAZ. This was tested for both HA and non-HA cluster.
- However, RAZ is not configured to return delegation token for JWT scenario. So we cannot fully test it E2E yet. This will be tested when RAZ changes are done from their side.

[raz] Add JWT support for Hue-Raz Integration

---

desktop/core/src/desktop/lib/raz/clients_test.py
desktop/core/src/desktop/lib/raz/raz_client.py
desktop/core/src/desktop/lib/raz/raz_client_test.py

- With these changes, we are now directly talking to RAZ endpoint for FS operation authorisation checks either via Kerberos or JWT.
- This completely removes using RAZ delegation tokens from the flow now. Earlier we use to get RAZ DTs via Kerberos (and future JWT) and pass that DT to RAZ again along with FS operation authorisation call, but its direct now and removing this hop.
- Tested in a live cluster - Hue is working fine using Kerberos to call RAZ. All existing FS operations looks good.
- Tested fetching JWT from Knox also in the live cluster and Hue is successful in getting it and passing to RAZ.
- However, RAZ is not configured to validate the incoming JWT and then authorise the FS operations. So we cannot fully test the existing FS operations E2E yet for JWT scenario. This will be …

[raz] Skip using RAZ DTs for FS operation authorisation

---

desktop/core/base_requirements.txt

Upgrade django-auth-ldap 4.3.0 and python-ldap 3.4.3
Manually tested login, sync user, sync group, sync users/group
And verify:
```
[root@yc-ldap-1 hue]# ./build/env/bin/hue shell --cm-managed
LD_LIBRARY_PATH can't be found, if you are using ORACLE for your Hue database
then it must be set, if not, you can ignore
export LD_LIBRARY_PATH=/path/to/instantclient
Python 3.8.12 (default, May 15 2023, 20:53:28) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import django_auth_ldap
>>> print(django_auth_ldap.__version__)
4.3.0
>>> import ldap
>>> print(ldap.__version__)
3.4.3
```
Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull …

[core] Upgrade django-auth-ldap 4.3.0 and python-ldap 3.4.3

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/middleware.py
desktop/core/src/desktop/middleware_test.py
desktop/core/src/desktop/settings.py

Add headers which restrict caching of the webpage (headers : Cache-Control, Pragma, Expires). This can be turned on/off by the config 'custom_cache_control'. By default caching is turned on and the config 'custom_cache_control' is set to false.
Manual tests - on a local Hue and CDH cluster Hue. The caching headers are visible in response headers. 
Attaching screenshot.

Add cache-control headers to restrict webpage caching

---

apps/oozie/src/oozie/templates/dashboard/list_oozie_workflow_graph.mako
apps/oozie/src/oozie/templates/dashboard/rerun_workflow_popup.mako

In the job browser view of Oozie workflow graphs we show the status of each widget as a progress bar attached to the individual widgets. When a user initiated a re-run of the entire workflow the status bars were updated one by one as they were executed and any following widgets were left with their previous status making it impossible for the user to get an indication of the current progress of the rerun.
To fix this it will now clear the status of all widgets in the graph once a re-run is submitted.

[jb] Clear the widget status on workflow rerun

---

desktop/core/src/desktop/auth/backend.py

Internal Jira: CDPD-56693
Added to print the failure message and also disabled resetting the credentials.
The patch was tested in a internal cluster which has Pam + kerberos enabled at that OS level
Pam file
cat /etc/pam.d/hue
#%PAM-1.0
auth required pam_krb5.so realm=ROOT.HWX.SITE keytab=FILE:/etc/pam.keytab
password required pam_deny.so
**_account required pam_permit.so_**  -------->   this is needed as an additional check for the user's account status was implemented by calling the function pam_acct_mgmt is by default in python-pam module. If the response indicates that the user is not allowed access to the system, authentication might fail with one of the following errors:
PAM_AUTH_ERR
PAM_SYSTEM_ERR
The call to pam_acct_mgmt fails when the authentication configuration on the system …

PamBackend authentication fails with PAM_AUTH_ERR or PAM_SYSTEM_ERR

---

apps/jobbrowser/src/jobbrowser/templates/job_browser.mako

- Knockout wrongly mounts components inside ` ` when condition is false.
- Investigation revealed that it can be solved using templates.

[ui] Knockout wrongly mounts components when not visible

---

desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py
docs/docs-site/content/administrator/configuration/connectors/_index.md
tools/docker/hue/Dockerfile

https://github.com/laughingman7743/PyAthena
https://pyup.io/packages/pypi/pyathena/changelog
- I would like to get variables '**work_group**' and '**catalog_name**' from python library **PyAthena**, otherwise can not use **Hue AWS Athena connector** without these variables.
- Not defined variable "workgroup" leads to the situation declined access:
```
An error occurred (AccessDeniedException) when calling the StartQueryExecution operation: You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again.
```
- And another variable '**catalog_name**' allow choose sources of data if you have a few sources in one AWS account instead of default data source.
Patch tested manually from Docker image …

Add vars 'work_group' and 'catalog_name' from python lib PyAthena for AWS Athena connector

---

docs/docs-site/content/administrator/installation/_index.md
docs/docs-site/content/releases/release-notes-4.4.0.md
docs/gethue/content/en/posts/2018-04-04-hue-4-2-and-its-self-service-bi-improvements-are-out.md
docs/gethue/content/en/posts/2018-10-17-hue-4-3-and-its-app-building-improvements-are-out.md
docs/gethue/content/en/posts/2019-03-02-configure-ambari-hdp-with-hue.md
docs/gethue/content/en/posts/2019-03-12-hue-in-docker.md
docs/gethue/content/en/posts/2019-03-22-quick-task-how-to-query-apache-druid-analytic-database.md
docs/gethue/content/en/posts/2019-03-26-quick-task-fixing-importerror-no-module-named-google_compute_engine-when-building-hue.md
docs/gethue/content/en/posts/2019-03-28-hue-4-4-and-its-improvements-are-out.md
docs/gethue/content/en/posts/2019-04-01-hive-on-tez-integrations-improvements.md
docs/gethue/content/en/posts/2019-04-12-documentation-revamp-making-hue-easier-to-install-use-and-develop.md
docs/gethue/content/jp/posts/2018-10-31-hue-4-3-and-its-app-building-improvements-are-out.md
docs/gethue/content/jp/posts/2019-03-08-configure-ambari-hdp-with-hue.md

- Update old docs dead links with new docs.gethue.com links.
- Remove open datahub dead link.
- Docs and blog built locally via hugo

[docs] Fix few dead links

---

tools/docker/hue/Dockerfile

When I build a hue dockerfile and run that image on the container, I found the Error Log that "Folder Not found /var/log/hue". So I add the code to make a /var/log/hue folder in the Dockerfile.

[Dockerfile] Add /var/log/hue folder for loading log data

---

tools/ci/check_for_python_lint.sh

This reverts commit d2ffc44e8b143d57015dc8f4fd0e594f2d5305ab.
re-enable the lint check

Enable temporarily disabled lint check

---

apps/beeswax/gen-py/TCLIService/TCLIService.py
apps/beeswax/src/beeswax/server/hive_server2_lib.py
desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/auth/backend.py
desktop/core/src/desktop/auth/views.py
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/middleware.py
desktop/core/src/desktop/middleware_test.py
desktop/core/src/desktop/views.py

Passing X-Forwarded-For header via thrift calls made to hive/impala when using knox and saml logins. 
Tested on Clusters with Knox and SAML logins. Hive debug logs shows the X-Forwarded-For header received from Hue. 

Add support for XFF header in Knox and SAML logins

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/settings.py

- Use the key server url to determine if custom jwt auth is set or not.
- Manually

[jwt] Remove redundant IS_ENABLED config

---

desktop/core/src/desktop/auth/api_authentications.py
desktop/core/src/desktop/auth/api_authentications_tests.py
desktop/core/src/desktop/conf.py

- When in HA mode, take healthy JKU to fetch the public key-set.
- Key server urls are comma separated configs in Hue in HA mode.
- Adding new unit tests.
- Tested in HA setup.

[jwt] Support JKU HA for public APIs JWT auth

---

desktop/libs/indexer/src/indexer/templates/importer.mako

- Iceberg checkbox is visible only when we choose 'Remote File' option in importer.
- Manually

[Importer] Iceberg checkbox is visible only for 'Remote File'

---

tools/cloudera/build_hue_common.sh

Pin the mysqlclient to 2.1.1 to avoid build time error with 2.2.0. Notice this mysqlclient won't be in Hue virtual env
Manual

[build] Pin mysqlclient 2.1.1 in Hue build time

---

apps/jobbrowser/src/jobbrowser/templates/job_browser.mako
apps/oozie/src/oozie/templates/editor2/common_scheduler.inc.mako

Throughout the Job Browser we use click events on table rows and because they're not anchor elements a ctrl/cmd click or middle mouse button click on the row won't open it in a new tab.
The proper solution would be to "modernize" this entire code-line but to solve the issue short term I've added certain event checks to detect the intention to open in a new tab.
This also takes care of some broken links where only the context popover were shown instead of document when clicking. Now the context popover is only shown when clicking the 'i' next to the link.
Tested manually.

[jb] Add support for middle button/ctrl/cmd click to open Oozie related links in a new tab

---

apps/jobbrowser/src/jobbrowser/api2.py
apps/jobbrowser/src/jobbrowser/apis/schedule_api.py
apps/jobbrowser/src/jobbrowser/templates/job_browser.mako

With this PR the status filter has been implemented for the tasks table, this was left todo many years ago, back when we made the switch from the dedicated Oozie status pages to the Job Browser in Hue 4, and for some reason we never got around to fixing this.
Given that the Job Browser pages are generic in the sense that the same code is used to display many types of "jobs" I've deliberately kept this change as non-intrusive as possible. Existing patterns, variables and values have been re-used even if there's quite some room for improvement and the filter will only appear for the tasks listing in the schedules tab.
While working on this I noticed that the pagination for the tasks listing was completely broken so I also fixed that.

Added filter and fixed pagination for the tasks list in the schedules Job Browser

---

apps/jobbrowser/src/jobbrowser/templates/job_browser.mako

The Job Browser page is split in two tables, one for running and one for completed jobs. When a user checks an item in the running table and performs some action, that moves the item to the completed table, the selected item might not be visible anymore. This can cause confusion when there are many jobs as some actions are only allowed when a single item is checked.

[jb] Uncheck jobs that transition between completed and running

---

apps/jobbrowser/src/jobbrowser/apis/query_api.py
apps/jobbrowser/src/jobbrowser/apis/query_api_tests.py

**NOTE!**
Even though I had commented on it myself, I missed that we actually had a good [PR from the community](https://github.com/cloudera/hue/pull/3371) to fix this issue. We can close this and use that PR if we like, or vice versa.
- refactored conversion into separate function and added fix millisecond precision which should be digits long.
- added unit tests
- unit tests

[jobbrowser] fix ms conversion precision in job start_time

---

desktop/core/src/desktop/middleware.py

For knox authentication, the host from header HTTP_X_FORWARDED_HOST is matched against the list of the knox gateways/hosts. But, when a request is passing through a hue_lb then the header contains the hostname of the LB and in such cases, the auth was failing.
This commit includes the hue_lb's in the the list to be matched with the FORWARDED_HOST values in the header.
Tested on cloudcat cluster with knox and HUE LB
Change-Id: I66bcbc74ecdf2ba7e623a41e345158da641a4ffd

[security][knox] include hue_lb in the list of allowed hosts

---

desktop/core/src/desktop/js/utils/html/html2text.ts
desktop/core/src/desktop/templates/common_notebook_ko_components.mako

[editor] Sanitize contents when copying results to the clipboard

---

tools/cloudera/build_hue_cloudera.sh
tools/cloudera/build_hue_common.sh
tools/relocatable.sh

- Adding sles15 build function
- Removing "bc" logic
- Canary build + Jenkins cluster

[Core] Add sles15 build script and removing 'bc' cmd logic

---

desktop/libs/notebook/src/notebook/connectors/spark_shell.py
desktop/libs/notebook/src/notebook/connectors/spark_shell_tests.py

- This change fixes the  edge cases for complex datatypes which were still failing: arrays, maps and structs.
- Tested in local Hue by connecting it to Spark3 running in a cluster.
- Added new unit tests.

[sparksql] Improve complex type result parsing

---

desktop/libs/indexer/src/indexer/file_format.py
desktop/libs/indexer/src/indexer/indexers/morphline_tests.py

- Replacing '\r\n' with '\n' 
- Manual
- Unit test

[Importer] Handle malformed data to improve delimiter guessing

---

docs/docs-site/content/administrator/installation/dependencies/_index.md
docs/docs-site/content/developer/development/_index.md

Updated the documents under content section. The following 2 lines of coded have been added: 
#export ROOT which should point to your Hue directory 
export ROOT=<path_to_hue_directory>
The added lines have been reviewed on GitHub before committing and merging them.

Updated Hue documentation with ROOT's path

---

apps/filebrowser/src/filebrowser/templates/display.mako
apps/filebrowser/src/filebrowser/templates/fb_components.mako

This takes care of possible xss injection through file and folder names in the File Browser.
All available actions and navigation options manually tested with malicious folder and file names.

[fb] Prevent cross site scripting in file and folder names

---

desktop/core/src/desktop/management/commands/desktop_document_cleanup.py

In some cluster, the Oozie is not enabled, so it is blacklisted app. document cleanup will failed with error:
`RuntimeError: Model class oozie.models.Job doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`
Manually tested with oozie  enabled or disabled

[commands] Check if Oozie is enabled in desktop document cleanup

---

desktop/core/src/desktop/js/reactComponents/FileChooser/FileChooserModal/FileChooserModal.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/PathBrowser/PathBrowser.tsx

- Currently the PathBrowser component has the breadcrumbs coupled with new folder and  upload button. Separating the two would allow the breadcrumbs to be reused in storage browser component. 
- Manual test

[frontend]Separate breadcrumbs from Pathbrowser component

---

tools/container/hue/supervisor-files/hue_loglistener_template

hue_loglistener isn't starting. thus logs are not generated. adding python before the log listener path
Change-Id: Ib8170176fcc8ce6deb9ec19aa75e4f1f51738705
manual test, hue_loglistener comes up fine.

hue_loglistener isn't starting.

---

desktop/libs/hadoop/src/hadoop/fs/webhdfs_types.py
desktop/libs/indexer/src/indexer/indexers/sql.py
desktop/libs/indexer/src/indexer/indexers/sql_tests.py

Issue:
End user is using a csv file in an encryption zone in the importer, then an error pops up: 
```ValueError: Extra data: line 1 column 5```
Added a unit test for checking the scratch path.
Manual test in a cluster with csv inside/outside encryption zone

[importer] Avoid creating scratchdir outside of encryption zone

---

Makefile
tools/cloudera/build_hue_cloudera.sh
tools/cloudera/build_hue_common.sh

Change-Id: I487830795482f9387a1fd41c9df51043d2b63c3d
The latest version of virtualenv==20.24.5 has changes related to brew and it crashes when building hue, as hue pulls the latest version of virtualenv. 
Error: " AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython3macOsBrew'"
So pinning the version of virtualenv==20.24.4 and virtualenv-make-relocatable==0.0.1 to avoid build failures. 
created a build and tested

[build] Pin virtualenv==20.24.4 and virtualenv-make-relocatable==0.0.1 versions

---

tools/cloudera/build_hue_cloudera.sh
tools/cloudera/build_hue_common.sh

Change-Id: I98330c468fec401cc06e911477832a640994db1d
Fix: Move VIRTUAL_ENV_VERSION and VIRTUAL_ENV_RELOCATABLE_VERSION declaration to correct location. 
In hue build, the "install_prerequisite" function gets the virtualenv version as empty string as it is used before declaration. This change will fix it. 
Tested on local machine

Fix VIRTUAL_ENV_VERSION declaration to correct location

---

Makefile

Change-Id: I7043802405ba0c5d7371deeddaf5aa637c15fe69
New version of virtual-env 20.24.4 crashes for rhel9 when running setup.py for pysaml2 with the following error
" ModuleNotFoundError: No module named 'setuptools'. "
Pinning the virtual-env version to 20.19.0 for Rhel9 fixes this issue. 
Created a build on Rhel9 and tested it.

Latest virtual-env crash with Rhel9, falling back to older version

---

package.json
webpack.config.npm.js

- added fix to remove npm dependencies starting with "file:"
- built using `npm run webpack-npm`
- ran `npm install` in npm_dist folder to verify that there was no error 

[build] remove cuix dependencies from published npm package

---

desktop/libs/notebook/src/notebook/connectors/base.py
desktop/libs/notebook/src/notebook/connectors/base_tests.py

There are multiple different ways that the various calls from UI pass
the compute information. Sometimes, it is a compute, other times it
is a connector etc. This change looks at config. So, if computes are
enabled then look up for compute in snippet, if connectors are
enabled then look for connector in snippet. If none of these are found,
then fallback to the default mechanism of picking up interpreter as
defined in the hue.ini
This bug got introduced in the earlier commit 283676c. Also, reverted
the unneeded change to connectors/base_test.py from that commit.
Change-Id: I8148f7dbf031c329f738ed94ba073161d8d8b4df

[core] Fixed the compute selection logic for query exec

---

desktop/libs/notebook/src/notebook/connectors/base.py

There was a leakage in the previous logic. If computes were enabled but a regular call with no compute came, the interpreter was not getting set. Now a the default interpreter lookup based on configs gets used when no compute or connector is found.
Change-Id: Iae18a98971e543cfb3ede8b4cc0aea4383257087

[core] Use default interpreter when no compute/connector

---

desktop/libs/azure/src/azure/abfs/abfs.py

- We were reading extra 1 byte from the abfs file
- Header['range'] = headers['range'] = 'bytes=x-y' in this x is starting point and y is end point and both are included hence we removed the 1 byte from y to make sure we are not duplicating the bytes.
- Locally

[ABFS] Fix reading file operation by 1 bytes

---

desktop/libs/azure/src/azure/abfs/abfs.py

- We were reading extra 1 byte from the abfs file
- Header['range'] = headers['range'] = 'bytes=x-y' in this x is starting point and y is end point and both are included hence we removed the 1 byte from y to make sure we are not duplicating the bytes.
- Locally and in live DH cluster

[ABFS] Fix download by reading file correctly instead of extra 1 byte always with every chunk

---

desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py

In phoenix database and table names are case sensitive, but in the sql_achlemy code we do upper() which is causing the tables not to be listed out.
Internal Jira: CDPD-61651
remove upper() for database and table
Performed manual test in a internal cluster and also via sqlalchemy.
>>> from sqlalchemy import create_engine, inspect
>>> engine = create_engine('phoenix://<phoenixserver>:8765')
>>> insp = inspect(engine)
>>> print(insp.get_schema_names())
['', 'SYSTEM', 'tcastestlower']
>>> print(insp.get_table_names("tcastestlower"))
['mahesh_test']
>>> print(insp.get_view_names("tcastestlower"))
['test_table']
>>> print(insp.get_table_names("TCASTESTLOWER"))
[]
>>>

Fix phoenix database and table names case sensitive

---

apps/filebrowser/src/filebrowser/templates/listdir_components.mako

For the filebrowser. Disable the copy button and the move button in the modals when 
a) The target path is "loading" (i.e. while there is diff between what the user has clicked and what has been registered).
b) The target is the same as the source path. 
- Manual testing of moving and copying files and folders 

[frontent] fix incorrectly enabled move and copy button in modal

---

.circleci/config.yml

Fix ARM64 build failed.
For detail of arm64 circle ci vm: https://circleci.com/docs/using-arm/
- tested by the circle ci test

[circleci] Update ARM64 machine image version

---

package-lock.json
package.json

This takes care of the following reported issues:
High - json5  <1.0.2 || >=2.0.0 <2.2.2
Prototype Pollution in JSON5 via Parse Method
Moderate - css-tools <4.3.1
Regular Expression Denial of Service (ReDOS) while Parsing CSS
Moderate - semver  <=5.7.1 || 6.0.0 - 6.3.0 || 7.0.0 - 7.5.1
semver vulnerable to Regular Expression Denial of Service
Tested manually.

[frontend] Fix various npm audit reported issues

---

apps/beeswax/src/beeswax/common.py
apps/beeswax/src/beeswax/models.py
apps/beeswax/src/beeswax/server/dbms.py
apps/metastore/src/metastore/views.py
desktop/libs/notebook/src/notebook/api.py
desktop/libs/notebook/src/notebook/connectors/base.py

The main bug being fixed is the broken describe db/table call on the table browser. The compute information was incorrectly being picked up and causing even the non-compute setup to be broken.
There are several different ways that compute information is passed in the api requests and within the code. This commit creates a single set of functions to handle the compute selection.
Change-Id: I0cb42b8fcfefac14ce193384a61f4e87b8848031

[core][computes] fixed compute selection for variety of requests

---

apps/beeswax/src/beeswax/server/dbms.py

The current logged in user's username was not being sent to Hive/Impala and instead `hive` was going out. This commit fixes it and sets the correct username.
Change-Id: I61bc4ac4545be397ca02c85c62daec74785667a6

[core][compute] fixed username for query execution

---

apps/beeswax/src/beeswax/server/dbms.py
apps/beeswax/src/beeswax/server/hive_server2_lib.py

The regular beeswax/hive connections set `hive.server2.proxy.user` to the current username but it was missing for the compute based connections. This commit adds a flag `is_compute` to query_server_config for compute/connector based configs.
Impala based connections were already setting the correct usernames on the connection.
Change-Id: I23521a5c1cf3d650da551b343d18820862feb7c5

[beeswax][compute] set username for computes/hive connection

---

apps/beeswax/src/beeswax/api.py
desktop/core/src/desktop/js/catalog/DataCatalogEntry.ts

fetching sample data from a view might be an expensive operation which causing query engineer resource issue

[query] Stop fetching sample data of a view

---

desktop/libs/notebook/src/notebook/conf.py

Currently we show the Hive or Impala editors even when there isn't a single compute available for that interpreter. This leads to unnecessary errors.
This commit adds an additional check for presence of computes while returning the list of editors in get_config call.
Change-Id: Id3837cc3b81da5f54d7539b89a6a9ae2f4a122b1

[compute] handle case of no hive or impala compute

---

desktop/libs/notebook/src/notebook/api.py

Cluster type is direct when there is no separate cluster/compute configured and the queries are supposed to go through the hive/impala specified in the connector request object.
Change-Id: I52c0ad97774c569cc41109c95f5334506c6b1386

[compute] Ignore cluster obj when type is direct

---

tools/container/hue/hueconf/altscript.sh

- Support custom jceks file path.
- Right now its hard coded to /jceks/secrets.jceks
- Manually tested in a real cluster

Support custom jceks

---

desktop/core/src/desktop/js/apps/notebook/snippet.js
desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

the problem is that when multiple queries are executed, we are not able to reuse the existing sessions as the session reuse is broken.
if computes are in use then use compute[name] as the type otherwise fallback to old snippet[type] and use it everywhere.
Change-Id: I0e6cb1149ca7961fc799ccce69fe70343d241bb5

[compute] check correctly for is_compute for session_type

---

apps/beeswax/src/beeswax/common.py

the default placeholder namespace_id is non numeric and breaks when we attempt to load record from db. This is actually an invalid id and we should not really be attempting to load from db.
Change-Id: If5305457291e779804434dd93f9dcf2e075fb903

handle non numeric id for namespace

---

desktop/libs/aws/src/aws/s3/s3fs.py

- listing of keys was wrong when we have same prefix in two files or folders
- Handling files and folders correctly 
- Locally

[s3] Fix key prefix for directories in copy operation

---

package-lock.json

The following packages were automatically upgraded to safe versions by running "npm audit fix":
adobe/css-tools  <4.3.1
Severity: moderate
Regular Expression Denial of Service (ReDOS) while Parsing CSS - https://github.com/advisories/GHSA-hpx4-r86g-5jrg
@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
json5  <1.0.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
semver  <5.7.2 || >=7.0.0 <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of …

[frontend] Fix vulnerabilities reported by npm audit

---

apps/beeswax/src/beeswax/server/dbms.py

The regular connections are not using session_pools. Our compute based connections are using session pools. This is leading to occasional expired queries.
This commit changes the default for compute/connector configs to not use session pools by default.
Change-Id: I1472a32146a14a159190226caa11fa6d6852a5bf

[compute] don't use session_pool by default

---

desktop/conf/dev_log.conf
desktop/core/src/desktop/log/__init__.py

Fix the Hue log level started with DEBUG. In Python 3, Logger.setLevel() calls to clear the cache. So, even the django_debug_mode=false, set the handler level to INFO.
```
class Logger(Filterer):
...
def setLevel(self, level):
"""
Set the logging level of this logger.  level must be an int or a str.
"""
self.level = _checkLevel(level)
self.manager._clear_cache()
```
Setting dev_log.conf in env variable DESKTOP_LOG_CONF_FILE is for local development with **runserver**.
CDW docker and data hub cluster.

[log] Default log level to INFO in all handlers

---

desktop/libs/indexer/src/indexer/templates/importer.mako

- Implement a regular expression for validating column names in tables for the importer.
- Hive tables allow spaces in column names
- https://issues.apache.org/jira/browse/IMPALA-4443
- Locally 

[Importer] Add a regex for column name validation in table creation

---

desktop/libs/indexer/src/indexer/indexers/sql.py
desktop/libs/indexer/src/indexer/indexers/sql_tests.py
desktop/libs/indexer/src/indexer/templates/importer.mako

- Adding an option "Copy file" in importer to copy file
- Locally in both AWS and AZURE

[Importer] Adding an option to copy and not just move files

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/ext-py3/boto-2.49.0/boto/gs/connection.py
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/lib/fs/gc/client.py
desktop/core/src/desktop/lib/fs/gc/gs.py
desktop/core/src/desktop/lib/fs/gc/gsconnection.py
desktop/core/src/desktop/lib/fs/proxyfs.py
desktop/core/src/desktop/lib/raz/clients.py
desktop/core/src/desktop/lib/raz/raz_client.py

- Piggybacking on S3, this PR allows the Google Storage access in Hue to pass through the already existing RAZ implementation for fine-grain access control.
- Manual testing in live cluster

[raz] Make user access for GS compatible with existing RAZ implementation

---

desktop/core/src/desktop/js/reactComponents/AlertComponent/AlertComponent.test.tsx
desktop/core/src/desktop/js/reactComponents/AlertComponent/AlertComponent.tsx

With this change we prevent showing multiple alerts with the same message and we also prevent showing alerts that are empty.
Unit tests added and tested manually

[frontend] Only show unique error message that have contents

---

desktop/libs/aws/src/aws/s3/s3connection.py

We want to always use AnonAuthHandler when Raz is enabled and that is what gets used in most cases, except for some regions.
S3Connection._required_auth_capability() has a decorator @detect_potential_s3sigv4 that overrides the default func (that works correctly) for certain regions (boto.auth.SIGV4_DETECT). So, RAZ is currently broken for regions cn-*, eu-central, ap-northeast-2, ap-south-1, us-east-2, ca-central and eu-west-2. We end up using auth.S3HmacAuthV4Handler rather than AnonAuthHandler.
This commit overrides _required_auth_capability() in RazS3Connection to look for AnonAuthHandler.

[RAZ][S3] Force AnonAuthHandler when Raz is enabled

---

tools/container/huelb/hue_httpd_template

This pull request addresses the throttling of concurrent connections (approximately at 200 simultaneous threads) by the Apache load balancer when directing traffic to the Hue server. The scalability of the Apache load balancer is enhanced by implementing the mpm_event module.
- The patch underwent stress testing using Jmeter.
- Tests were conducted on both Redhat8 and Centos7 systems with varying computational capacities and node configurations.
- Below is a sample result from a Redhat 8 machine:
**Default Apache Configurations:**
```
"Summary: + 1591 in 00:00:30 = 53.1/s Avg: 20938 Min: 0 Max: 172930 Err: 510 (32.06%) Active: 989 Started: 1000 Finished: 11
Summary Total: 14118 in 00:09:17 = 25.4/s Avg: 20088 Min: 0 Max: 174866 Err: 2668 (18.90%)"
```
- The test concluded in roughly 10 …

mpm_event module to improve apache scalability

---

desktop/core/requirements.txt
desktop/core/src/desktop/models.py

There was some error left in the PR (https://github.com/cloudera/hue/pull/3514/files), this is the update for the same.
Original PR (https://github.com/cloudera/hue/pull/3514/):
When a user visits Hue we open the editor by default after logging in. If Hue is configured to have multiple editors the first one is used by default.
Each user have the possibility to pick the default editor by clicking the star icon in the editor header. There are cases when an organization wants to control this for all users through configuration so we should add such a config setting in the .ini.
The order of deciding which editor to display would be:
If the user has "stared" an editor use that one
If there's a config for which editor to use use that one (new)
And lastly, pick the first editor in the list
For …

[core] Default to editor choice with default_app correctly

---

desktop/core/src/desktop/conf.py
desktop/core/src/desktop/lib/raz/raz_client.py
desktop/core/src/desktop/lib/raz/raz_client_test.py

- Add support for RAZ HA in Hue - multiple RAZ servers (min. 2)
- This changes is similar to the current approach for handling HA for services like Knox, Idbroker, Atlas etc. where we switch the host after error handling.
- There are long term improvements possible with caching healthy hosts with lazy switching -- but that requires some scoping for maintaining the cache state which is in the roadmap.
- Updated existing UTs and added new UTs.
- Tested in live cluster setup - both HA and non-HA.

[raz] Add support for RAZ HA

---

apps/filebrowser/src/filebrowser/conf.py
apps/filebrowser/src/filebrowser/templates/listdir_components.mako
desktop/core/src/desktop/api2.py
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/js/ext/fileuploader.custom.js
desktop/core/src/desktop/js/ext/fileuploader.custom.new.js
desktop/core/src/desktop/js/hue.js
desktop/core/src/desktop/settings.py
desktop/core/src/desktop/static/desktop/less/components/hue-qq-upload.less

The chunked fileuploader breaks each file that is selected to be uploaded into chunks and stores them first to local storage. This backend PR : https://github.com/cloudera/hue/pull/3504 picks these locally stored chunked files and uploads them to desired filesystem (HDFS, S3, ABFS, Ozone). This chunked upload feature can now help the user upload large GB files without hogging the Hue Server. 
Manual testing on hdfs, S3, ABFS

Chunked File Uploader - front end changes

---

desktop/core/src/desktop/js/ko/bindings/ko.reactWrapper.js

Made KO-react bridge consistently unwrap KO observables
- Verified that creation and updates and works with a root component
- Verified that no root components where dealing with the props as functions only

[frontent] Make KO-react bridge consistently unwrap KO observables

---

apps/useradmin/src/useradmin/ldap_access.py

Fix LDAP sync group without import posix group users. The group info fetch from LDAP server are binary string, and keys in CaseInsensitiveDict are lowercases.
tested LDAP with posix groups and users on DC cluster.

[ldap] Fix LDAP sync group without import posix group users

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/api.ts
desktop/core/src/desktop/js/reactComponents/FileChooser/types.ts

[##]([url](url)) What changes were proposed in this pull request?
- Allows sorting of columns in ascending or descending order based on toggle of the column header.
https://github.com/cloudera/hue/assets/44032758/3c09d580-2761-4e6d-98a6-d0a40264bce0
- Manually

[frontend] Implementation of sorting columns in Storage browser table

---

tools/container/base/hue/Dockerfile

RDS Postgres server 11 will be EOF soon. Upgrade PostgresSQL to version 13
Deployed the Canary docker build and run pg_dump/pg_restore

[docker] Upgrade PostgresSQL version from 11 to 13

---

desktop/libs/azure/src/azure/abfs/abfsstats.py

- If user is set to None, it was failing a small edge case of sorting the file listing by user column with the following error:
```
Status code : 500 Internal Server Error
TypeError at /filebrowser/view=abfs://xyz
'<' not supported between instances of 'NoneType' and 'NoneType'
```
- Sorting is also failing when using the `group` and `date` column. 
- Better none check handling fixes the above issues.

[abfs] Fix none check for ABFSStat attributes

---

desktop/libs/notebook/src/notebook/connectors/jdbc.py

- Remove py2 excepton syntax and import section. It was breaking JDBC code on py3 env.

[jdbc] Remove Py2 syntax

---

apps/beeswax/gen-py/TCLIService/TCLIService.py

Internal Jira: CDPD-65034
Seeing the exception:
thrift_util  ERROR    Thrift saw exception (this may be expected).
File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/desktop/core/src/desktop/lib/thrift_util.py”, line 522, in wrapper
ret = res(*args, **kwargs)
File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/apps/beeswax/gen-py/TCLIService/TCLIService.py”, line 255, in decorate
trans_client.setCustomHeaders({‘X-CSRF-TOKEN’: csrf})
TypeError: ‘NoneType’ object is not callable
and
File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/desktop/core/src/desktop/lib/thrift_util.py”, line 522, in wrapper
ret = res(*args, **kwargs)
File “/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p0.44702451/lib/hue/apps/beeswax …

Check csrf to see if it has value before setting it up

---

tools/cloudera/build_hue_common.sh

- Update latest MySQL RPM for CentOS 7 because old RPM installation failed with GPG key
Manual repro with old PRM and tested with new RPM

[build] Update latest MySQL RPM for CentOS 7

---

.circleci/config.yml

- Remove old py3.8 CircleCI check which is based on py2 docker image.

[ci] Remove old py2 docker image based py3.8 CircleCI check

---

.github/workflows/commitflow-frontend.yml

- Remove file extension restriction for frontend CI
- This is run the Ci check for all PR including backend specific PRs. Reason to go with this is to make frontend CI check as required so that its not skipped even for frontend focused PRs.

[ci] Run frontend CI for all PRs

---

desktop/core/src/desktop/js/apps/tableBrowser/metastoreViewModel.js

Previously the hue prefix was only added if Knox was not running, 
which caused the back button to trigger a 404.
- Updated the metastore.url.change in metastoreViewModel.js
@wing2fly this change will overwrite some of you changes here https://github.com/cloudera/hue/pull/2111 but I think it will still work since all parts called 'hue' are removed before actually loading the data.
- Tested by manually temporary modifying the window.HUE_BASE_URL in  metastoreViewModel.js and changeURL.ts to verify that HUE_BASE_URL = '/hue' would result in a url containing two 'hue' in the path. E.g. looking like _hue/hue/metastore/table/default/sample_07?source_type=hive_ when navigating in the table browser. Because that is how the base url looks in a Knox enabled setup.
- Please review [Hue Contributing …

[frontend] added 'hue' to metastore url prefix when running Knox

---

apps/filebrowser/src/filebrowser/api.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py

- Implement a dedicated /touch API method tailored for new storage browser.
- This separates the old method for existing filebrowser to not have regressions + much cleaner new method.
- Manually

[api] Add new /touch public api

---

desktop/libs/notebook/src/notebook/connectors/trino.py

- Reformatting the return of the show_table for autocomplete call as the earlier format did not match our existing code.
- Due to a different format, samples for tables were missing in the left assist.
- Locally

[Trino] Reformatting the return of the show_table for autocomplete call

---

apps/filebrowser/src/filebrowser/api.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py

- Implement a dedicated /rename API method tailored for new storage browser.
- This separates the old method for existing filebrowser to not have regressions + much cleaner new method.
- Manually

[api] Add new /rename public api

---

desktop/core/src/desktop/lib/fs/gc/gsconnection.py

- Consolidating both RazGSConnection and SignedUrlGSConnection into one for better readability and improving docstrings.
- Manual testing in live setup.

[raz] Improve RazGSConnection class for better code readability

---

desktop/core/src/desktop/management/commands/sync_warehouses.py

Our hive authentication relies on the use of doAs parameter. The user with proxy_privilege (typically system user with enhanced privilege such as `hive`) is used as auth_username is same for all users. The currently logged-in user's username is passed in the `hive.server2.proxy.user` field while making the connection.
Since, we were not setting the default auth_username and password for computes, it was relying on using the currently logged-in user and was causing permission issues. This change fixes it.

[compute] set default user/pass for hive from config

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/libs/notebook/src/notebook/connectors/trino.py

- Add ldap/basic username and password authentication support
- https://github.com/trinodb/trino-python-client?tab=readme-ov-file#basic-authentication
- Need secure trino cluster.

[Trino] Add ldap/basic username and password authentication support

---

tools/ci/check_for_website_dead_links.sh

Fix the failing Github commitflow for documentation lint. For several new PRs it failed with error:
"..small read buffer. Increase ReadBufferSize."
Solution here is to double muffet buffer size to around 8 KB
- If the commitflow "run documentation lints" passes it should be ok

[frontend] increase muffet buffer size for dead link testing of docs

---

.github/workflows/commitflow-py3.yml

- Updates the github actions to use the latest versions
- Make sure the github action warnings about deprecated node versions are gone from the summary page for this PR

Updated versions of CI github actions to resolve deprecation warnings

---

tools/container/base/hue/Dockerfile

To support Azure PostgreSQL Flexible Server 14.9
The image is being build locally correctly.
$(find / -name "pg_dump" -type f) --version
pg_dump (PostgreSQL) 15.6

[docker] Upgrade PostgresSQL version from 13 to 15

---

desktop/conf.dist/gunicorn_log.conf
desktop/conf.dist/log.conf
desktop/conf/gunicorn_log.conf
desktop/conf/log.conf

Removing dev-only comment to avoid confusion
Just comments, no test required

[log] Remove the comment of dev only in log conf files

---

apps/filebrowser/src/filebrowser/api.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py

- Implement a dedicated /content_summary API method tailored for new storage browser.
- Removed redundant exceptions not relevant to API
- This separates the old method for existing file browser to not have regressions + much cleaner new method.
- Manually

[api] Add new /content_summary public api

---

desktop/core/src/desktop/conf.py
desktop/core/src/desktop/lib/idbroker/client.py
desktop/core/src/desktop/lib/idbroker/conf.py
desktop/core/src/desktop/lib/idbroker/tests.py
desktop/libs/aws/src/aws/conf.py
desktop/libs/aws/src/aws/tests.py
desktop/libs/azure/src/azure/conf.py
desktop/libs/azure/src/azure/tests.py

- Refactor IDBroker support and give more preference to RAZ when both are configured in Hue.
- Improved IDBroker HA code section to switchover to healthy instance correctly and not depend only on the first one for every scenario. This should improve Hue page loading performance also.
- Tested manually in a live E2E setup with RAZ enabled to check for no regressions + correct IDBroker switchover + improved Hue page load time.
- Update existing unit tests.
- Adding new unit tests for IDBroker HA.

[idbroker] Refactor IDBroker with improved HA support and giving more preference to RAZ when both are configured in Hue

---

apps/impala/src/impala/conf.py
apps/jobbrowser/src/jobbrowser/apis/query_api.py
apps/jobbrowser/src/jobbrowser/apis/query_api_tests.py
desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl

When the Impala coordinator web UI has Spnego enabled, clicking on the link in the mini job browser will result in 400 bad request, because there missing parameters in the link.
Example is the hyperlink under ID [fd477439047f4d91:fefe506000000000] in the screenshot.
- Manual test and unit test

Update the corrdinator URL pattern in Impala mini job browser

---

desktop/core/src/desktop/js/reactComponents/AlertComponent/AlertComponent.test.tsx
desktop/core/src/desktop/js/reactComponents/AlertComponent/AlertComponent.tsx

The info alert popup messages will automatically go after 3 seconds from when it is shown. Since, the error and warning messages are important and we want the user to close them themselves, so such a timer is only used for the info messages.
Attached a demo video. 
The patch is manually tested on the Hue UI using a stopwatch of 3 seconds.
https://github.com/cloudera/hue/assets/68558847/c1610f97-0ad8-48a9-bd79-ef9a8892b933

[frontend] Dismiss info alert popup messages after 3 seconds (along with Unit Test)

---

apps/jobbrowser/src/jobbrowser/templates/mini_job_browser.mako
desktop/core/src/desktop/js/apps/jobBrowser/miniJobBrowser.js
desktop/core/src/desktop/js/jest/koTestUtils.js
desktop/core/src/desktop/js/ko/components/ko.jobBrowserLinks.js
desktop/core/src/desktop/js/ko/components/ko.jobBrowserLinks.test.js
webpack.config.js

With this change I removed the dedicated mini Job Browser webpack entry and changed is so that the mini Job Browser JS gets initialized on first open instead of on document ready as before. This hopefully takes care of race condition issue with loading the config before the csrf token logic is attached.
On top of this I've also made sure that the component gets properly disposed and I fixed an issue that's been there for a while where the mini Job Browser reacts to URL hashes from the main Job Browser page.
Tested manually as well as a simple unit test to make sure it gets initialized only once.

[jb] Various mini Job Browser improvements

---

desktop/core/src/desktop/lib/sdxaas/knox_jwt.py
desktop/core/src/desktop/lib/sdxaas/knox_jwt_test.py

- Improve unit test cases for HA support for Knox gateway URLs.
- Running updated unit tests.

[knox_jwt] Improve unit tests for Knox JWT HA support

---

desktop/libs/notebook/src/notebook/connectors/trino.py
desktop/libs/notebook/src/notebook/connectors/trino_tests.py

- Explain query method added
- Manually
- Unittest added

[Trino] Adding explain query method

---

tools/container/huelb/Dockerfile

fix Huefrontend pod going to carshloopbackoff state
backport internal fix

[docker] fix Huefrontend pod going to carshloopbackoff state

---

desktop/core/src/desktop/conf.py
desktop/core/src/desktop/settings.py

Added 3 new configurations under [desktop] to control CORS. CORS must be enabled for public APIs and SAML login.
1. cors_enabled - Enable or disable Cross-Origin Resource Sharing (CORS). Defaults to True.
2. cors_allow_credentials - This value determines whether the server allows cookies in the cross-site HTTP requests. Defaults to True.
3. cors_allowed_origins - A comma separated list of origins allowed for CORS. If not set all origins are allowed.
- Hue was started locally on port 80
- Two new domains were added to /etc/hosts pointed to localhost - abc.com, def.com
- Logged into Hue via def.com domain.
- From browser dev tool, made a fetch request to abc.com - No error as **cors_allowed_origins** is not set.
- Set cors_allowed_origins=http://abc.com
- From browser dev tool, again made …

[api] Provide configs to control CORS

---

apps/filebrowser/src/filebrowser/views.py

- When filebrowser is blacklisted, we are getting the following error which is failing Hue startup:
```
File "/opt/hive/desktop/core/src/desktop/urls.py", line 50, in <module>                                                                                                                                                                                             │
│     from desktop import api_public_urls_v1                                                                                                                                                                                                                            │
│   File "/opt/hive/desktop/core/src/desktop/api_public_urls_v1.py", line 20, in <module> …
```

[fb] Check for get attribute for ARCHIVE_UPLOAD_TEMPDIR config

---

.eslintrc.js
apps/beeswax/src/beeswax/templates/execute.mako
desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/js/api/utils.ts
desktop/core/src/desktop/js/apps/editor/EditorViewModel.js
desktop/core/src/desktop/js/apps/editor/components/aceEditor/autocomplete/AutocompleteResults.test.ts
desktop/core/src/desktop/js/apps/editor/components/aceEditor/autocomplete/AutocompleteResults.ts
desktop/core/src/desktop/js/apps/editor/execution/api.ts
desktop/core/src/desktop/js/apps/editor/snippet.js
desktop/core/src/desktop/js/apps/notebook/NotebookViewModel.js
desktop/core/src/desktop/js/apps/notebook/aceAutocompleteWrapper.js
desktop/core/src/desktop/js/apps/notebook/snippet.js
desktop/core/src/desktop/js/catalog/api.ts
desktop/core/src/desktop/js/config/types.ts
desktop/core/src/desktop/js/jest/jest.init.js
desktop/core/src/desktop/js/reactComponents/AlertComponent/AlertComponent.test.tsx
desktop/core/src/desktop/js/sql/autocompleteResults.js
desktop/core/src/desktop/js/sql/autocompleteResults.test.js
desktop/core/src/desktop/js/sql/sqlAutocompleter.test.ignore.js
desktop/core/src/desktop/js/types/types.ts
desktop/core/src/desktop/js/utils/hdfsAutocompleter.js
desktop/core/src/desktop/models.py
desktop/core/src/desktop/templates/common_header_m.mako
desktop/core/src/desktop/templates/global_js_constants.mako
desktop/libs/notebook/src/notebook/templates/editor2.mako
desktop/libs/notebook/src/notebook/templates/editor_components.mako
desktop/libs/notebook/src/notebook/templates/editor_m.mako

Setting editor_autocomplete_timeout is currently dead code, so I decided to deprecate it with this commit and replace it with a boolean disable_source_autocomplete setting. The timeout setting was introduced in the past to support two use cases. First the old autocomplete selection panel would not show until all autocomplete suggestions had been fetched, to speed things up in the UI this could be set to a few seconds, today this is no longer needed as results are populated as they come in from the backend. The second use case was to disable API-based autocomplete all together by setting it 0, this has been broken for at least 3 years now.
Given that the timeout is no longer necessary I went for a boolean replacement.
Unit tests and manual testing.
While testing I also found an issue with …

[editor] Replace the editor_autocomplete_timeout setting with disable_source_autocomplete

---

desktop/core/src/desktop/js/apps/storageBrowser/InputModal/InputModal.scss
desktop/core/src/desktop/js/apps/storageBrowser/InputModal/InputModal.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/InputModal/InputModal.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/api.ts

- Implements create New file or folder modal 
- Allows new file or folder to be created
- Create new modal can be reused for creation of new buckets, renaming files and folders 
Manually

[frontend] Implement new file and folder creation

---

.eslintrc.js

This one checks missing return types and args, for some reason it's still a warning after the previous commit to change all warnings to errors.

[frontend] Change typescript eslint rule from warning to error

---

setup-hooks.sh
tools/git-hooks/pre-commit
tools/git-hooks/pre-push

Add a Precommit hook for linting on the diff
Run the script ./setup-hooks.sh for this to work.
Example Runs only on diffs:
Running ESLint for desktop/core/src/desktop/js/jquery/plugins/jquery.filechooser.js...
/Users/tabraiz/Documents/cloudera/internal-hue/hue/desktop/core/src/desktop/js/jquery/plugins/jquery.filechooser.js
791:4  error  Parsing error: Unexpected token, expected "," (791:4)
✖ 1 problem (1 error, 0 warnings)

[linting] precommit hooks for linting

---

desktop/core/src/desktop/lib/raz/raz_client.py

- If a directory has 1000+ keys, then when listing the objects using the GET request, it also required a `marker` header to fetch more keys.
- This `marker` headers needs to be unquoted when sent to RAZ but left unchanged when sent to S3 to have proper access on the path from RAZ side.
- Manual E2E testing in live setup.

[raz][s3] Fix encoding for special chars in directory name listing 1000+ keys

---

desktop/core/src/desktop/templates/global_js_constants.mako
desktop/core/src/desktop/templates/job_browser_common.mako

This takes care of two issues:
1. The Hive section was always enabled even though configured to be disabled
2. The knockout templates for details of an impala query contained syntax errors
Only manual testing. No unit tests on this one as the templates are still in mako files.

[jb] Fix two bugs from the previous job browser migration to webpack

---

.circleci/config.yml
.github/workflows/commitflow-frontend.yml
.github/workflows/commitflow-py3.yml
docs/docs-site/content/administrator/installation/dependencies/_index.md
docs/docs-site/content/developer/development/_index.md
tools/cloudera/build_hue_cloudera.sh
tools/cloudera/build_hue_common.sh
tools/docker/hue/Dockerfile
tools/docker/hue/Dockerfile.py2

- Update node.js from 14 to 20 (LTS is currently at 20.10.0). NPM will be on 10.
- engines node in 'package.json' does not enforce, it is a recommendation that can show a warning if not met.
- gihub actions
- circle CI
- docs
- docker files
- build scripts (only modified the scripts using nodesource.com where I could verify that the node version existed)
Tested on redhat8, redhat9, ubi8 docker images. 'node -v' returns 'v20.10.0'. Using @bjornalm change for circle ci, github workflow images from PR: https://github.com/cloudera/hue/pull/3566. 

update nodejs version from 14 to 20

---

apps/beeswax/src/beeswax/test_base.py
apps/metastore/src/metastore/tests.py
apps/security/src/security/tests.py
desktop/libs/hadoop/src/hadoop/fs/test_webhdfs.py

- Converted previously unconverted tests to pytest format
- Locally
- unittest

[test] convert remaining nose based test to pytest

---

desktop/libs/aws/src/aws/conf_tests.py

- Earlier this test will pass or fail according to the values in your local Hue setup configs.
- This PR removes that dependency and explicitly set the expected configs to run the tests and cleans them up afterwards.
- By running this unit testcase locally.

[tests] Fix S3 tests to not pickup local Hue setup configs

---

pyproject.toml
tools/ci/check_for_python_lint.sh

- We were ignoring the `E902` rule earlier because it was triggering for deleted files.
- Instead, this PR ignores the deleted files and not use them for lint checks to avoid further triggering such rules.
- Locally running lint checks.

[lint] Ignore deleted files for Ruff linting

---

apps/useradmin/src/useradmin/management/commands/promote_to_superuser.py
apps/useradmin/src/useradmin/management/commands/set_user_as_active.py

- added new command **set_user_as_active**, and moved & improvised custom_command **promote_to_superuser** to useradmin command. 
- **set_user_as_active** script will mark a given set of users as active.
- currently, **promote_to_superuser** is part of _custom_command_ and only handles the use case to promote a single user to superuser at a time. I have improvised this script to be part of hue useradmin commands and to promote single or multiple users to a superuser in a single go.
- manual testing

[useradmin] Add new "set_user_as_active" and improve "promote_to_superuser" commands

---

desktop/libs/notebook/src/notebook/connectors/base.py

We do not send all connector fields to the UI, such as `interface` and some `options`. So, the connector sent as part of the query exec is incomplete. Therefore we should only rely on the connector_name from frontend and use the rest from backend.

[connectors] connectors from request is incomplete

---

desktop/core/base_requirements.txt

- Bumping to the latest version fixes the following CVE:
- https://github.com/cloudera/hue/security/dependabot/231
- Tested manually in local Hue setup

[core][cve] Bump sqlparse to 0.5.0

---

desktop/core/base_requirements.txt
desktop/devtools.mk

- This package is having CVEs and I tried to where it is used in the Hue codebase but didnt get any dependency references so looks like its better to remove it.
- Tested locally

[core][cve] Remove werkzeug package

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx

- Add a "Folder is empty" placeholder for storage browser table.
- Removes the previous folder and current folder entry in the table. (i.e .. and . folders)
- Manually

[frontend] Implement placeholder for empty table scenario

---

desktop/core/base_requirements.txt

- Giving old style file path was failing `./build/env/bin/pip freeze` with the following error:
```
harsh.gupta@Harshs-MacBook-Pro hue % ./build/env/bin/pip freeze                                       
ERROR: Exception:
File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
status = run_func(*args)
File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/commands/freeze.py", line 98, in run
for line in freeze(
File "/Users/harsh.gupta/workspace/hue/upstream/hue/build/env/lib/python3.8/site-packages/pip/_internal/operations/freeze.py", line 43, in freeze
req = FrozenRequirement.from_dist(dist)
File …
```

[core] Change ext-py3 package installation path

---

desktop/core/base_requirements.txt

- Upgrading from 0.12.0 to 0.14.0 
- E2E downstream

[core] Upgrade the request_kerberos lib for python3.10 support

---

tools/relocatable.sh

- It was considering "3.10" < "3.8" as it compares lexicographically
- Using correct expression for python version comparison
- E2E downstream

[core] Correct expression for python version comparison

---

desktop/core/base_requirements.txt
desktop/core/src/desktop/management/commands/runruff.py
pyproject.toml

- Added a custom Django command in Hue for running ruff. 
This will help in not depending on tools/ci/check_for_python_lint.sh file and have all ruff functionality on the go via Hue command (both linting + formatting).
- Added an extra argument to specify the diff branch to compare the changed files. This will help in scenarios where the base development branch is not always `origin/master`.
<br>
- Improved the ruff configs to support formatting of python files and also updated Ruff to latest version.
- Manually in local setup.

[ruff] Add custom Ruff command in Hue and improve config file

---

desktop/core/src/desktop/management/commands/runruff.py

- Raised exception is not always an actual error. Mostly it notifies about the violations.
- Manually.

[ruff] Skip logging subprocess exception as error

---

pyproject.toml

- Ruff will lint the Python code with isort rules. 
- Manually in local setup.

[ruff] Enable isort rules for linter

---

desktop/core/src/desktop/lib/tasks/compress_files/compress_in_hdfs.sh

- In Python3, we need to use **urllib.parse** instead of **urllib**.
- Also, raw_input() was renamed to input(). Reference: https://docs.python.org/3/whatsnew/3.0.html#builtins
- Ref: CDPD-66706
- manually tested in CDP 7.1.9 and CDP 7.1.7 [SP1]

[filebrowser] updated file compression in hdfs to support py3

---

desktop/core/src/desktop/models.py
desktop/libs/notebook/src/notebook/api.py
desktop/libs/notebook/src/notebook/connectors/base.py
desktop/libs/notebook/src/notebook/models.py
desktop/libs/notebook/src/notebook/tasks.py

Disable schedule tasks tab in job browser based on task_server_v2 configs. 
Also move back notebook tasks to be enabled based on old task_server configs. 
-Tested on local mac and hue from docker builds. 

[taskserver] Disable schedule tasks tab in job browser based on task_server_v2 configs

---

desktop/core/src/desktop/management/commands/sync_warehouses.py

In some cases, there might be multiple clusters running in the same k8s environment. In such cases, we can pass a label selector to limit the k8s namespaces that hue service-discovery looks at.

[computes] add k8s label selector filter for service discovery

---

apps/filebrowser/src/filebrowser/tasks.py
apps/filebrowser/src/filebrowser/utils.py
desktop/core/src/desktop/api2.py
desktop/core/src/desktop/management/commands/rungunicornserver.py
desktop/core/src/desktop/settings.py

Avoid initializing free disk space in redis for all hue shell commands. The `initialize_free_disk_space_in_redis()` method was invoked for all hue shell commands and breaks the hue's service-discovery pod since there is no redis-server running in this pod. 
Moving it to rungunicornserver.py -> start_server() method, since `initialize_free_disk_space_in_redis` has to be invoked when hue server starts up. 
- Local testing on mac. Building docker images for testing. 

Avoid initializing free disk space in redis for all hue shell commands

---

desktop/core/src/desktop/js/apps/tableBrowser/metastoreTable.js

- View SQL option was visible for Impala but not for Hive. 
- It turns out we were correctly parsing the describe view response for Impala and checking for correct view SQL property.
- This was missing for Hive describe view response and now we are checking for Hive related property also with this change.
- Manually

[ui-tablebrowser] Fix viewSQL tab for Hive

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx

- Allows multi file or folder selection in storage browser
- Updated file summary to support multiple file selections scenario
- Manually
- Unit tests

[ui-storageBrowser]Implement multiselect for Storage browser table data

---

apps/filebrowser/src/filebrowser/api.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py
desktop/core/src/desktop/lib/fs/proxyfs.py

- Old Filebrowser APIs were bulky with all the form and args looping logic and rendering server side mako files.
- This PR implements few of the original APIs for public V1 with only core logic for the new storage browser sending only the required data for UI to use and getting rid of server side rendering slowly.
- APIs ported for V1:
- storage/move
- storage/copy
- storage/set_replication
- storage/rmtree
- storage/trash/restore
- storage/trash/purge
- Manually

[api][fb] Refactor existing filebrowser APIs to clean public APIs

---

desktop/core/src/desktop/js/reactComponents/MetricsComponent/MetricsComponent.scss
desktop/core/src/desktop/js/reactComponents/MetricsComponent/MetricsComponent.test.tsx
desktop/core/src/desktop/js/reactComponents/MetricsComponent/MetricsComponent.tsx
desktop/core/src/desktop/js/reactComponents/MetricsComponent/MetricsTable.tsx
desktop/core/src/desktop/js/reactComponents/imports.js
desktop/core/src/desktop/templates/metrics.mako

This PR is about shifting the entire code for the Metrics tab (page) in ReactJS i.e. adding Metrics as a react component. The Metrics page is present as a tab in the Administrator server.
I have added unit tests here. One for the selection dropDown and the other for filtering the metrics based on name.
The code is tested manually as well.
This is how the current Metrics page looks like.

[ui-metrics] Converted the Metrics page within Admin Server in ReactJS

---

apps/beeswax/src/beeswax/api.py
apps/beeswax/src/beeswax/server/dbms.py
apps/beeswax/src/beeswax/server/dbms_tests.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py
desktop/core/src/desktop/js/ko/components/ko.catalogEntriesList.js
desktop/libs/notebook/src/notebook/api.py
desktop/libs/notebook/src/notebook/connectors/hiveserver2.py
desktop/libs/notebook/src/notebook/urls.py

- Sample api added for nested/complex datatype
- SQL generation for sampling
- Handling the output
- Manually
- Unittest

[Hive] Support complex data type sampling

---

docs/gethue/content/en/posts/2024-06-26-integrating-trino-editor-in-hue-supporting-data-mesh-and-SQL-federation.md

- Trino blog
- Manually via Hugo

[Blog] Trino blog

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserActions/StorageBrowserActions.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx
desktop/core/src/desktop/js/apps/storageBrowser/SummaryModal/SummaryModal.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/api.ts
desktop/core/src/desktop/js/utils/storageBrowserUtils.test.ts
desktop/core/src/desktop/js/utils/storageBrowserUtils.ts

- Implement a rename modal and integrate it with the api
- Add tests to check for functionality and conditions.
- Update summary modal to call api only on modal open
- Add util functions to check for file systems. ( For eg: isS3, isGS and so on)
- UI Unit tests
- Manually

[ui-storageBrowser] Implement UI for rename action

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/types.ts

The `StorageBrowserTabContent` and `StorageBrowserTable` components are refactored such that the selection entity is file or directory can be identified, once they are identified, the relevant component is rendered to either show the table view for directory (existing) or viewing file content for files (to be built)
- Ran existing unit tests, as this PR focuses on refactoring the existing code.
- Manual tested the UI interaction to ensure no functionality is lost.

[ui-core] refactor storage browser to extend file preview feature

---

desktop/core/base_requirements.txt

- Repeating the change done in https://github.com/cloudera/hue/pull/3720 because it was reverted by mistake as a part of https://github.com/cloudera/hue/pull/3719.
- Manually in local setup

[core] Change ext-py3 package installation path again

---

desktop/core/src/desktop/settings.py

Celery's USE_TZ setting is overriding Django's timezone-aware datetimes setting. Due to this, time zone support is active in timestamps and written in the same format in hue tables like UserProfile. Certain configs in hue cannot process the timestamp if the timezone support is active like 
```
[[auth]]
idle_session_timeout=200
```
Set the USE_TZ=False in Celery settings. 
Tested on local machine, Kubernetes deployment. 

[Taskserver] Set timezone-aware datetimes to False

---

desktop/core/ext-py3/dnspython-1.16.0/dns/query.py
desktop/core/ext-py3/dnspython-1.16.0/dns/resolver.py

Based on the dnspython upstream commits
1. https://github.com/rthalley/dnspython/commit/f66e25b Upstream PR: https://github.com/rthalley/dnspython/pull/1044
2. https://github.com/rthalley/dnspython/commit/0ea5ad0 Upstream PR: https://github.com/rthalley/dnspython/pull/1054

[ext-py][dnspython] Fix Tudoor DoS issue (CVE-2023-29483)

---

desktop/core/base_requirements.txt

Pin krb5 to 0.5.1 for SLES12
```
18:09:59 2024/07/23 01:09:59 INFO    :   Building wheel for krb5 (pyproject.toml): started
18:10:17 2024/07/23 01:10:17 INFO    :   Building wheel for krb5 (pyproject.toml): finished with status 'error'
18:10:17 2024/07/23 01:10:17 INFO    :   error: subprocess-exited-with-error
18:10:17 2024/07/23 01:10:17 INFO    : 
18:10:17 2024/07/23 01:10:17 INFO    :   × Building wheel for krb5 (pyproject.toml) did not run successfully.
18:10:17 2024/07/23 01:10:17 INFO    :   │ exit code: 1
18:10:17 2024/07/23 01:10:17 INFO    :   ╰─> [107 lines of output]
18:10:17 2024/07/23 01:10:17 INFO    :       Using krb5-config at 'krb5-config'
18:10:17 2024/07/23 01:10:17 INFO    :       Using libkrb5.so as Kerberos module for platform checks
18:10:17 2024/07/23 01:10:17 …
```

[lib] Pin krb5 to 0.5.1 for SLES12

---

.github/workflows/commitflow-py3.yml

- Earlier, the node version in ubuntu was defaulting to v18 even after explicitly installing node v20.
- Using the dedication action simplifies it and makes sure node v20 is correctly installed.
- By validating all checks are passing and checking node version in py3 CI logs

[ci] Setup node v20 correctly for py3 checks

---

desktop/core/base_requirements.txt
desktop/core/requirements.txt

- Upgrading the libraries to support the python 3.11.
- slack-sdk 3.2.0 -> 3.31.0
- pandas 1.4.2 -> 2.0.3
- numpy 1.23.1 ->1.24.4
- Locally
- CI

[Python3.11] Upgrade libs to support python3.11 with backward compatibility

---

desktop/core/src/desktop/lib/conf_test.py

- Global flags should be at the start of the expression
- It was warning from python3.6 but from the python3.11 it's en error
- https://bugs.python.org/issue47066
- Locally
- CI

[Python3.11] Improve the regex expression

---

desktop/core/src/desktop/templates/document_browser.mako

This reverts a previous commit (b903bd7) which was done to favour the top search, however the top search does not contain all the actions a user would want to do after finding a specific document, making it very cumbersome, and in some cases impossible, to achieve that.
Manually tested (and thoroughly tested in the past)

[ui-core] Add the inline documents search back in the documents page

---

desktop/core/src/desktop/js/ko/components/assist/ko.assistDocumentsPanel.js
desktop/core/src/desktop/templates/document_browser.mako

This adds the copy action for Hue documents to the right-click context menu in the left assist panel and the documents page.

[ui-core] Add the copy action to the context menu on the documents page and left assist

---

desktop/core/base_requirements.txt

Upgrade celery to 5.4.0 and django-celery-beat to 2.6.0
bug blitz

[core] Bump up celery to 5.4.0 and django-celery-beat to 2.6.0

---

tools/virtual-bootstrap/virtual-bootstrap.py

Change-Id: I0e592cf65b46d3b7775a4e3114b55a4c18d93e9a
- Remove libexpat.dll from  windows OS's virtual env directory due to an integer overflow in the doProlog function of Expat library (aka libexpat) [CVE-2022-23990](https://nvd.nist.gov/vuln/detail/CVE-2022-23990 ). Addition of this file is under a windows virtual env installation which we don't support now. 
- Created builds and tested on docker and base deployments.

[CVE] Remove libexpat from  windows OS's virtual env directory

---

apps/filebrowser/src/filebrowser/api.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py
desktop/core/src/desktop/lib/fs/proxyfs.py

- There was no API for getting trash path per user.
- Earlier, we were depending on a redirect from backend to the trash path but now having a dedicated API for trash path makes sense for revamping the filebrowser UX.
- This API is mainly for HDFS for now because other supported filesystems dont have a clear trash use-case concept in Hue.
- Manually

[api] Add /get_trash_path public API

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/tests.py
desktop/libs/notebook/src/notebook/api_tests.py
desktop/libs/notebook/src/notebook/conf.py

- This change ensures that if a user needs an interpreter X, then user needs to add its config under `[[interpreters]]` section. This way Hue won't be showing all unneeded interpreters and confuse users whenever any app is whitelisted.
- If user still wants to add all default available interpreters for every whitelisted app (old scenario), then they can set the flag `enable_all_interpreters` to `True` in the Hue configs.
- Manually tested different scenarios of Hue config and verified the editors available on the Hue UI.
- Added new unit tests and updated existing ones.

[interpreters] Skip adding all available editors by default for every whitelisted app

---

desktop/core/src/desktop/js/reactComponents/TaskBrowser/TaskBrowser.tsx

Removing the import and usage of act in TaskBrowser.jsx. Since "@testing-library/react" was upgraded,the webpack Tree Shaking would normally remove unused dependencies and "@testing-library/react" is only used in test files which are not part of the build. So using "@testing-library/react" in TaskBrowser.jsx crashes the build. 
Tested on Mac, created builds and tested it. 

Removing the import and usage of act in TaskBrowser.tsx

---

desktop/core/src/desktop/js/apps/admin/Metrics/Metrics.scss
desktop/core/src/desktop/js/apps/admin/Metrics/Metrics.test.tsx
desktop/core/src/desktop/js/apps/admin/Metrics/Metrics.tsx
desktop/core/src/desktop/js/apps/admin/Metrics/MetricsTable.tsx

Metrics page wasn't exactly synced with Cloudera design. This PR ensures consistency of the metrics page. Mainly exchanging the positions of dropDown and filter & getting the headings (captions) of each small table within the table (leading to make changes in the test as well) with some changed style of the headings.
The Metrics page is now with sync in Cloudera design. UseMemo has been introduced in the code to be able to cache the result of a function, so that it can be returned again without re-computation.
PR has some basic updations in the metrics code to make it more readable and trying to use the best coding practices.
Original PR of updating metrics: https://github.com/cloudera/hue/pull/3707
Additional metrics PR: https://github.com/cloudera/hue/pull/3761
Sanity check of the …

[ui-metrics-cuix] Updating metrics to sync with Cloudera design

---

apps/beeswax/src/beeswax/server/dbms.py

-  update port number and Kerberos principle after switching to new active endpoint
-  sort the hs2 endpoints by Zookeeper sequence number so that recovered endpoint with new sequence number at the end
-  update cache logic 

[hive] Fix config issue in HS2 ZK discovery

---

desktop/core/base_requirements.txt

- Markdown 3.1 to 3.7 (supporting Py3.8, Py3.9, Py3.10, Py3.11)
- https://pypi.org/project/Markdown/
- Locally
- Redhat8-Arm64

[core] Upgrade markdown package from 3.1 to 3.7

---

apps/oozie/src/oozie/management/commands/share_all_workflows.py

- Refactoring the oozie workflow sharing command to support Py3 syntax. Earlier it was failing with the following error:
```
File "/lib/hue/apps/oozie/src/oozie/management/commands/share_all_workflows.py", line 50
except AttributeError, e:
^
SyntaxError: invalid syntax
```
- Refactoring also includes code formatting and changing `LOG.warn()` to `LOG.warning()`

[oozie] Upgrade workflow sharing command to support Py3

---

desktop/core/src/desktop/js/utils/hooks/useLoadData.test.tsx
desktop/core/src/desktop/js/utils/hooks/useLoadData.ts

- Add the onSuccess and onError callback for useLoadData hook. The callback can be used to trigger any dependant action including sequential API call.
- Added the unit test to test the calling of the respective callback.

[ui-core]: add onSuccess and onError callback for useLoadData hook

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/lib/conf.py

- This change is already present downstream.
- Add a `secret` parameter and hide all the config values which this parameter is `True` in the response sent to the UI.
- Manually

[core][config] Hide config values having secret attribute as True

---

desktop/core/base_requirements.txt
desktop/libs/notebook/src/notebook/connectors/trino.py
desktop/libs/notebook/src/notebook/connectors/trino_tests.py

- Table/database names starting with digit were giving syntax error.
- Added the double quotes for catalog, database and tables
- Locally

[Trino] Table/database names starting with digit should inclosed with double quotes

---

apps/beeswax/src/beeswax/common.py
apps/beeswax/src/beeswax/conf.py
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/management/commands/sync_warehouses.py
desktop/core/src/desktop/models.py
desktop/libs/notebook/src/notebook/api.py
desktop/libs/notebook/src/notebook/conf.py
desktop/libs/notebook/src/notebook/connectors/base.py
desktop/libs/notebook/src/notebook/connectors/trino.py

With this change, trino compute can be discovered, saved to db and used similar to hive and impala.

[trino][compute] Add compute support for Trino

---

apps/useradmin/src/useradmin/metrics.py
desktop/core/src/desktop/metrics.py

Lost connection happens in Django when using multiprocessing or other parallel execution methods. It often occurs because MySQL connections are not shared safely between processes or threads, leading to disconnections or dropped connections during execution. Metrics use multiprocessing when we started Gunicorn server.
Manually tested on DC cluster

[metrics] Fix lost connection when metrics query database

---

desktop/core/src/desktop/js/sql/sqlUtils.ts

- Modified the code for Trino editor to use double quotes (") instead of backticks (`) when dragging and dropping a table from the left assist into the editor, as Trino does not support backticks for identifiers. This change ensures that table suggestions in the editor are correctly formatted and compatible with Trino syntax.
- Locally

[Trino] Update drag and drop suggestions to use double quotes instead of backticks

---

desktop/libs/indexer/src/indexer/templates/importer.mako

- Adding a compute selection in the import destination step so that user can selected the compute from available compute to import the data
- Tested manually for the .mako code

[ui-importer] adds compute selection in importer destination

---

desktop/core/ext-py3/boto-2.49.0/boto/utils.py

- Support WRITE operations for AWS S3 + RAZ in FIPS mode.
- E2E testing in live setup (both FIPS and non-FIPS)

[raz][fips] Set usedforsecurity=False for MD5 hash to support FIPS mode

---

desktop/core/src/desktop/js/utils/hooks/useSaveData.test.tsx
desktop/core/src/desktop/js/utils/hooks/useSaveData.ts

- Add useSaveData hook for react to save the data to the backend. This is similar to useLoadData hook implemented for fetching data.
```
const { loading: isSaving, save } = useSaveData(API_URL, {
onSuccess: () => {
setIsEditing(false);
}
});
const handleSave = () =>
save({
path: fileData.path
});
```

[ui-core] add useSaveData hook for api calls

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/FileChooserModal/FileChooserModal.tsx
desktop/core/src/desktop/js/utils/hooks/useLoadData.test.tsx
desktop/core/src/desktop/js/utils/hooks/useLoadData.ts

- This PR removes the urlPrefix option from useLoad Data hook
- Updated the unit test

[ui-core] remove urlPrefix option from useLoadData hook

---

desktop/libs/notebook/src/notebook/connectors/trino.py
desktop/libs/notebook/src/notebook/connectors/trino_tests.py

- Add a flag to distinguish between the database and table/column name
- Since we are formatting the identifier, we want to ensure that table or column names with special characters are not broken.
- Locally

[Trino] Add a flag to distinguish between the database and table/column name

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/forms.py
apps/filebrowser/src/filebrowser/views.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py
desktop/core/src/desktop/settings.py
desktop/core/src/desktop/templates/global_js_constants.mako
desktop/libs/aws/src/aws/s3/s3fs.py

- Clean all filebrowser APIs with improved logic as separate methods serving public APIs
- Currently /upload, /extract, /compress APIs are not refactored -- that will be done in future PR.
- Will add unit tests in future PR.
- Manually

[api] Refactor old filebrowser methods to new public APIs

---

.github/workflows/commitflow-py3.yml
.gitignore
desktop/core/base_requirements.txt
pyproject.toml

- Generate an HTML report for both GitHub Actions and local runs. 
- GitHub Action: If any tests fail, users can download the artifact from the uploaded pytest report in GitHub Actions to view the test results in a more readable format.
- Local Run: Users can simply open the report.html file in any browser to view the test results.
- Disable warning summary for better visibility of test results.
- Display test output using counts instead of percentages.
- Locally
- Github action

[Pytest] Generate HTML report for test results and disable warnings

---

apps/filebrowser/src/filebrowser/views.py
apps/filebrowser/src/filebrowser/views_test.py
desktop/core/base_requirements.txt

- Fix support for reading the parquet files in filebrowser
- Using Pyarrow for reading the parquet files
- Locally
- Unittest

[Filebrowser] Fix support for reading Parquet files

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py
apps/filebrowser/src/filebrowser/conf.py
desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/api2.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/lib/fs/gc/gs.py
desktop/core/src/desktop/lib/fs/gc/upload.py
desktop/core/src/desktop/lib/fs/ozone/ofs.py
desktop/core/src/desktop/lib/fs/ozone/upload.py
desktop/core/src/desktop/lib/fs/proxyfs.py
desktop/core/src/desktop/settings.py
desktop/libs/aws/src/aws/s3/s3fs.py
desktop/libs/aws/src/aws/s3/upload.py
desktop/libs/azure/src/azure/abfs/abfs.py
desktop/libs/azure/src/azure/abfs/upload.py
desktop/libs/hadoop/src/hadoop/fs/upload.py
desktop/libs/hadoop/src/hadoop/fs/webhdfs.py

- The original file upload implementation is super old and directly uploads the file by checking the available upload handlers set in `settings.py` when the request reaches the first middleware.
- This flow did not follow the current Hue filebrowser design of routing the FS calls via ProxyFS. 
- The design also had historical flaws of uploading the file even if request was meant for other file operation (if you send a file with /copy call, it will still upload the file and then try doing the copy operation).
- There was no flexibility for upload pre-checks and error handling. Most of such stuff was shifted post file upload.
<br>
- The new implementation helps in solving all the above problem along with cleaner code, improved design, upload on-demand, greater control and performance …

[api] Improve normal file upload design for public APIs

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py

- We need to prevent users to rename files to restricted file types. This is to counter the scenario where user uploads a file with different type then renames it to a different type for malicious intent. 
- Although we are not restricting when the source file type is already restricted and then user is renaming to same file type because we don't know how the file is present in the first place in the filesystem as Hue will not allow normal upload of restricted file type.
- Manually
- Adding new unit tests

[api] Prevent renaming files to restricted file types

---

desktop/core/src/desktop/lib/fs/gc/upload.py
desktop/core/src/desktop/lib/fs/ozone/upload.py
desktop/libs/aws/src/aws/s3/upload.py
desktop/libs/azure/src/azure/abfs/upload.py
desktop/libs/hadoop/src/hadoop/fs/upload.py

- Add check for preventing upload operation for files having restrictive file extensions in old upload handlers also.
- Manually

[fb] Stop file uploads with restrictive file types for old upload handlers

---

apps/filebrowser/src/filebrowser/api_test.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_tests.py
desktop/core/src/desktop/api_public_urls_v1.py
desktop/core/src/desktop/log/api.py
desktop/core/src/desktop/log/api_test.py

- Current log methods in Hue are super old and returning server-side mako based view responses.
- This refactoring helps in improving the core logic and present it as a public API.
<br>
- This will also help the ongoing revamp of Hue server logs page to consume the new APIs. Once the new server logs page is ready, we can cleanup all related old code.
- Manually
- Unit tests

[logs] Refactor old Hue logs views into new public APIs

---

tools/cloudera/build_hue_common.sh
tools/container/hue/Dockerfile

- Psycopg2-binary comes pre-packaged with a openssl version that is not compatible with the FIPS requirements. So, removing the psycopg2-binary package and installing psycopg2 & its necessary dependencies. 
- Manual tests on Rhel-8,9 , Centos, Ubuntu, Sles12,15

Remove psycopg2-binary due to FIPS restrictions

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py

- Add an overwrite option for the file upload if the file already exists with same name at the destination path. 
- By default this option is `False`.
- Manually
- Unit tests

[api] Add overwrite option for /upload API when file already exists

---

desktop/core/src/desktop/js/utils/hooks/useQueueProcessor.test.tsx
desktop/core/src/desktop/js/utils/hooks/useQueueProcessor.ts

- This hook manages the list of async task that need to be processed in controlled way. 

[ui-core] adds useQueueProcessor hook to manage concurrent async task

---

tools/cloudera/build_hue_common.sh

Psycopg2-binary comes pre-packaged with a openssl version that is not compatible with the FIPS requirements. So, removing the psycopg2-binary package and installing psycopg2 & its necessary dependencies.
Adding psycopg2 installation for all os'es
- Manual tests on Rhel-8,9 , Centos, Ubuntu, Sles12,15.

Install psycopg2 for all os

---

desktop/core/base_requirements.txt

(cherry picked from commit 5781f39d313cf7391f49dc59b91d87d91b94e2c1)

[backend] Remove lockfile python package due to EOL

---

apps/filebrowser/src/filebrowser/views.py

- Makes an early return of the new storage browser mako file when the `ENABLE_NEW_STORAGE_BROWSER` flag is set as true
- manually tested

[api] optimise new storage browser rendering

---

desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py

- This endpoint is not required now because we have introduced `/stats`, `/display`, `/list` public API endpoints.
- Manually

[api] Remove old storage/view public API endpoint

---

desktop/libs/notebook/src/notebook/connectors/trino.py
desktop/libs/notebook/src/notebook/connectors/trino_tests.py

- Logs errors for failed catalog queries and continues processing other catalogs without interruption.
- Unit test
- Manually

[Trino] Ensures uninterrupted schema listing even if a catalog query fails

---

desktop/core/src/desktop/js/apps/storageBrowser/InputModal/InputModal.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/InputModal/InputModal.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/CreateAndUploadAction/CreateAndUploadAction.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/CreateAndUploadAction/CreateAndUploadAction.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/CreateAndUploadAction/CreateAndUploadAction.tsx

- When API calls are in progress, the buttons of modal need to be disabled to indicate the progress.
- Updated the test cases

[ui-storagebrowser] adds disable button to InputModal component

---

apps/useradmin/src/useradmin/metrics.py
desktop/core/src/desktop/metrics.py

Stacktrace:
[20/Dec/2024 08:23:00 -0500] metrics      ERROR    Could not get active_users
File "/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p1015.59425156/lib/hue/build/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p1015.59425156/lib/hue/build/env/lib/python3.8/site-packages/django/db/backends/oracle/base.py", line 521, in execute
self._guess_input_sizes([params])
File "/opt/cloudera/parcels/CDH-7.1.9-1.cdh7.1.9.p1015.59425156/lib/hue/build/env/lib/python3.8/site-packages/django/db/backends/oracle/base.py", line 467, in _guess_input_sizes
self.setinputsizes(**sizes)
cx_Oracle.DatabaseError: DPI-1010: not connected
The above …

Fix Metrics for Oracle DPI errors

---

desktop/core/src/desktop/templates/job_browser_common.mako

Stacktrace seen:
[07/Jan/2025 09:31:26 -0800] access       ERROR     admin - "POST /desktop/log_js_error HTTP/1.1" --- JS ERROR: {"msg":"Uncaught TypeError: lodash__WEBPACK_IMPORTED_MODULE_1___default.a.trimRight is not a function","url":"https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/hue-bundle-651ca10da11cbc8f75e8.2537e7eff7ba.js","line":74060,"column":139,"stack":"TypeError: lodash__WEBPACK_IMPORTED_MODULE_1___default.a.trimRight is not a function\n    at app (https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/hue-bundle-651ca10da11cbc8f75e8.2537e7eff7ba.js:74060:139)\n    at https://ccycloud-1.ni-717x-yq.root.comops.site:8889/static/desktop/js/bundles/hue/vendors~hue-chunk-651ca10da11cbc8f75e8.04f0b70fc23d.js:83803:52\n …

Fix JB Oozie Log Icon

---

apps/filebrowser/src/filebrowser/api.py

- Remove unused compression field from /display API
- Manually

[api] Remove unused compression field from /display API

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryPage.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryPage.tsx
desktop/core/src/desktop/js/utils/constants/storageBrowser.ts

- When the files are queued for upload, currently we refresh the UI once all the files are uploaded, this becomes painful when the list of files that are queued is long.
- To Give user the sense of upload success (Similar to file upload in Google Drive and other file browser), The short silent pooling is introduced, this refetches the list of files and folders in the background and updates the list with new files that got uploaded successfully. 

[ui-storagebrowser] Adds silent polling for list_dir during file upload

---

desktop/libs/libsaml/src/libsaml/backend.py

* added nonce to the script tag as inline js is not supported anymore, and saml logout is failing

inline js in the saml logout page

---

desktop/core/src/desktop/static/desktop/js/file-display-inline.js

As part of removing csp with inline javascript, a filename was hardcoded by mistake, this has been fixed
[file-display-inline.js#67](https://github.com/cloudera/hue/pull/3923/files#diff-f7ca5d7f137c38ed478b2912804d5dd191ada020a4962280b07922a974238d7dR67) instead has an hardcoded /user/admin/ai_case.txt path used
Fixes: https://github.com/cloudera/hue/issues/3956
- This has been tested manually

replace the hardcoded filename with correct filename

---

apps/filebrowser/src/filebrowser/api.py
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryPage.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageFilePage/StorageFilePage.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageFilePage/StorageFilePage.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/api.ts
desktop/core/src/desktop/js/reactComponents/FileChooser/types.ts
desktop/core/src/desktop/js/reactComponents/Pagination/Pagination.scss
desktop/core/src/desktop/js/reactComponents/Pagination/Pagination.tsx
desktop/core/src/desktop/js/utils/constants/storageBrowser.ts

- When the file is big, the preview need to be paginated.

[ui-storagebrowser] adds pagination in file preview page

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/StorageBrowserActions.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/StorageBrowserActions.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/StorageBrowserActions.util.ts

- Adds the download action for the storage browser

[ui-storagebrowser] adds download action

---

desktop/core/ext-py3/djangosaml2-0.18.0/djangosaml2/views.py
desktop/core/src/desktop/templates/djangosaml2/post_binding_form.html

* pysaml by default gives a template which has unsafe inline code. django saml bypasses that if we use a custom template. i have defined that custom template and added a request object.
* Uses the post binding form to add nonce, if the nonce is available in the request. if csp_nonce is disabled in the setting it won't be added here. 
- created a image replaced it in mow-dev to test the image. it was working with both csp enabled and disabled

[security] SAML login issues with csp enabled

---

desktop/core/src/desktop/static/desktop/js/listdir-inline.js

- Fixing the toaster message display on the old storage browser.
- manually tested

[ui-storagebrowser] fix the translation strings

---

apps/filebrowser/src/filebrowser/api.py
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/ChangeOwnerAndGroupModal/ChangeOwnerAndGroupModal.scss
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/ChangeOwnerAndGroupModal/ChangeOwnerAndGroupModal.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/ChangeOwnerAndGroupModal/ChangeOwnerAndGroupModal.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/StorageBrowserActions.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/StorageBrowserActions.util.ts
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryPage.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/api.ts

- for the file and folder in new storage browser, this action will allow super user to change the owners

[ui-storagebrowser] adds change owner and group action

---

desktop/core/src/desktop/static/desktop/js/file-display-inline.js
desktop/core/src/desktop/static/desktop/js/task-browser-inline.js
desktop/core/src/desktop/templates/taskserver_list_tasks.mako

**Issue**: Inline scripts from AJAX responses aren't executed due to CSP restrictions when unsafe-inline is removed.
**Fix**: Manually process and append scripts from AJAX responses to ensure execution.
- tested in local

[security] Fix AJAX Loading of Inline Scripts in editFile

---

apps/filebrowser/src/filebrowser/urls.py
apps/filebrowser/src/filebrowser/views.py
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserTab/StorageBrowserTab.tsx
desktop/core/src/desktop/js/apps/storageBrowser/app.js
desktop/core/src/desktop/js/components/sidebar/HueSidebar.vue
desktop/core/src/desktop/js/onePageViewModel.js
desktop/core/src/desktop/models.py
desktop/core/src/desktop/templates/global_js_constants.mako
desktop/core/src/desktop/templates/hue.mako

- The New Storage Browser is now moved to a new frontend url, this eliminates the various issues caused in old file browser. 
- When `enable_new_sotrage_browser` flag is enabled, user will see only the new file browser in the sidebar but can access the old file browser via old url
- When `enable_new_sotrage_browser` flag is disabled, user will see only old file browser in the sidebar but can access  the new file browser via new url

[ui-storagebrowser] moves the new storage browser to new endpoint 

---

desktop/core/src/desktop/js/ko/components/ko.contextSelector.js
desktop/core/src/desktop/static/desktop/locales/en/translation.json
desktop/core/src/desktop/templates/global_js_constants.mako

- Replaces the label for database selection

[ui-editor] changes the Active database label to database

---

desktop/core/src/desktop/management/commands/sync_warehouses.py

This commit fixes a bug where impala queries were not going with the doas param resulting in all queries running with system user credentials.

[computes] fixed impala impersonation flag

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py
desktop/core/src/desktop/lib/fs/ozone/ofs.py
desktop/libs/hadoop/src/hadoop/conf.py

- Removed extra response fields from the /list API and included them in /filesystems API only for HDFS. This way we can use the configs only when HDFS is configured and it will not clutter the response for /list for all filesystems.
<br>
- Trash is also configurable now to make it easier to enable and test locally. Although it is recommended we read the values from `core-site.xml` in the prod deployments so be at better sync with the running HDFS service. Because of this reason, I've not added the config explicitly in the `.ini` files and also we are dynamically defaulting always to the `core-site.xml` value.
- Manually
- Unit tests

[api] Refactor /filesystems API and include extra HDFS configs in its response

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py

- Add extra validation checks for the /mkdir API and make sure it returns an error when someone tries to create two directories with same name.
- Manually
- Unit tests

[api] Refactor /mkdir API with better validation checks

---

.circleci/config.yml
.github/workflows/commitflow-py3.yml
Makefile
Makefile.vars
desktop/core/base_requirements.txt
desktop/core/test_requirements.txt

…t_prep`
Separate test required package in different build target
Manual

[test] Move pytest and its dependencies from `make apps` to `make test_prep`

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py
apps/filebrowser/src/filebrowser/conf.py

- Fixes the issue where rename fails when the config is not set and files with no extensions were not allowed to rename in **new storage browser**.
- It also fixes upload operation for **both new storage browser and old filebrowser** where uploads of file with no extensions were failing when the config was not set.
- Manually
- Unit tests

[api] Change RESTRICT_FILE_EXTENSIONS config's default value and fix restricted types handling in /rename API

---

apps/filebrowser/src/filebrowser/api.py

- Error handling was broken for 500 code JsonResponse objects for the bulk operations. This PR fixes it and improves the error response structure a bit.
- More improvement will be part of Error UX roadmap item.
- Manually

[api] Fix error handling in bulk operations

---

apps/filebrowser/src/filebrowser/api.py

- This changes fixes the filename issue when downloading the file from new storage browser. Now the file gets downloaded with correct filename instead of _`"download"."extension"`_ such as download.csv, download.txt etc.
- Manually

[api] Improve content disposition handling in /download API

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py

- Add extra validation checks for the /move API to catch edge case scenarios and improve error handling.
- Manually
- Unit tests

[api] Refactor /move API with additional validation checks

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py

- Add extra validation checks for the /copy API to catch edge case scenarios and improve error handling.
- Manually
- Unit tests

[api] Refactor /copy API with additional validation checks

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserTab/StorageBrowserTab.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageBrowserActions/StorageBrowserActions.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryPage.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/FileChooserModal/FileChooserModal.tsx
desktop/core/src/desktop/js/reactComponents/FileChooser/api.ts
desktop/core/src/desktop/js/reactComponents/FileChooser/types.ts

- The config of file system has been moved from `/list_dir` API to `/filesystem` API.

[ui-storagebrowser] moves the HDFS config to /fileSystem API

---

desktop/libs/azure/src/azure/abfs/abfs.py

- Add try/except block to correctly catch ABFS exceptions and then handle the 404 case explicitly to determine if the path exists or not.
- Manually

[abfs] Fix isdir and isfile methods to handle exceptions better

---

desktop/core/src/desktop/js/apps/notebook/NotebookViewModel.js

- When presentation mode is enabled, the selected compute was not getting passed to the Snippet class.

[ui-editor] fixes compute selection in presentation mode

---

apps/beeswax/src/beeswax/api.py
apps/beeswax/src/beeswax/server/hive_server2_lib.py
apps/beeswax/src/beeswax/views.py
desktop/libs/notebook/src/notebook/connectors/hive_metastore.py
desktop/libs/notebook/src/notebook/connectors/hiveserver2.py
desktop/libs/notebook/src/notebook/connectors/rdbms.py
desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py

- Impala changed the invalid query handle exception alerts content.
- HUE didn't capture the 'Invalid or unknown query handle' exception from Impala side. It was 'Invalid query handle' from long time.
- We are now also checking for the new exception message to be at par with all versions.
- Manually

[core] Check for new query handle exception message for handling expired queries better in query history

---

.github/workflows/commitflow-py3.yml
desktop/core/test_requirements.txt

- To get an idea of initial unfiltered (meaning nothing excluded) numbers and see the flow for coverage and pytest and what format it supports both on local setup and Github Action.
-  Then we can plan the next steps to refine the numbers and improve code coverage reporting in Hue.
- Github Actions CI check
- Manually

[ci] Add code coverage report generation to CI workflow

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/api2_tests.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py

- Previously, each app had its own /install_example private API which installed example data/tables.
- Now with this PR change, I've added new public API which can install examples data/tables for supported apps. This will eliminate the need to use the old per app /install_example APIs + its a flexible public API which reduces old dead code.
- Manually
- Unit tests

[api] Add new API endpoint to install app examples with suitable setup functions

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/api2_tests.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py

- Port the old /check_config API to new public API and also remove all mako relate code.
- Manually
- Unit test

[api] Add new check_config API endpoint to validate Hue configuration

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/api2_tests.py

- Change field name as per this PR comment: https://github.com/cloudera/hue/pull/4018#discussion_r1973621488
- Manually
- Unit tests

[api] Rename 'config_error_list' to 'config_errors' in check_config API response

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/api2.py
desktop/core/src/desktop/conf.py

- Add new config for enabling/disabling the New Workflow dropdown in Hue documents page. This is required for scenarios where blanket restriction is done on users for creating new workflows. Users should only have read access for the current workflows.
- Manually

[conf][oozie] Add configuration option to enable or disable workflow creation in Hue documents

---

.coveragerc
.github/workflows/commitflow-py3.yml
.gitignore
pyproject.toml

- Refactor the pyproject.toml file to add coverage configs
- Checking numbers on local setup
- Checking numbers from Github Action checks

[ci][cov] Update coverage configs and streamline report generation

---

desktop/libs/notebook/src/notebook/connectors/flink_sql.py

`default_catalog` and `default_database` parameters make it possible to switch to desired Flink catalog and database automatically after the session is created.
Manual tests.

[flink] Add default_catalog and default_database option

---

desktop/core/src/desktop/js/apps/admin/ServerLogs/ServerLogsTab.scss
desktop/core/src/desktop/js/apps/admin/ServerLogs/ServerLogsTab.test.tsx
desktop/core/src/desktop/js/apps/admin/ServerLogs/ServerLogsTab.tsx

- Improve formatting of admin server log to match old style and functionality
Wrapping (and white space preserve):
No wrapping (and repeated whitespace removed):
- manual testing
- updated unit test

[ui-admin] Improve server log formatting

---

.github/workflows/pr-comments.yml

- Change pull request event so that PRs from forks can also trigger the action comments on Hue PRs
- Running checks on PR Github Actions

[ci] Update PR comments workflow to use pull_request_target event and adjust permissions

---

apps/beeswax/src/beeswax/common.py
desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

A null check for session that are already gone.
While creating new sessions, the compute name and id information comes in different ways in different api's. This change attempts to load compute object if a type or dialect is also available.

[compute] fixes for session close and recreate

---

desktop/core/src/desktop/js/components/sidebar/HueSidebar.vue
desktop/core/src/desktop/templates/global_js_constants.mako

- Disable the log out button if the authentication is handled by Knox
I didn't find enough info in the config API so I had to rely on the URL variables. 
@amitsrivastava can you verify that it is safe to depend on the global js variables like this and that the condition is complete? 
- manual testing by accessing different deployments using Knox or none to establish the condition used to set the ALLOW_HUE_LOGOUT flag. 
- Manually setting ALLOW_HUE_LOGOUT to true or false to verify that the logout button shows/disappears in the left bar both for expanded and collapsed.

[ui-admin] disabled log out button for Knox

---

apps/filebrowser/src/filebrowser/templates/listdir.mako

Renaming `schedule upload` button to `upload` when task_server is enabled.

Renaming schedule upload button to upload when task_server is on

---

tools/cloudera/build_hue_common.sh

Fix a issue - move to pip3.9 from pip3.8 for psycoopg2 installation in rhel8 installation. 
Tested on rhel8 system, hue comes up fine. 

Move to pip3.9 from pip3.8 for psycopg2 installation in rhel8

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryPage.tsx
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadQueue.scss
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadQueue.test.tsx
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadQueue.tsx
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadRow/FileUploadRow.scss
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadRow/FileUploadRow.test.tsx
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadRow/FileUploadRow.tsx
desktop/core/src/desktop/js/utils/constants/storageBrowser.ts
desktop/core/src/desktop/js/utils/hooks/useFileUpload/types.ts
desktop/core/src/desktop/js/utils/hooks/useFileUpload/useChunkUpload.ts
desktop/core/src/desktop/js/utils/hooks/useFileUpload/useFileUpload.ts
desktop/core/src/desktop/js/utils/hooks/useFileUpload/useRegularUpload.ts
desktop/core/src/desktop/js/utils/hooks/useFileUpload/util.ts
desktop/core/src/desktop/js/utils/hooks/useFileUpload/utils.ts
desktop/core/src/desktop/js/utils/hooks/useQueueProcessor/useQueueProcessor.test.tsx
desktop/core/src/desktop/js/utils/hooks/useQueueProcessor/useQueueProcessor.ts
desktop/core/src/desktop/js/utils/hooks/useSaveData/useSaveData.ts

- Added a progress bar showing the progress of the file upload for each file
- Refactored useChunkUpload to improve performance.

[ui-storagebrowser] add progressbar in file upload

---

desktop/core/src/desktop/js/jquery/plugins/jquery.filechooser.js

- Added a refresh mechanism (using pooling) similar to the file browser page. Problem was, The uploader modal would refresh automatically once the file is chunked by the browser  but wont wait for the actual upload to complete on the FS. This fix will keep pooling the upload task and refresh once the upload is complete. 
- Manual tests

Importer not auto refreshing for file uploads with task server

---

desktop/core/src/desktop/js/apps/notebook/snippet.js
desktop/core/src/desktop/js/parse/utils.ts

This fix adds a check to avoid
`Uncaught TypeError: Cannot read properties of undefined (reading 'dialect')`
This unchecked attr access in js blocks saved queries from loading.

[compute][ui] old saved queries failing to load

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/api_test.py

This fixes 2 issues:
- Fix file download with names having spacial chars, whitespace, percentage for all filesystems.
- Fix file download for all filenames for HDFS and OFS filesystems as the stats object is buggy from very long time and does not correct set the name field for current path.
- Manually
- Add unit tests for /download API

[api] Improve filename handling in Content-Disposition header for /download API

---

.github/workflows/pr-comments.yml

- This action will now check for changes in test files and comment only if no changes are found.
- It will also prevent repeated comments.
- Examples of test files: *test, _*tests, *.test.*
- Locally

[CI] Improve handling of comments when no test files are present in the commit

---

desktop/core/src/desktop/js/apps/notebook/snippet.js

- when computes are enabled, hive becomes hive-compute. Due to this findEditorConnector was not able to find the appropriate compute.
-  Tested manually

[ui-editor] fixes loading computes in saved query page

---

desktop/libs/libsaml/src/libsaml/backend.py

* [security] fix arguments error for saml logout issue
* Remove the extra arguments . `exception: not enough arguments for format string`

[security] fix arguments error for saml logout issue

---

apps/filebrowser/src/filebrowser/api.py
apps/filebrowser/src/filebrowser/views.py

In django4.1 the size param has been removed. Justification from django looks good.
Removed outdated handling of length parameter to If-Modified-Since header The length parameter is not described in RFC-7232 and it's against HTTP/1.0 and HTTP/1.1 specifications. It was an old and unofficial extension set by some ancient versions of IE.

[django] fixed was_modified_since by removing size param

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/api2_tests.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py

- Return all available apps per admin users for example installation.
- Manually
- Unit tests

[api] Add endpoint to fetch available apps for example installation

---

desktop/core/base_requirements.txt

upgrading setuptools package to 70.0.0 version due to https://nvd.nist.gov/vuln/detail/cve-2024-6345 
Created a build and tested the docker image on CDW. Hue works fine. 

upgrade setuptools package due to CVE-2024-6345

---

.eslintrc.js
desktop/core/src/desktop/js/apps/editor/components/result/reactExample/ReactExample.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageFilePage/StorageFilePage.tsx
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadQueue.test.tsx
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadQueue.tsx
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadRow/FileUploadRow.test.tsx
desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadRow/FileUploadRow.tsx
desktop/core/src/desktop/js/reactComponents/PathBrowser/PathBrowser.tsx
desktop/core/src/desktop/js/reactComponents/TaskServer/TaskServer.scss
desktop/core/src/desktop/js/reactComponents/TaskServer/TaskServer.tsx
package-lock.json
package.json
tools/ci/check_for_js_licenses.js

Improve accessibility by adding eslint-plugin-jsx-a11y to the linter 

[ui-core] adds eslint-plugin-jsx-a11y rule

---

tools/cloudera/build_hue_common.sh

- This PR updates the curl command used for downloading SQLite files to include the `-L` flag, enabling support for HTTP redirects. Without this flag, the command fails to download the actual file, resulting in an empty output.
- Hue builds were failing because of this
- Created builds on Centos, Rhel, Sles, Ubuntu OS'es

fix curl enable support for redirects in file downloads

---

desktop/core/base_requirements.txt
desktop/core/ext-py3/djangosaml2-0.18.0/djangosaml2/urls.py

`django-debug-panel` is dropped as it is no longer supported for django4. If we want something we will need to bring in some other more modern debug panel.

[django] Fix for removal of django.conf.urls.url in Django4

---

tools/scripts/hue.sh
tools/scripts/python/hue_py_shebang.sh
tools/scripts/python/python_helper.sh

1. `tools/scripts/hue.sh` is the wrapper script to call the hue script, that is currently in `build/env/bin/hue` but could be in various locations depending on python version in use.
2. `tools/scripts/python/python_helper.sh` contains helper functions
- `find_latest_python` returns the latest py version (3.11, 3.9, 3.8)
- `latest_venv_bin_path` returns the path to the env/bin of the latest python, relative to the top-level hue directory.
3. `tools/scripts/python/hue_py_shebang.sh` is a helper script that is supposed to be used in the shebang line of python scripts in Hue. I can direct the python script to the correct python to be used.
4. `HUE_PYTHON_VERSION` environment variable can be set to override the automatic selection of latest available python.
- (Please fill in changes proposed …

[multi-python] scripts to simplify the selection of python version

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/api2_tests.py

- Earlier when we were validation the `connector_id`, spark example was not installing because it was always throwing missing param error.
- Now we are directly checking for connector if its available and then going to spark example in the else condition.
- Updated unit tests

[api] Skip connector_id validation in _setup_notebook_examples for spark example to work

---

tools/scripts/python/python_helper.sh

- Added these checks to avoid errors when directories like `build/env/`or `build/venvs `don't exist.
- locally

[multi-python] Improve the helper function

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/api2_tests.py

Wraps connector fetching logic in try-except block to gracefully handle cases where the connector doesn't exist or when queries fail. This prevents the API from sending 500 response when setting up notebook examples with invalid connector IDs.
Adds corresponding test cases to verify both scenarios:
- When connector lookup returns None
- When connector lookup raises an exception
- Updated unit tests

[api] Add error handling for missing connector in notebook setup install_example API

---

tools/scripts/hue.sh
tools/scripts/python/hue_py_shebang.sh
tools/scripts/python/python_helper.sh

There is also some refactoring for easier debugability.

[multi-python] Fixed the kinit path

---

desktop/core/src/desktop/settings.py
desktop/core/src/desktop/urls.py
desktop/libs/hadoop/src/hadoop/fs/upload.py

Import documents in documents tab are failing, when task server is enabled with error 
"  File "/opt/hive/desktop/core/src/desktop/api2.py", line 1027, in import_documents
raise PopupException(_('Failed to import documents, the file does not contain valid JSON.'))".
This was because the document upload handler was using `FineUploaderChunkedUploadHandler` when the `is_chunked_fileuploader_enabled` flag is on. No supporting logic was added to `FineUploaderChunkedUploadHandler` to support document uploads as the main motive of `FineUploaderChunkedUploadHandler` was to support large file uploads. 
So adding a custom upload handler that will delegate the document upload tasks to the `HDFSfileUploadHandler` and rest of the file uploads to `FineUploaderChunkedUploadHandler` when …

documents uploads will use HDFSfileUploadHandler when task_server is on

---

apps/filebrowser/src/filebrowser/api.py

- Instead of displaying raw binary content when file decoding fails, returns a user-friendly error message suggesting file download as an alternative.
- Adds error logging to help diagnose encoding issues in server logs.
- Manually

[api] Improve error handling for non-decodable files in /display filebrowser API

---

Makefile
Makefile.vars
desktop/core/generate_requirements.py
tools/cloudera/build_hue_cloudera.sh
tools/cloudera/build_hue_common.sh

Multi python commits

---

README.md

This PR significantly improves the README.md file with several enhancements:
- Restructured the layout with a cleaner, more modern design
- Added modern shields.io badges with consistent style and updated icons
- Enhanced project description with detailed feature sections
- Improved documentation of key features including File Browser, Job Browser, Table Browser and Table Importer
- Added specific details about supported file systems (HDFS, S3, ABFS, Ozone, GS)
- Reorganized "Getting Started" section with clearer deployment options
- Updated database integration examples to focus on the most relevant engines
- Improved code formatting with proper markdown syntax
- Updated license link to point to local LICENSE.txt
- Added DeepWiki badge for auto-refreshed AI documentation
- Manually

[docs] Modernize and enhance Hue project README

---

.github/workflows/pr-comments.yml
jest.config.js

This pull request includes updates to the `.github/workflows/pr-comments.yml` file to improve workflow organization and modify the Jest coverage report settings.
Workflow organization:
* Renamed the job `tests-and-coverage` to `backend-tests-and-coverage` for better clarity and distinction in workflow naming. (`permissions:` section, [.github/workflows/pr-comments.ymlL12-R12](diffhunk://#diff-e2eeb2f61cd715cd003bcb2d9904a7ef75aceece2b54c5efcb0dfc99b6622f9fL12-R12))
Jest coverage report settings:
* Updated the `coverage-summary-path` from `./reports/jest/coverage-final.json` to `./reports/jest/coverage-summary.json` and changed the `summary-title` from "Jest Coverage Report" to "UI Coverage Report" to align with updated reporting conventions. (`jobs:` section, …

[ui] Add json-sumary as one of the coveragereporter config in jest

---

desktop/core/src/desktop/management/commands/rungunicornserver.py

Apply hue conf dir and user/group config to gunicorn options
Manual test

[core] Apply hue conf dir and user/group config to gunicorn options

---

desktop/libs/aws/src/aws/s3/s3fs.py
desktop/libs/aws/src/aws/s3/s3fs_test.py

- Refactors the recursive deletion logic to efficiently handle deleting large numbers of S3 objects by chunking delete requests according to the S3 API's 1000-key limit.
- Fixes deletion of virtual directories where path like s3a://bucket/child/inner.txt creates a child directory and deleting that was failing before.
- Adds detailed error handling, logging, and validation for invalid URIs and bucket access failures. Enhances robustness when deleting directories and single objects, and clarifies the method's behavior and limitations.
- Tested manually with in non-raz setup
- Tested E2E on a raz enabled live cluster

[s3] Improve S3 recursive delete to handle large directories and virtual directory scenarios

---

apps/about/src/about/api.py
apps/about/src/about/api_tests.py
apps/about/src/about/serializer.py
desktop/core/src/desktop/api_public.py
desktop/core/src/desktop/api_public_urls_v1.py
desktop/core/src/desktop/auth/api_permissions.py

This pull request refactors the usage analytics API by introducing a class-based view, improving serializers, and updating permissions. It also replaces outdated function-based endpoints with a more modern structure and enhances test coverage for the API. 
* Replaced the function-based `get_usage_analytics` and `update_usage_analytics` endpoints with a class-based `UsageAnalyticsAPI` view in `apps/about/src/about/api.py`. The new view handles `GET` and `PUT` requests, uses `IsAdminUser` for permission checks, and integrates the `UsageAnalyticsSerializer` for data validation.
* Added `UsageAnalyticsSerializer` in `apps/about/src/about/serializer.py` to validate and serialize the `collect_usage` field, ensuring proper data handling for the API.
* Introduced `IsAdminUser` permission class in …

[api] Refactor usage analytics API to DRF APIView and update tests

---

docs/docs-site/content/administrator/installation/dependencies/_index.md

- Update the docs
- via hugo serve (manually)

[docs] modernize Apple Silicon instructions, clarify Python 3.11 support, remove Intel Mac references

---

apps/beeswax/src/beeswax/api.py
apps/beeswax/src/beeswax/api_tests.py
apps/beeswax/src/beeswax/conf.py
apps/metastore/src/metastore/conf.py
desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/api2.py
desktop/core/src/desktop/js/catalog/DataCatalogEntry.ts
desktop/core/src/desktop/js/config/types.ts
desktop/core/src/desktop/models.py

This PR introduces a new configuration flag, allow_sample_data_from_views, to control whether Hue attempts to fetch sample data for database views.
Previously, fetching sample data from views was disabled by default due to potential performance concerns with complex or long-running views. This change makes this behavior configurable.
Default value: false (maintains previous behavior)
If set to true, Hue will attempt to fetch sample data for views.
Unit tests have been added for both the Python API endpoint and the TypeScript data catalog logic to verify the flag's functionality under both true and false conditions.
Manually tested with allow_sample_data_from_views both true, false and commented out in desktop/conf/pseudo-distributed.ini
Please review [Hue Contributing …

[metastore] add config flag to fetch sample data for views

---

desktop/core/src/desktop/api2.py
desktop/core/src/desktop/api2_tests.py
desktop/core/src/desktop/models.py

- Enhanced the configuration retrieval in the API to include new flags for sharing and usage collection. This fixes the bug related to `hue_config` present `ClusterConfig` getting overridden.
- Removed redundant configuration entries from the ClusterConfig model.
- Reorganized import statements for consistency and clarity.
- Updated test cases to check for all config fields, improve readability and maintainability, including adjustments to JSON handling and assertions.
- Manually
- Running updated unit tests

[api][conf] Refactor API tests and configuration handling

---

desktop/core/src/desktop/static/desktop/js/listdir-inline.js

- Removed redundant "Error:" keyword in the alert of the old file browser.
current state:
New state:

[ui-filebrowser] remove redundant Error keyword from alert

---

desktop/core/base_requirements.txt
desktop/core/generate_requirements.py
desktop/core/src/desktop/lib/importer/api.py
desktop/core/src/desktop/lib/importer/api_tests.py
desktop/core/src/desktop/lib/importer/operations.py
desktop/core/src/desktop/lib/importer/operations_tests.py
desktop/core/src/desktop/lib/importer/schemas.py
desktop/core/src/desktop/lib/importer/schemas_tests.py
desktop/core/src/desktop/lib/importer/serializers.py
desktop/core/src/desktop/lib/importer/serializers_tests.py

- Added Pydantic schemas for local file uploads, file metadata guessing, file previews, and SQL type mapping to improve data validation and structure.
- Updated the `local_file_upload`, `guess_file_metadata`, `preview_file`, `guess_file_header`, and `get_sql_type_mapping` functions to utilize these schemas, enhancing type safety and clarity.
- Refactored serializers to leverage Pydantic for validation, simplifying the validation logic and improving error handling.
- Included the `pydantic` dependency in requirements for schema validation support.
- Manually
- Running new and existing unit tests

[importer] Integrate Pydantic schemas for file operations and enhance validation

---

apps/beeswax/src/beeswax/models.py
apps/beeswax/src/beeswax/server/hive_server2_lib.py
apps/impala/src/impala/server.py
apps/jobbrowser/src/jobbrowser/apis/query_api.py
desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

Impala uses cookies for maintaining sticky sessions in active-active setup.
With this commit,
1. we extract all the cookies from the response,
2. store the cookies in the properties (json) column of sessions
3. When making a call, we pull the cookies from session and set it in the client.
4. More changes were needed to make sure that session info is flowing all the way to the spot of making the call.

[impala][beeswax] Store cookies for beeswax http transport

---

apps/filebrowser/src/filebrowser/views.py

kt_renewer consistently crashes on first startup in CDH 7.3.1 but works when manually restarted.
Race condition between multiple Hue processes during startup:
1. Process 1 checks `os.path.exists('/tmp/hue_uploads')` → False
2. Process 2 checks `os.path.exists('/tmp/hue_uploads')` → False  
3. Process 1 calls `os.makedirs('/tmp/hue_uploads')` → Success
4. Process 2 calls `os.makedirs('/tmp/hue_uploads')` → FileExistsError
Add `exist_ok=True` parameter to `os.makedirs()` to make directory creation race-condition safe.
Tested on CM-CDH cluster.

Fix kt_renewer startup crash due to directory creation race condition

---

desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

If the frontend sends a request with session that is no longer in the db or malformed, the current `Session.object.get()` throws an error. The change to using `filter().first()` would get the session if found in db or `None` rather than throwing an exception. This would let the query proceed with a new session getting created.

[beeswax] Do not error on invalid session in request

---

desktop/core/src/desktop/lib/importer/api.py
desktop/core/src/desktop/lib/importer/api_tests.py
desktop/core/src/desktop/lib/importer/operations.py
desktop/core/src/desktop/lib/importer/operations_tests.py
docs/docs-site/content/developer/api/rest/_index.md
docs/docs-site/content/developer/api/rest/importer.md

This pull request refactors the `get_sql_type_mapping` API to return a sorted list of unique SQL types supported by a specific SQL dialect, instead of a mapping from Polars data types to SQL types. The changes simplify the API response and improve consistency across dialects. The most important changes include updates to the API implementation, adjustments to tests to reflect the new response format, and updates to documentation to align with the revised behavior.
* Refactored `get_sql_type_mapping` in `desktop/lib/importer/operations.py` to return a sorted list of unique SQL types instead of a mapping dictionary. Introduced a helper function `_get_polars_to_sql_mapping` for internal use. [[1]](diffhunk://#diff-de3428bd573ff885faf6d14a8a3477b38df24b4587493591f3cc0627e4b693afL630-R676) …

[importer] Update SQL type mapping API to return unique SQL types as a sorted list and change its docs section

---

desktop/libs/librdbms/src/librdbms/server/dbms.py
desktop/libs/librdbms/src/librdbms/server/mysql_lib.py
desktop/libs/librdbms/src/librdbms/server/oracle_lib.py
desktop/libs/librdbms/src/librdbms/server/postgresql_lib.py
desktop/libs/librdbms/src/librdbms/server/sqlite_lib.py
desktop/libs/notebook/src/notebook/connectors/base.py
desktop/libs/notebook/src/notebook/connectors/base_tests.py
desktop/libs/notebook/src/notebook/connectors/flink_sql.py
desktop/libs/notebook/src/notebook/connectors/hive_metastore.py
desktop/libs/notebook/src/notebook/connectors/jdbc.py
desktop/libs/notebook/src/notebook/connectors/jdbc_clickhouse.py
desktop/libs/notebook/src/notebook/connectors/jdbc_kyuubi.py
desktop/libs/notebook/src/notebook/connectors/jdbc_teradata.py
desktop/libs/notebook/src/notebook/connectors/jdbc_vertica.py
desktop/libs/notebook/src/notebook/connectors/ksql.py
desktop/libs/notebook/src/notebook/connectors/rdbms.py
desktop/libs/notebook/src/notebook/connectors/solr.py
desktop/libs/notebook/src/notebook/connectors/spark_shell.py
desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
desktop/libs/notebook/src/notebook/connectors/sqlflow.py
desktop/libs/notebook/src/notebook/connectors/trino.py

- Add source code parsing test to validate connector method signatures
- Add base API contract validation to ensure consistent signatures
- Prevent runtime TypeError when adding parameters like 'nested' to get_sample_data()
- Added source code parsing tests to validate that all connector method signatures remain consistent with the base API contract
- Implemented base API contract validation to ensure method signatures across 11+ connectors (Trino, MySQL, PostgreSQL, Oracle, SQLite, Flink SQL, JDBC variants, etc.) stay synchronized
- Added parameter compatibility checks to prevent runtime TypeErrors when new parameters (like 'nested') are added to base API methods
- Unit tests: Added comprehensive source code parsing tests that validate method signatures across all connector …

Add nested param to get_sample_data and API compatibility tests to prevent connector signature mismatches

---

tools/scripts/hue.sh

Updated `run_syncdb_and_migrate_subcommands` function with retry. This is mostly to be resilient to migration processes running concurrently from multiple hosts. django's `migrate` command runs in its own db transaction, so it is safe wrt concurrency, But, it still can cause our startup script to fail. The retry mechanism adds a delay and retry. Any earlier `migrate` commands shouldn't take more than 5 seconds. So, the subsequent `migrate` would either be a no-op or complete the migration.
Please review [Hue Contributing …

[build] Add migration retry logic to hue.sh

---

Makefile

- Remove `--system-site-packages` flag to avoid package conflicts and ensure clean isolated environment for builds
- locally
- canary build

[Core] remove --system-site-packages flag from virtualenv creation

---

desktop/core/src/desktop/js/utils/hooks/useFileUpload/useRegularUpload.test.tsx
desktop/core/src/desktop/js/utils/hooks/useFileUpload/useRegularUpload.ts

- Moving the destination_path from FormData to query param, due to change in the backend API request schema
- Updated unit test

[ui-sb] moves the destination_path from FormData to query param

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryActions/CreateAndUpload/CreateAndUploadAction.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryActions/CreateAndUpload/CreateAndUploadAction.tsx

- Removes redundant modal that pops up when user clicks on Upload File.
- Now, when the user clicks on "Upload File", the file selector opens up directly.
Existing:
https://github.com/user-attachments/assets/8529f67e-9426-43b4-9c1c-38f923ccd61a
Changes in this PR:
https://github.com/user-attachments/assets/756bbdf5-bbff-4547-bdb2-af7ca8d83995
- Updated the unit test

[ui-sb] refactor: removes redundant file upload modal

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryActions/CreateAndUpload/CreateAndUploadAction.test.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageDirectoryPage/StorageDirectoryActions/CreateAndUpload/CreateAndUploadAction.tsx
desktop/core/src/desktop/js/utils/storageBrowserUtils.test.ts
desktop/core/src/desktop/js/utils/storageBrowserUtils.ts

- Create bucket/volume/file systems based on current file path.
- Manually
- Unit tests

[ui-storageBrowser] Add create bucket/volume/filesystem functionality

---

desktop/conf.dist/hue.ini
desktop/conf/pseudo-distributed.ini.tmpl
desktop/core/src/desktop/conf.py
desktop/core/src/desktop/lib/ip_utils.py
desktop/core/src/desktop/lib/ip_utils_test.py
desktop/core/src/desktop/management/commands/rungunicornserver.py

- Introduced enable_ipv6 (default false) to optionally bind Hue on IPv6.
- When enabled, rungunicornserver uses fetch_ipv6_bind_address() to build the bind string:
- Accepts already-bracketed IPv6 ([addr]), validates and appends :port.
- Brackets raw IPv6 literals (addr → [addr]:port).
- For hostnames/IPv4, resolves AAAA and uses [ipv6]:port; if no AAAA/DNS error, falls back to host:port.
- Strips zone identifiers from IPv6 (e.g., %en0) before binding.
- Keeps default behavior unchanged when IPv6 is disabled; --bind still takes precedence.
- Added config docs for enable_ipv6 in hue.ini and pseudo-distributed template.
- Added unit tests for the formatter covering AAAA success, zone-id stripping, and no-AAAA fallback.
Unit tests: Verified IPv6 bind formatting logic (AAAA resolution, …

hue ipv6 changes

---

desktop/core/src/desktop/conf.py
desktop/core/src/desktop/lib/rest/http_client.py
desktop/core/src/desktop/lib/thrift_util.py
desktop/core/src/desktop/lib/tls_utils.py
desktop/core/src/desktop/management/commands/rungunicornserver.py

- Add TLS 1.3 configuration options and enhanced cipher suites
- Implement TLS 1.3 support in Gunicorn server with optimal protocol selection
- Enhance HTTP client with TLS 1.3 support and custom SSL adapters
- Add TLS 1.3 support to Thrift client with graceful fallback
- Include comprehensive TLS 1.3 compliance test suite
- Maintain backward compatibility with TLS 1.2 systems
- Manually on the Hue server.

[security] Implement TLS 1.3 support across Hue components

---

desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage.tsx
desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserTab/StorageBrowserTab.tsx

There was an unintentional double decoding of the URL search params.
1. `URLSearchParams` returns params with the decoded values
2. Decoding again using `decodeURIComponent`
hence, Removed decodeURIComponent

[ui-sb] fix: remove double decoding of url search params

---

desktop/core/src/desktop/settings.py
desktop/libs/libsaml/src/libsaml/backend.py

Problem 1:
`request.csp_nonce` was not getting passed to the djangosaml template. Added request context processor to Django template backend to fix this.
Problem 2:
SAML authentication was causing infinite recursion. Our `update_user` method in `libsaml/backend.py` was not getting called. Renamed `update_user()` to `_update_user()`
Had to add additional checks for the first-time user login.

[django][saml] Fix SAML for Django 4 upgrade
