cloudera/hue

- apps/useradmin/src/useradmin/ldap_access.py
The same sanitization process we do in users we run into in groups so the fix needs to be applied there additionally
> [useradmin] Sanitization process added to groups

- apps/spark/java/README.rst
- apps/spark/java/livy-core/src/main/scala/com/cloudera/hue/livy/spark/SparkSubmitProcessBuilder.scala
- apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/batch/BatchSessionManager.scala
- apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/batch/BatchSessionProcess.scala
- apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/batch/BatchSessionYarn.scala
- apps/spark/java/livy-yarn/src/main/scala/com/cloudera/hue/livy/yarn/Client.scala
* Add numExecutors in POST Batch request;
* Fix problem of https://github.com/cloudera/hue/issues/195
> Add numExecutors and fix files option issue

- docs/sdk/sdk.md
append the 'csrf_token' token to calculator app simple
> append the 'csrf_token' token to calculator app

- README.md
> My AWS Ubuntu 14 was missing libz-dev

- desktop/libs/liboauth/src/liboauth/backend.py
> [desktop] Fix oauth_authentication_time metric decorator typo in liboauth

- tools/docker/hue-base/Dockerfile
there's a missing build dependency
> missing dependency libffi-dev

- apps/beeswax/src/beeswax/locale/ko/LC_MESSAGES/django.po
> Fix korean translation

- apps/beeswax/src/beeswax/locale/ja/LC_MESSAGES/django.po
- apps/impala/src/impala/locale/ja/LC_MESSAGES/django.po
- apps/rdbms/src/rdbms/locale/ja/LC_MESSAGES/django.po
I improved the Japanese translation of SQL editor. (Impala, beeswax, rdbms)
> Improved the Japanese translation of new SQL Editor

- apps/about/src/about/locale/ja/LC_MESSAGES/django.po
- apps/jobbrowser/src/jobbrowser/locale/ja/LC_MESSAGES/django.po
- apps/oozie/src/oozie/locale/ja/LC_MESSAGES/django.po
- desktop/core/src/desktop/locale/ja/LC_MESSAGES/django.po
- desktop/libs/notebook/src/notebook/locale/ja/LC_MESSAGES/django.po
I improved some Japanese translation of notebook editor, etc.
> Improve of Japanese for Hue 3.12

- desktop/libs/hadoop/src/hadoop/fs/webhdfs.py
Re-places the logic accidentally removed by HUE-1212
> HUE-6795 [fb] Fix minor logic error in trash directory creation

- docs/manual.txt
> Corrected an error spelling

- desktop/core/src/desktop/auth/views.py
Fixes https://issues.cloudera.org/browse/HUE-7868
Signed-off-by: Lars Francke <lars.francke@gmail.com>
> HUE-7868: Change successful logins to log at INFO

- desktop/core/ext-py/requests-kerberos-0.6.1/requests_kerberos/kerberos_.py
https://review.cloudera.org/r/12820/
> HUE-8202 [jb] Fix mutual authentication failed with Isilon

- desktop/libs/dashboard/src/dashboard/templates/common_search.mako
https://review.cloudera.org/r/12821/
> HUE-7793 [dashboard] Do not convert dates with non traditional format

- desktop/core/src/desktop/templates/hue.mako
Fixed [core] HUE-8310 Broken template for multiple custom apps
> HUE-8310 Broken template for multiple custom apps

- docs/user-guide/user-guide.md
Minor fixes to user guide for links and one typo.
> User guide fixes

- docs/user-guide/user-guide.md
> Updated user-guide.md - spelling fixes

- tools/docker/README.md
correct the command to copy the hue.ini file.
> correct the command to copy the hue.ini file

- desktop/libs/notebook/src/notebook/connectors/jdbc.py
Addresses https://github.com/cloudera/hue/issues/623
> HUE-8774: [notebook] Implement download for jdbc notebook connector

- desktop/libs/notebook/src/notebook/views.py
Fixes error while export Hive query result as CSV file
> Fixes download() got an unexpected keyword argument 'file_format'

- tools/docker/hue/Dockerfile
#835
https://www.cloudera.com/documentation/enterprise/6/6.2/topics/hue_sec_saml_auth.html
> add saml dependencies  #835

- requirements.txt
> HUE-8862 [ci] Remove currently not used requirement file

- docs/docs-site/content/administrator/installation/dependencies/_index.md
Replaced java8 with adoptopenjdk
> HUE-8891 [doc] Update doc to install java open jdk

- apps/beeswax/src/beeswax/server/dbms.py
- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- docs/admin-manual/manual.md
Will follow with full setup guide.
> Adding LLAP Interpreter to Hue.ini and PseudoDistributed.ini.tmpl

- apps/filebrowser/src/filebrowser/views_test.py
- desktop/core/src/desktop/lib/tasks/compress_files/compress_utils.py
Fixed test cases for compress_hdfs_files
Made more test cases for compress_hdfs_files to be harder to pass
Fixed problem where files cannot be read due to illegal characters in file paths
> Fixed test cases for compress hdfs files and Fixed compress_files utils

- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/libs/notebook/src/notebook/connectors/base.py
- desktop/libs/notebook/src/notebook/connectors/jdbc_vertica.py
This change adds Vertica support as a backend for Hue.
It brings support for the schema browser as well.
> Add Vertica JDBC connector

- apps/filebrowser/src/filebrowser/forms.py
- apps/filebrowser/src/filebrowser/templates/fb_components.mako
- apps/filebrowser/src/filebrowser/templates/listdir.mako
- apps/filebrowser/src/filebrowser/templates/listdir_components.mako
- apps/filebrowser/src/filebrowser/views.py
- apps/filebrowser/src/filebrowser/views_test.py
- desktop/core/src/desktop/js/api/apiHelper.js
- desktop/core/src/desktop/js/jquery/plugins/jquery.filechooser.js
- desktop/core/src/desktop/js/ko/bindings/ko.aceEditor.js
- desktop/core/src/desktop/js/ko/components/assist/assistStorageEntry.js
- desktop/core/src/desktop/js/ko/components/assist/ko.assistPanel.js
- desktop/core/src/desktop/js/ko/components/assist/ko.assistStoragePanel.js
- desktop/core/src/desktop/js/ko/components/ko.sidebar.js
- desktop/core/src/desktop/models.py
- desktop/core/src/desktop/settings.py
- desktop/libs/azure/src/azure/abfs/__init__.py
- desktop/libs/azure/src/azure/abfs/abfs.py
- desktop/libs/azure/src/azure/abfs/abfs_test.py
- desktop/libs/azure/src/azure/abfs/abfsfile.py
- desktop/libs/azure/src/azure/abfs/abfsstats.py
- desktop/libs/azure/src/azure/abfs/upload.py
- desktop/libs/azure/src/azure/client.py
- desktop/libs/hadoop/src/hadoop/fs/test_webhdfs.py
Implements the Azure Lake Storage Version 2 into Hue
Note: Currently has bugs, will edit in future commits
> ABFS in Hue

- docs/docs-site/content/administrator/configuration/editor/_index.md
Adding configuration options for Presto to connect over HTTPS and SSL
> Presto over HTTPS from HUE throws SSL Exception

- desktop/core/src/desktop/js/ko/components/assist/assistStorageEntry.js
- desktop/core/src/desktop/js/ko/components/contextPopover/storageContext.js
- desktop/core/src/desktop/js/sql/autocompleteResults.js
- desktop/libs/azure/src/azure/abfs/__init__.py
- desktop/libs/azure/src/azure/abfs/abfs.py
- desktop/libs/azure/src/azure/abfs/abfs_test.py
- desktop/libs/azure/src/azure/abfs/abfsfile.py
- desktop/libs/azure/src/azure/abfs/abfsstats.py
- desktop/libs/azure/src/azure/abfs/upload.py
- desktop/libs/hadoop/src/hadoop/fs/test_webhdfs.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- desktop/libs/notebook/src/notebook/api.py
The commit is just overall changes to ABFS. This commit combines both autocomplete and ABFSv3 branches.
There will be more changes coming.
> Changes to ABFS

- desktop/core/src/desktop/templates/common_header_footer_components.mako
- desktop/core/src/desktop/templates/common_notebook_ko_components.mako
Manual test with a rich text editor and Excel/Numbers
> [editor] Switch clipboard copy from text to formatted html table

- desktop/core/src/desktop/js/sql/sqlFunctions.js
It seems #991 CI fails because of this.
- https://codepoints.net/U+2013
> Use ascii hyphen instead of EN DASH (U+2013) in date_format desc

- README.md
- desktop/core/src/desktop/js/topNavViewModel.js
>  Fix the URL for "Add more" button . Issue #1006

- apps/spark/src/spark/conf.py
Submitting patch for the issue: [ISSUE-1035](https://github.com/cloudera/hue/issues/1035)
> Set spark use_sasl flag dynamically

- docs/gethue/content/jp/posts/2019-08-14-hue-4-5-and-its-improvements-are-out.md
- docs/gethue/content/jp/posts/2019-12-03-release-hue-4-6.md
- docs/gethue/content/jp/posts/2020-01-28-ten-years-data-querying-ux-evolution.md
- docs/gethue/themes/stack-hue-theme/i18n/jp.toml
- docs/gethue/themes/stack-hue-theme/layouts/partials/home.jp.html
I improved some Japanese themes and localized a couple of blogs into Japanese.
> Localized the blog into Japanese before Jan 2020

- tools/container/hue/Dockerfile
- tools/container/huelb/Dockerfile
- tools/container/huelb/run_httpd.sh
(cherry picked from commit 881062400d9ed189784343014ddcb1ca622a8daf)
> HUE-9163 [core] Enable HUE image to be runnable in OpenShift environment

- tools/kubernetes/helm/hue/templates/deployment-hue.yaml
- tools/kubernetes/helm/hue/values.yaml
which can be used to configure kiam, proemtheus using annotations
> Add podAnnotations section,

- tools/container/base/hue/Dockerfile
- tools/container/base/huelb/Dockerfile
- tools/container/build.sh
- tools/container/compile/hue/Dockerfile
Tested on the internal cluster.
> HUE-9271 [core] Use UBI base images for Hue images

- desktop/libs/notebook/src/notebook/connectors/base.py
> HUE-9273 [notebook] Encoding Error when use non-ascii characters in sql-editor-variables

- CONTRIBUTING.md
Fixed couple of typos and reformulated one phrase
> Grammar improvements in CONTRIBUTING.md

- desktop/libs/liboozie/src/liboozie/submission2.py
related to https://github.com/cloudera/hue/issues/1133.
> [#1133] variables in REMOTE_DEPLOYMENT_DIR are not properly replaced

- apps/metastore/src/metastore/tests.py
> added grant_access to TestApi.test_show_tables

- apps/about/src/about/tests.py
> [about] changed a test case which was broken by past changes of admin_wizard.mako

- apps/beeswax/src/beeswax/tests.py
> TestHive.test_install_examples need to access to beeswax

- apps/filebrowser/src/filebrowser/views_test.py
filebrowser.views_test.TestFileBrowserWithHadoop.test_compress_hdfs_files need to access jobbrowser 
related to #1173
> filebrowser.views_test.TestFileBrowserWithHadoop.test_compress_hdfs_files need to access jobbrowser

- apps/beeswax/src/beeswax/tests.py
> changed assert target stat from numRows to numFiles. (failed with numRows)

- desktop/core/src/desktop/templates/common_share.mako
HUE-9383 potential Script execution in Share Document UI
Manually Tested for script Injection Resolution in Google Chrome, Firefox and Safari
> HUE-9383 potential Script execution in Share Document UI

- apps/useradmin/src/useradmin/templates/layout.mako
HUE-9382 Possible Script Execution on Add/Sync LDAP users (asnaik) Fix
Tested in : Safari , Chrome & Firefox
> HUE-9382 Possible Script Execution on Add/Sync LDAP users (asnaik)

- desktop/core/src/desktop/js/ko/components/contextPopover/documentContext.js
- desktop/core/src/desktop/js/ko/components/contextPopover/partitionContext.js
HUE-9391 Possible Script Execution on Documents Page in Description Field	
Tested manually in Chrome, Firefox & Safari
> HUE-9391 Possible Script Execution on Documents Page in Description Field	

- desktop/core/src/desktop/templates/common_share.mako
Moved to https://github.com/cloudera/hue/pull/1203
> Revert "HUE-9383 potential Script execution in Share Document UI"

- docs/docs-site/content/administrator/administration/reference.md
- docs/docs-site/content/administrator/configuration/server/_index.md
- docs/docs-site/content/administrator/installation/cloud.md
- docs/docs-site/content/developer/api/_index.md
- docs/docs-site/content/developer/connectors/_index.md
- docs/docs-site/content/developer/development/_index.md
- docs/docs-site/content/developer/parsers/_index.md
- docs/docs-site/content/user/querying/_index.md
fixing some typographical errors in https://docs.gethue.com/
> fixing_typographical_errors

- docs/gethue/content/en/posts/2014-07-17-rbtools-example-how-do-easily-do-code-reviews-with-review-board.md
Update the blog  "Hue Development Process - How to do code changes and reviews with Review Board and Git"
> Ci commit master ayush

- docs/docs-site/content/developer/development/_index.md
Adding the documentation of Hue Development Process - How to do code changes and reviews with Review Board and Git
> Adding the documentation of Hue Development Process - How to do code changes and reviews with Review Board and Git

- apps/oozie/src/oozie/importlib/workflows.py
This is the same patch applied in a previous pull request:
https://github.com/cloudera/hue/pull/1266
> [oozie] Fix workflow graph rendering with Python 3 - part 2 (#1262)

- desktop/libs/notebook/src/notebook/connectors/oozie_batch.py
What changes were proposed in this pull request?
HUE-9467 [sqoop] [editor] Hue showing Sqoop command as running even when its finished
How was this patch tested?
Manually Tested for sqoop editor in Hue
> HUE-9467 [sqoop] [editor] Hue showing Sqoop command as running even when its finished

- docs/gethue/content/jp/posts/2020-08-15-automated-checking-python-style-lint-git-commit-messages-continuous-integration.md
- docs/gethue/content/jp/posts/2020-08-19-quick-hue-in-docker.md
- docs/gethue/content/jp/posts/2020-09-14-rest-api-querying.md
- docs/gethue/content/jp/posts/2020-09-15-sql-querying-improvements-phoenix-flink-sparksql-erd.md
- docs/gethue/content/jp/posts/2020-09-23-release-hue-4-8.md
Hi Hue-team,
I cleaned up my repository and created a new pull request.
Please let me know if you find any issues.
Best Regards,
--
Tatsuo
> [blog] localize blog posts into Japanese (Aug, Sep 2020) (#1274)

- docs/gethue/content/jp/posts/2020-09-30-quick-checking-sql-connection-from-kubernetes-pod.md
Hi,
I localized Hue blog post (Kubernetes) into Japanese.
Please let me know if you any issues.
Best Regards,
Tatsuo
> [blog] localized kubernetes blog post  into Japanese 

- docs/docs-site/content/administrator/administration/operations.md
- docs/docs-site/content/administrator/configuration/apps/_index.md
> [docs] Refresh the download restriction properties (#1295)

- tools/docker/hue/Dockerfile
> [docker] Drop install of Phoenix modules as already included (#1299)

- desktop/libs/notebook/src/notebook/decorators.py
```
/notebook/api/check_status
{"status": "expired"}
```
> [sqlalchemy] Support expired query history reload

- desktop/core/src/desktop/js/components/InlineAlert.test.ts
- desktop/core/src/desktop/js/components/InlineAlert.vue
- desktop/core/src/desktop/js/components/__snapshots__/InlineAlert.test.ts.snap
https://issues.cloudera.org/browse/HUE-9509
> HUE-9509 [ui] Create AlertBox component

- desktop/core/ext-py/requests-2.23.0/setup.py
- tools/docker/hue/Dockerfile
> [libs] Comment the chardet dependency in request module config

- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
> [sqlalchemy] Adding explain() to notebook API

- desktop/core/src/desktop/js/apps/notebook2/components/ExecutableActions.vue
- desktop/core/src/desktop/js/components/HueButton.vue
- desktop/core/src/desktop/js/components/__snapshots__/DateRangePicker.test.ts.snap
- desktop/core/src/desktop/js/components/__snapshots__/HueButton.test.ts.snap
- desktop/core/src/desktop/js/components/dropdown/__snapshots__/DropdownMenu.test.ts.snap
- desktop/core/src/desktop/js/components/styles/colors.scss
- desktop/core/src/desktop/js/components/styles/variables.scss
- [frontend] Update the fluid colors to the latest version
- [frontend] Add Fluid styling to the HueButton component
- [editor] Show the stop button in red in editor v2
> [editor] Show the stop button in red in editor v2

- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
e.g. when opening up a blank editor
> [sqlalchemy] Protect against explain on empty statement

- desktop/core/src/desktop/js/apps/tableBrowser/propsMappers.ts
- desktop/core/src/desktop/js/components/er-diagram/comps/literal-entity.vue
- desktop/core/src/desktop/js/components/er-diagram/comps/table-entity.vue
- desktop/core/src/desktop/js/components/er-diagram/index.vue
- desktop/core/src/desktop/js/components/er-diagram/lib/entities.ts
- desktop/core/src/desktop/js/components/er-diagram/lib/interfaces.ts
- Renamed CSS class variable to cssClassName for better readability
- Added custom CSS class support to IRelation
- Improved Type usage in er-diagram/index.vue & tableBrowser/propsMappers.ts
> HUE-9381 [ui] Table ERD - Better CSS class support in entities

- package.json
- webpack.config.npm.js
Publish Hue parsers as vanilla JS files, and move source files into src
> [parser] #1390 Publish Hue parsers as vanilla JS files

- webpack.config.npm.js
package.json created by `npm run webpack-npm` was coming corrupted, this patch is to fix that.
> GH-1390 [parser] Fixed issue with package.json created by webpack-npm

- desktop/core/src/desktop/models.py
[21/Nov/2020 21:51:50 -0800] models       ERROR    Could not load back default app
File "/usr/share/hue/desktop/core/src/desktop/models.py", line 1762, in get_main_quick_action
UserPreferences.objects.get(user=self.user, key='default_app').value
File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/db/models/query.py", line 384, in get
(self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one UserPreferences -- it returned 2!
> [core] User default app preference can have duplicate rows

- apps/jobbrowser/src/jobbrowser/api2.py
- Pass current logged in user name as **x-do-as** header to the proxied endpoint
- Make proxy return better error message when the endpoint is not reachable
> GH-1432 [api] Add doAs header in proxied jobbrowser requests

- desktop/core/src/desktop/js/apps/notebook2/apiUtils.ts
- desktop/core/src/desktop/js/apps/notebook2/components/aceEditor/AceEditor.vue
- desktop/core/src/desktop/js/apps/notebook2/components/aceEditor/AceEditorKoBridge.vue
- desktop/core/src/desktop/js/ext/ace.d.ts
- desktop/core/src/desktop/js/vue/webComponentWrapper.ts
- desktop/libs/notebook/src/notebook/templates/editor_components2.mako
Custom Hue base url tested with the format SQL endpoint and axios. For the remaining APIs I'll see if we'll use jquery ajaxSetup or switch to axios.
> Various AceEditor improvements

- desktop/core/src/desktop/js/apps/notebook2/components/aceEditor/AceEditor.vue
- desktop/core/src/desktop/js/apps/notebook2/components/aceEditor/AceLocationHandler.ts
- desktop/core/src/desktop/js/apps/notebook2/components/aceEditor/QueryEditorWebComponent.ts
- desktop/core/src/desktop/js/apps/notebook2/components/aceEditor/autocomplete/AceAutocomplete.vue
- desktop/core/src/desktop/js/apps/notebook2/components/aceEditor/autocomplete/AutocompleteResults.ts
- desktop/core/src/desktop/js/ext/ace/ext-language_tools.js
- desktop/core/src/desktop/js/ko/components/simpleAceEditor/ko.simpleAceEditor.js
- desktop/core/src/desktop/js/utils/i18n.js
- desktop/core/src/desktop/js/vue/webComponentWrapper.ts
- desktop/core/src/desktop/templates/hue_ace_autocompleter.mako
- tools/ace-editor/lib/ace/autocomplete.js
- tools/ace-editor/lib/ace/ext/language_tools.js
- webpack.config.npm.js
Still have styles left to take care of before it's usable.
> Export the query editor as a web component and various related fixes

- apps/useradmin/src/useradmin/templates/change_password.mako
- apps/useradmin/src/useradmin/views.py
- desktop/core/src/desktop/auth/views.py
HUE-9605 [core] change_default_password config Not working in latest hue versions
Tested the Scenarios 
- when change_default_password is true the change password loads well
-  Change the Password for an newly created user when change_default_password is true (no impact)
-  Change the Password for an newly created user when change_default_password is false ( no impact)
- Admin is able to change his password in profile page ( no impact)
The Fix Works Fine.
the page that is loaded for Mandatory Change password when change_default_password is set as true :
> HUE-9605 [core] change_default_password config Not working in latest hue versions

- desktop/libs/notebook/src/notebook/dashboard_api.py
As require access to self.backticks
> [dashboard] Convert _get_aggregate_function to method

- desktop/libs/notebook/src/notebook/api.py
- desktop/libs/notebook/src/notebook/connectors/base.py
- [core] Small style fix in default app preference API
- [notebook] Standardize fetch_result api to accept a request argument
> [core] Small style fix and making fetch_result standard

- desktop/core/src/desktop/templates/analytics.mako
- desktop/libs/notebook/src/notebook/api_tests.py
- desktop/libs/notebook/src/notebook/models.py
- desktop/libs/notebook/src/notebook/models_tests.py
Moving the tests to the proper corresponding test file
> [stats] Adding monthly dialect execution to the stats

- desktop/core/src/desktop/lib/connectors/types.py
- [connectors] Put better default values for the hostnames
- [hive] Also add Hive via SqlAlchemy connector
- [connector] Harmonize quoting style in all the types
> review romain2

- tools/ci/check_for_website_dead_links.sh
As getting a 400 consistently now
> [ci] Whitelist gethue twitter handle

- tools/ci/check_for_website_dead_links.sh
> [ci] Whitelist github links for now

- apps/beeswax/data/tables_transactional.json
This is good enough to be transational and works with more
versions of Hive.
> [hive] Using minimal version of transational sample tables

- .circleci/config.yml
Still using py2 but preparing for switching to py3
> [ci] Switch to dedicated latest build

- desktop/libs/metadata/src/metadata/optimizer/dummy_client.py
- desktop/libs/metadata/src/metadata/optimizer/optimizer_client.py
- desktop/libs/metadata/src/metadata/optimizer_api.py
- [metadata] Add connectors to suggestion API
- [metadata] Fix python styling of client API
> [metadata] Add connectors to suggestion API

- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
#1558  broked the download csv function, revert it
> [presto] fix download csv function

- desktop/core/src/desktop/middleware.py
> [connector] Metadata lib should be accessible

- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
- desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py
Relates to #1573
This change adds support for valid session properties when using the SqlAlchemy connector.
When executing queries, invalid USER and PASSWORD properties cause an AuthenticationRequired error to be raised which triggers the auth prompt on the client-side.
> Raise AuthenticationRequired error whenever invalid credentials to datasource throws exception

- desktop/core/src/desktop/lib/connectors/api.py
- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
- [impala] Listing tables does not accept table name filters
- [sqlalchemy] Add note about bug when updating a connector
- [sqlalchemy] Auto delete session key only if key present
- [sqlalchemy] Avoid broken connector config check
> Various SqlAlchemy bugs fixes

- apps/metastore/src/metastore/views.py
Connector id is getting lost across the chain.
Not ideal fix but good for iterating.
> [connector] Avoid data sample failure

- apps/jobbrowser/src/jobbrowser/api2.py
- apps/jobbrowser/src/jobbrowser/apis/hive_query_api.py
> GH-1424 [api] Query kill is broken

- desktop/core/src/desktop/lib/connectors/types.py
- docs/docs-site/content/administrator/configuration/connectors/_index.md
- [docs] Adding references to Trino
- [connector] Adding Trino to connector name
> [docs] Adding references to Trino

- docs/gethue/content/jp/posts/2020-10-20-querying-live-streams-of-data-with-flink-sql.md
- docs/gethue/content/jp/posts/2020-10-20-querying-live-streams-of-data-with-kafka-sql.md
- docs/gethue/content/jp/posts/2020-11-17-querying-live-kafka-data-in-apache-hbase-with-phoenix.md
- docs/gethue/content/jp/posts/2020-12-31-querying-spark-sql-with-spark-thrift-server-and-hue-editor.md
Hi Hue-team,
I translated four blogs into Japanese after October 2020. Please let me know if find any issues.
Best Regards,
Tatsuo
> [docs] Translation of blogs into Japanese after October 2020

- desktop/core/src/desktop/management/commands/runcelery.py
- desktop/libs/notebook/src/notebook/models.py
- desktop/libs/notebook/src/notebook/tasks.py
- tools/docker/hue/Dockerfile
- tools/kubernetes/helm/hue/templates/deployment-celery-workers.yaml
- [k8s] Task Server for Python 3
- [task] Connector support
> [k8s] Task Server for Python 3

- docs/docs-site/content/developer/parsers/_index.md
> [docs] Updating and fixing Parser page links

- apps/beeswax/src/beeswax/server/dbms.py
- desktop/core/src/desktop/lib/connectors/types.py
- [connector] Add use Sasl property to Impala dialect
- [connector] Fix use sasl property
> [connector] Add use Sasl property to Impala dialect

- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/libs/hadoop/src/hadoop/conf.py
- desktop/libs/hadoop/src/hadoop/fs/webhdfs.py
For historical reason there is no way to disable HDFS.
> [hdfs] Add a config flag to cleanly disable while using connectors

- desktop/libs/notebook/src/notebook/connectors/flink_sql.py
- tools/docker/hue/conf3/z-hue-overrides.ini
- [docker] Re-indent all the default ini properties
- [flink] Add get_sample_data skeleton API
- [flink] Avoid mixing public and private API
> [flink] Add get_sample_data skeleton API

- README.md
- docs/gethue/content/en/posts/2020-10-20-querying-live-streams-of-data-with-flink-sql.md
- docs/gethue/content/en/posts/2020-11-17-querying-live-kafka-data-in-apache-hbase-with-phoenix.md
- [flink] Add get_sample_data skeleton API
- [flink] Avoid mixing public and private API
- [blog] Fix mention of Phoenix SQL
- [blog] Add reference to follow-up post on Flink SQL
> [blog] Add reference to follow-up post on Flink SQL

- apps/about/src/about/templates/admin_wizard.mako
- apps/about/src/about/views.py
- apps/beeswax/data/queries.json
- apps/beeswax/data/tables.json
- apps/beeswax/data/tables_standard.json
- apps/beeswax/data/tables_transactional.json
- apps/beeswax/src/beeswax/management/commands/beeswax_install_examples.py
- apps/beeswax/src/beeswax/management/commands/beeswax_install_examples_tests.py
- desktop/core/src/desktop/auth/backend.py
- desktop/core/src/desktop/lib/connectors/types.py
- desktop/libs/notebook/src/notebook/management/commands/notebook_setup.py
- desktop/libs/notebook/src/notebook/management/commands/samples_setup.py
- desktop/libs/notebook/src/notebook/views.py
- desktop/libs/notebook/src/notebook/views_tests.py
- [phoenix] Add sql sample tables and queries
- [editor] Swapping file names of create table data files
- [phoenix] Add a test checking for the UPSERT sample data
- [notebook] Install all samples command
> Step 1 of refactoring the SQL samples install to allow new dialects more easily

- apps/beeswax/src/beeswax/management/commands/beeswax_install_examples.py
- apps/useradmin/src/useradmin/models.py
- apps/useradmin/src/useradmin/organization.py
- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/core/src/desktop/models.py
- desktop/libs/notebook/src/notebook/api.py
- desktop/libs/notebook/src/notebook/apps.py
- desktop/libs/notebook/src/notebook/conf.py
- desktop/libs/notebook/src/notebook/management/commands/samples_setup.py
- desktop/libs/notebook/src/notebook/models.py
- desktop/libs/notebook/src/notebook/views.py
- [editor] Refactoring for Auto install examples
- [editor] Refresh examples content when re-installing them
- [editor] Hook in auto load dialect example
> Step 1 of auto loading dialect examples on fresh editor openong

- apps/useradmin/src/useradmin/organization.py
- desktop/core/src/desktop/lib/connectors/models.py
- [phoenix] Add sql sample tables and queries
- [editor] Swapping file names of create table data files
- [phoenix] Add a test checking for the UPSERT sample data
- [notebook] Install all samples command
- [notebook] Allow to pick a certain dialect in install examples
- [notebook] Adding hive and impala dialects to their sample queries
- [editor] Do not fail when dialects dont have samples
- [organization] Workaround creating org of sample user on first login
- [connectors] Offer a minimal natural key mapping
> [connectors] Offer a minimal natural key mapping

- apps/about/src/about/templates/admin_wizard.mako
- apps/beeswax/data/queries.json
- apps/beeswax/data/tables.json
- apps/beeswax/src/beeswax/management/commands/beeswax_install_examples.py
- desktop/core/src/desktop/lib/connectors/models.py
- desktop/core/src/desktop/models.py
- [flink] Adding Flink SQL examples
- [ksql] Adding ksqDB SQL examples
> review romain

- apps/beeswax/src/beeswax/management/commands/beeswax_install_examples.py
- apps/beeswax/src/beeswax/management/commands/beeswax_install_examples_tests.py
- desktop/core/src/desktop/models.py
- desktop/libs/notebook/src/notebook/models.py
Should be in document:
- dialect: hive
- type: query-hive
- FK to Connector
> [editor] Fix issue of query-10 vs query-hive in samples

- apps/beeswax/data/tables_transactional.json
This reverts commit 77c69c554dc74a0b3c3172939125e80f75098212.
> Revert "[hive] Using minimal version of transational sample tables"

- desktop/core/src/desktop/js/catalog/optimizer/NoopSqlAnalyzer.ts
- desktop/core/src/desktop/js/catalog/optimizer/SqlAnalyzer.ts
- desktop/core/src/desktop/js/catalog/optimizer/optimizer.ts
With this change it will now always call the api to retrieve top joins.
> [editor] Combine the local and api strategies into a new SqlAnalyzer

- .github/pull_request_template.md
- [Git] Creating an Pull Request Template for Hue
- Followed the guidelines as per Github Docs : https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
> [Git] Creating an Pull Request Template for Hue

- docs/docs-site/content/developer/development/_index.md
- Minor docs typo in the 'Development' section
> [docs] 'Sump' typo fix to 'Sum-up'

- docs/docs-site/content/developer/development/_index.md
- Added how to update the test snapshots in the testing section of the docs
> [docs] Add how to update test snapshots

- README.md
- VERSION
- desktop/libs/librdbms/java/pom.xml
- docs/docs-site/content/_index.md
- docs/docs-site/content/administrator/installation/dependencies/_index.md
- docs/docs-site/content/developer/development/_index.md
- docs/docs-site/content/releases/release-notes-4.6.0.md
- docs/docs-site/content/releases/release-notes-4.7.0.md
- docs/docs-site/content/releases/release-notes-4.8.0.md
- docs/docs-site/content/releases/release-notes-4.9.0.md
- docs/gethue/content/en/posts/2021-02-02-release-hue-4-9.md
- maven/pom.xml
- package-lock.json
- package.json
- [docs] Improve release process
- [docs] Move notion of Jira to GitHub issues
- [release] Perform 4.9 release
> 4.9 Release

- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
- desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py
Tested manually
With adding `get_view_names()` ss -> https://drive.google.com/file/d/1FNAa6Hn5Fw2MEZstoOAQveJjOWwVOu2O/view?usp=sharing
without adding  ss->  https://drive.google.com/file/d/1MDFUoUkk5i6Jl1IxX8A92KtzH645Oona/view?usp=sharing
> HUE-9728 [sqlAlchemy] Add views to get_tables API

- desktop/core/src/desktop/js/apps/editor/execution/sqlExecutable.ts
- desktop/core/src/desktop/js/catalog/optimizer/SqlAnalyser.test.ts
- desktop/core/src/desktop/js/catalog/optimizer/SqlAnalyzer.ts
- desktop/core/src/desktop/js/ko/components/assist/ko.assistEditorContextPanel.js
- desktop/core/src/desktop/js/parse/types.ts
- [analyser] Add checkMissingLimit() in SQL statement
- [analyser] Add tests to SqlAnalyzer abd checkMissingLimit()
> [analyser] Add tests to SqlAnalyzer

- desktop/core/src/desktop/js/catalog/optimizer/SqlAnalyser.test.ts
- desktop/core/src/desktop/js/catalog/optimizer/SqlAnalyzer.ts
- desktop/core/src/desktop/js/ko/components/assist/ko.assistEditorContextPanel.js
- [analyser] Add checkSelectStar util
- [editor] Add checkSelectStar to assist
- [editor] Rename Add filter assist action to Fix me
- [analyser] Fixing coding nits on parsing
> [analyser] Add checkSelectStar util

- desktop/core/src/desktop/templates/login.mako
Button text & style must change, similar to pressing the button.
> [ui] Feedback on login when pressing <enter>

- desktop/libs/notebook/src/notebook/conf.py
Default values in inis were correct.
> [editor] Show external statement should default to false

- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/core/src/desktop/conf.py
- desktop/core/src/desktop/urls.py
- Slack integration added in hue.ini and made naming/message of slack integration simpler and generic.
> Update hue.ini and simpler naming/messages

- desktop/core/requirements.txt
- desktop/core/src/desktop/settings.py
- desktop/core/src/desktop/urls.py
- [core] Disable django admin app
- [core] Adding djangomako==1.2.1
- [core] djangomako==1.2.1 require Mako 1.0.7 max
> Unblocking Django 2.2 upgrade

- docs/docs-site/content/administrator/administration/reference.md
- docs/docs-site/content/developer/api/_index.md
- [docs] Refresh API section summary
- [docs] Removing old JIRA references on architecture page
> [docs] Refresh API section summary

- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
- desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py
- get_logs() function in sql_alchemy
> GH-1682 [sql_alchemy] adding get_logs() function

- desktop/libs/notebook/src/notebook/models.py
The MockRequest class
see https://github.com/cloudera/hue/issues/1754
Tested with hue 4.8.0 docker
Tested with a PIG script
> modify MockRequest class (see issue #1754)

- tools/ci/check_for_python_lint.sh
> Whitelist contents of /ops directory

- desktop/core/src/desktop/js/components/Tab.test.ts
- desktop/core/src/desktop/js/components/Tab.vue
- desktop/core/src/desktop/js/components/Tabs.vue
- desktop/core/src/desktop/js/components/__snapshots__/Tabs.test.ts.snap
Fix tab selection
Manually & UTs
> [frontend] Tab selection not working after Vue3 migration, fixed it

- desktop/core/requirements.txt
- desktop/core/src/desktop/lib/django_util.py
- Django==3.0.12 to Django==3.1.7 (latest version as of now)
> [Django 3.1] Upgraded Django to the latest version(3.1.7) till now

- desktop/core/src/desktop/views.py
(cherry picked from commit 814fdde6e362de3f70758d41875d7ec4be75fa5e)
> Fix SAML groups check

- tools/kubernetes/helm/hue/templates/deployment-hue-api.yaml
- tools/kubernetes/helm/hue/templates/ingress-https.yaml
- tools/kubernetes/helm/hue/templates/service-hue-api.yaml
- tools/kubernetes/helm/hue/values.yaml
- [core] Setting to turn off CORS
- [k8s] Adding API service
> [k8s] Adding API service

- tools/kubernetes/helm/hue/templates/ingress-https.yaml
- tools/kubernetes/helm/hue/templates/service-hue-api.yaml
- tools/kubernetes/helm/hue/values.yaml
Otherwise keep hititing:
Error: UPGRADE FAILED: YAML parse error on hue/templates/ingress-https.yaml: error converting YAML to JSON: yaml: line 24: mapping values are not allowed in this context
> [k8s] Move api into its own section

- desktop/core/ext-py/pysaml2-4.9.0/src/saml2/sigver.py
- re-apply HUE-3102 to pysaml2 v4.9.0
End-to-end with SAML2 IDP
> [core] Merge HUE-3102 to pysaml2 v4.9.0

- desktop/core/src/desktop/js/components/Spinner.vue
Add zIndex to hue-spinner
Manually
> [frontend] hue-spinner was getting hidden behind other elements

- desktop/core/src/desktop/js/components/DateRangePicker.vue
- desktop/core/src/desktop/js/components/FacetSelector.vue
- desktop/core/src/desktop/js/components/SearchInput.vue
- desktop/core/src/desktop/js/components/dropdown/DropdownDrawer.vue
- desktop/core/src/desktop/js/components/dropdown/DropdownPanel.vue
- Fix usage of slots in Dropdown, DateRangePicker & FacetSelector
- Fix value emit in SearchInput
Manually
> [frontend] UI components not working as expected

- apps/jobbrowser/src/jobbrowser/templates/job_browser.mako
Recreate queries everytime
Manually
> [frontend] Queries doesn't get refreshed

- desktop/core/src/desktop/js/types/types.ts
- package-lock.json
- package.json
> [frontend] Types change for moment & file-saver

- desktop/core/src/desktop/lib/botserver/views.py
- desktop/core/src/desktop/lib/botserver/views_tests.py
- Added Document2.DoesNotExist and updated UT with side_effect
Ref. PR for comments - https://github.com/cloudera/hue/pull/1824
> [slack] Add Document2.DoesNotExist and update UT

- docs/gethue/content/en/posts/2021-03-04-vue3-build-cli-options-composition-api-template-web-components-hue.md
Blogpost on Introducing Vue 3 & Web Components in Hue Query Editor
Using `hugo serve`
> [blog] Introducing Vue 3 & Web Components in Hue Query Editor

- tools/docker/website/gethue.Dockerfile.dockerignore
- [blog] Tweaks for generating the content with git modification history
- [website] Add local dockerignore to offer automated build
- [gethue] Add missing dockerignore
> blog build

- docs/gethue/themes/stack-hue-theme/layouts/partials/home.en.html
- [gethue] Add missing dockerignore
- [website] Remove Viz section from landing page
> [website] Remove Viz section from landing page

- .github/workflows/commitflow.yml
- [website] Remove Viz section from landing page
- [ci] Port Python circleci to GH action
> [ci] Port Python 2 circleci to GH action

- apps/filebrowser/src/filebrowser/lib/xxd_test.py
- Using mysql
- [fb] CI skip test_compare_to_xxd
> [fb] CI skip test_compare_to_xxd

- tools/vue3-webcomponent-wrapper/README.md
- tools/vue3-webcomponent-wrapper/package.json
Addressing review comments from https://github.com/cloudera/hue/pull/1850 as it got automerged
> [frontend] Improved vue3-webcomponent-wrapper README

- .github/workflows/autoclose-stale.yml
> [ci] Bump number of items of staleness checker to catch-up

- docs/gethue/content/en/posts/2021-03-09-process-and-learnings-when-upgrading-the-webserver-stack-django-upgrade-1.11-to-3.1.md
> [Blog] adding django_upgrade 1.11 to 3.1  blog

- .github/workflows/commitflow.yml
> [ci] Properly reset home to checked out repo for doc linting

- .eslintrc.js
- desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceEditor.test.ts
- desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceLocationHandler.ts
- desktop/core/src/desktop/js/apps/editor/components/aceEditor/__snapshots__/AceEditor.test.ts.snap
This takes care of an issue where the syntax checker for keywords doesn't replace the actual word.
> [editor] Syntax checker fix

- docs/gethue/content/jp/posts/2021-03-04-vue3-build-cli-options-composition-api-template-web-components-hue.md
- docs/gethue/content/jp/posts/2021-03-06-web-api-service-upgrade-no-downtime-kubernetes-rollout.md
- docs/gethue/content/jp/posts/2021-03-09-process-and-learnings-when-upgrading-the-webserver-stack-django-upgrade-1.11-to-3.1.md
Hi Hue-team,
I translated three blogs into Japanese.
Please let me know if you find any problems.
- Localized three blogs that published in March 2021.
- Verified on my browser using `hugo serve`
> [docs] localized latest blogs into Japanese (published in March 2021)

- desktop/core/requirements.txt
- desktop/core/src/desktop/lib/botserver/views.py
- Fetch query result for preview
- Refactoring for better readability
- Better unfurl UI
> [slack] Show fetch result, refactor payload function and better UI

- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/core/src/desktop/conf.py
- [core] Default gunicorn workers to one
- [core] Automatically run with Gunicorn when on Python 3
> [core] Automatically run with Gunicorn when on Python 3

- package.json
> [frontend] Bump the npm package version

- .github/workflows/autosquash.yml
- [ci] Refactor stale yml into issue and PR sections
- [ci] Only run autosquash on PR not coming from a Fork
> [ci] Only run autosquash on PR not coming from a Fork

- apps/beeswax/src/beeswax/models.py
- apps/beeswax/src/beeswax/server/hive_server2_lib_tests.py
- Fix TSessionHandle guid and secret corrupted after save
- tested in my local py3 dev environment
> [impala] Fix TSessionHandle guid and secret corrupted after save

- desktop/core/src/desktop/lib/botserver/views.py
- desktop/core/src/desktop/lib/botserver/views_tests.py
- Changed None check according to [PEP8](https://www.python.org/dev/peps/pep-0008/#programming-recommendations)
- Try/except for Slack API calls
- Separate method for result file upload
- Updated UTs
- By running Unittests
> [slack] Update unit tests and refactor views.py

- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
To avoid error poup on incomplete queries, i.e. autocomplete table name
still partial
> [sqlalchemy] Avoid errors from auto explain query

- docs/docs-site/content/user/concept/_index.md
- Removed the release number confusion
- Better explanation for sharing section along with addition of `public links/gist sharing` and beta `share to slack` feature
> [docs] User concept section improvements

- docs/docs-site/content/developer/development/_index.md
- The issue in https://docs.gethue.com/developer/development/#apache-hive is fixed with this PR 
- (Attached screenshot of the issue)
- tested manually in online md editor , Fix Works well.
> [doc] correct developer documentation intendation to consider the content as code .

- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
- [sqlalchemy] Skip column key metadata retrieval for Phoenix
- [sqlalchemy] Avoid column autocomplete errors on unknown tables
> [sqlalchemy] Avoid column autocomplete errors on unknown tables

- desktop/core/src/desktop/middleware.py
fixing the middleware upgrade issue -> https://docs.djangoproject.com/en/3.1/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware
There are 2 ways of writing the middleware
1 -> Write middleware in the new style (https://docs.djangoproject.com/en/3.1/topics/http/middleware/#writing-your-own-middleware)
2 -> upgrade the old style using MiddlewareMixin (https://docs.djangoproject.com/en/3.1/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware)
> [Django_middleware] fixing the middleware upgrade issue

- desktop/core/src/desktop/js/apps/editor/components/QueryEditorWebComponents.ts
- desktop/core/src/desktop/js/apps/editor/execution/executable.ts
- desktop/core/src/desktop/js/components/assist/SqlAssistPanel.scss
- desktop/core/src/desktop/js/components/assist/SqlAssistPanel.vue
- package-lock.json
- package.json
Updated SQL Scratchpad code will follow after new NPM release.
> SQL Scratchpad improvements

- desktop/core/src/desktop/lib/botserver/views.py
- Remove 'dialect' and 'created by' section
- Add 'created by' in the preview heading instead
> [slack] Improve preview UI

- apps/useradmin/src/useradmin/test_ldap.py
- apps/useradmin/src/useradmin/test_ldap_deprecated.py
Tried moving warning suppression to test function
with warnings.catch_warnings():  # Hide GH false positive check from LDAPError exception.
warnings.simplefilter("ignore")
And:
PYTHONWARNINGS=always,ignore:::useradmin.test_ldap
Log trace:
2021-03-17T01:57:26.2822415Z   raise PopupException(smart_str(_('There was an error when communicating with LDAP: %s')) % str(e))
2021-03-17T01:57:26.2827941Z [16/Mar/2021 18:57:26 -0700] exceptions_renderable ERROR    Potential trace: [<FrameSummary file /home/runner/work/hue/hue/apps/useradmin/src/useradmin/views.py, line 601 in add_ldap_users>, <FrameSummary file /home/runner/work/hue/hue/apps/useradmin/src/useradmin/views.py, line 802 in import_ldap_users>, <FrameSummary file /home/runner/work/hue/hue/apps/useradmin/src/useradmin/views.py, line 945 …
> [ci] Ignore LDAP tests warnings to avoid GH false positive checks

- tools/license/checkLicenses.js
From https://www.npmjs.com/package/argparse
> [frontend] Add Python-2.0 as valid npm license

- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
adding hasHeader feature
and using file_url in the place of csv_data (global variable)
adding unittest
> [Importer] adding hasHeader, file_url to improve the code

- desktop/core/src/desktop/js/jquery/plugins/jquery.notify.js
- desktop/core/src/desktop/static/desktop/js/jquery.notify.js
Fix bug using _this and not this.
Make sure we check the message post XSS and tags stripping.
> [ui] Also patch another jquery.notify plugin

- desktop/core/requirements.txt
- tools/docker/hue/README.md
- tools/kubernetes/helm/hue/Chart.yaml
- tools/kubernetes/helm/hue/README.md
- tools/kubernetes/helm/hue/templates/NOTES.txt
- tools/kubernetes/helm/hue/values.yaml
- [lib] Bump dahpne as needed by new channels
- [k8s] Refresh to work easily with helm3 and publick repo
> [k8s] Refresh to work easily with helm3 and publick repo

- desktop/core/src/desktop/lib/python_util.py
- desktop/core/src/desktop/lib/python_util_test.py
- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
adding support for CJK and French encoding
tested with Hive and Impala
> [core] Adding CJK and French for check encoding

- desktop/core/src/desktop/lib/botserver/views.py
- desktop/core/src/desktop/lib/botserver/views_tests.py
- Remove query result section for gists shared in Slack
> [slack] Query result section only for query links and not gists

- desktop/core/src/desktop/js/apps/editor/execution/sqlExecutable.ts
automatic refresh added after create/drop just like before.
> [left assist] Automatic refresh of left assist on table DDL operation

- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- desktop/libs/indexer/src/indexer/tests.py
- Shifted the file chooser option in right
- supporting the special char in user name (in URL of file upload)
- Moving the localfile to position 1
- changing the name from LocalFile to Small Local File and File to Remote File
> [importer] improvements in direct upload

- desktop/libs/dashboard/src/dashboard/models.py
- desktop/libs/kafka/src/kafka/ksql_client.py
- desktop/libs/metadata/src/metadata/optimizer_api.py
- desktop/libs/notebook/src/notebook/connectors/flink_sql.py
- [flink] Handle completely empty results
- [meta] Avoid error message when no top columns are recommended
- [flink] Avoid false positive error when closing empty job
> [flink] Handle better expired queries

- desktop/core/src/desktop/conf.py
- desktop/core/src/desktop/middleware.py
And to decouple it from the CORS off flag.
> [api] Add a auto login flag for testing purpose

- docs/docs-site/content/administrator/configuration/server/_index.md
- Add channels:read in OAuth scopes table
> [docs] Add channels:read in slack app scopes table

- desktop/core/src/desktop/js/api/auth.ts
- desktop/core/src/desktop/js/apps/editor/components/sqlScratchpad/SqlScratchpad.vue
- desktop/core/src/desktop/js/apps/editor/components/sqlScratchpad/SqlScratchpadWebComponent.ts
- desktop/core/src/desktop/js/ext/ace.d.ts
- package-lock.json
- package.json
This fixes an issue with regenerator-runtime when used outside babel and adds a couple of attributes to the element:
- user and password for login
- optional jwt attribute to enable legacy login when set to false
- api_url added for the base url
> [editor] Simplify the SQL Scratchpad web component

- desktop/libs/indexer/src/indexer/templates/importer.mako
- putting if-else condition for default source type.
> [importer_direct_upload] applying if else condition for default source type

- desktop/core/src/desktop/js/ko/bindings/ko.hiveChooser.js
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
> [importer_direct_upload_dialects] Adding drop down for selecting different dialects

- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- supporting the hive dialect for the direct upload.
> [importer_direct_upload_hive] Supporting hive dialect for the direct upload

- desktop/core/src/desktop/js/api/apiHelper.js
- desktop/core/src/desktop/js/api/urls.js
- desktop/core/src/desktop/js/apps/editor/components/ko.snippetEditorActions.js
- desktop/core/src/desktop/js/ko/components/__snapshots__/ko.shareGistModal.test.js.snap
- desktop/core/src/desktop/js/ko/components/ko.shareGistModal.js
- desktop/core/src/desktop/lib/botserver/api.py
- desktop/core/src/desktop/lib/botserver/api_tests.py
- desktop/core/src/desktop/lib/botserver/urls.py
- desktop/core/src/desktop/lib/botserver/views.py
- desktop/core/src/desktop/lib/botserver/views_tests.py
- desktop/core/src/desktop/templates/global_js_constants.mako
- Added share from editor section in gist modal
- Added send message API
- Update API UTs
- Link unfurling enabled for bot 
- Successfully running UTs and manually testing
Gist modal with changes and polished UI
On pressing `Post Message`
> [slack] Share from Editor section

- desktop/libs/indexer/src/indexer/indexers/sql.py
- supporting the MySQL dialect for the direct upload
> [importer_direct_upload_mysql] Supporting mysql dialect for the direct upload

- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- unit test added using pre-exist CSV file (us_population.csv)
> [importer] adding unit test for direct upload using sourceType as mysql

- desktop/libs/aws/src/aws/s3/s3connection.py
- desktop/libs/aws/src/aws/s3/s3connection_test.py
- [raz] Iteration on file reading
- [raz] Refactoring to share common XML unmarshalling
> [raz] Refactoring to share common XML unmarshalling

- desktop/libs/aws/src/aws/s3/s3connection.py
- desktop/libs/aws/src/aws/s3/s3connection_test.py
- desktop/libs/aws/src/aws/s3/s3file.py
- [raz] Iteration on file reading
- [raz] Refactoring to share common XML unmarshalling
- [raz] Add tests for UrlConnection with RAZ client
- [aws] Move all common get_buckets code in parent method
- [aws] MVP of S3 file download via URL
> [aws] MVP of S3 file download via URL

- desktop/libs/indexer/src/indexer/templates/importer.mako
- feature of auto default dialect added
> [importer_direct_upload] adding auto default dialect

- desktop/core/src/desktop/lib/botserver/views.py
- Basic assistance of catching raw SQL SELECT 1 and sending a "only visible to you" message for user in channel.
- The message body can be made prettier using [Block Kit](https://api.slack.com/block-kit/building)
> [slack] Assistance V1

- desktop/libs/aws/src/aws/client.py
- desktop/libs/aws/src/aws/s3/s3connection.py
- desktop/libs/aws/src/aws/s3/s3connection_test.py
- desktop/libs/aws/src/aws/s3/s3file.py
- [aws] HEAD on get_key to avoid downloading all the key
- [aws] Raz client should take an HTTP action in argument
- [aws] Use S3FileSystemException within the UrlConnections
- [aws] Use signed url directly in boto make_request()
- [aws] Move back url signed file reading to open()
- [aws] MVP of simpler Connection
> [aws] MVP of simpler Connection

- desktop/libs/aws/src/aws/client.py
- desktop/libs/aws/src/aws/s3/s3connection.py
- desktop/libs/aws/src/aws/s3/s3connection_test.py
- [aws] Adding get key test for SelfSignedUrlS3Connection
- [aws] Adding more logic to the Raz Client
- [aws] Adding get key test for RazS3Connection
> Test for SelfSignedUrlS3Connection and RazS3Connection

- desktop/core/src/desktop/asgi.py
- tools/kubernetes/helm/hue/templates/deployment-celery-beat.yaml
- tools/kubernetes/helm/hue/templates/deployment-celery-flower.yaml
- tools/kubernetes/helm/hue/templates/deployment-celery-workers.yaml
- tools/kubernetes/helm/hue/templates/deployment-daphne.yaml
- tools/kubernetes/helm/hue/templates/ingress-https.yaml
- tools/kubernetes/helm/hue/templates/service-daphne.yaml
- [k8s] Adding daphne properties
- [k8s] Add config hash to deployments
- [k8s] Ingress and deployment for Daphne
> [k8s] Ingress and deployment for Daphne

- desktop/core/src/desktop/lib/raz/clients.py
- desktop/core/src/desktop/lib/rest/http_client.py
- desktop/core/src/desktop/lib/rest/raz_http_client.py
- desktop/core/src/desktop/lib/rest/raz_http_client_test.py
- desktop/libs/azure/src/azure/abfs/abfs.py
- [rest] Slight clean-up in HttpClient
- [abfs] First skeleton of RAZ client with tests
> [abfs] First skeleton of RAZ client with tests

- desktop/core/src/desktop/lib/botserver/api.py
- desktop/core/src/desktop/urls.py
- Fixes `no permission to access to Slack Application` error
- Closes #2095
> [slack] Change Slack URLs by adding /desktop

- desktop/core/src/desktop/lib/botserver/views_tests.py
- Update the host domain in test links
- Add test for `select 1` message
- Successfully running unit tests
> [slack] Update botserver UTs

- desktop/libs/indexer/src/indexer/templates/importer.mako
-  removing the 'Type' bar because there is only a Table option
> [importer_direct_upload] removing the 'Type' bar because there is only a Table option

- desktop/core/src/desktop/lib/botserver/views.py
- desktop/core/src/desktop/lib/botserver/views_tests.py
- Allows the permission check to be used for other events. Needed for Assistance V1 and upcoming additions
- UTs refactoring reduces the time taken for running botserver unit tests by half
> [slack] Refactor slack permission check and unit tests

- desktop/core/src/desktop/urls.py
> [core] Add a logout url with hue prefix

- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- Now following the rule as followed in https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/base.py#L359-L361
> [importer_direct_upload] solving the issue of snippet_type and connector_type conflict

- tools/slack/manifest.yml
- Adding latest version of Hue Slack App YAML Manifest file
> [slack] Add latest version of app manifest

- apps/metastore/src/metastore/templates/metastore.mako
- desktop/core/src/desktop/conf.py
- desktop/core/src/desktop/js/apps/editor/EditorViewModel.js
- desktop/core/src/desktop/js/apps/notebook/NotebookViewModel.js
- desktop/core/src/desktop/js/apps/tableBrowser/metastoreSource.js
- desktop/core/src/desktop/js/apps/tableBrowser/metastoreViewModel.js
- desktop/core/src/desktop/js/doc/docSupport.js
- desktop/core/src/desktop/js/ko/components/assist/ko.assistDbPanel.js
- desktop/core/src/desktop/js/ko/components/assist/ko.assistEditorContextPanel.js
- desktop/core/src/desktop/lib/connectors/api.py
- desktop/core/src/desktop/models.py
- desktop/core/src/desktop/templates/global_js_constants.mako
- desktop/libs/notebook/src/notebook/api_tests.py
- desktop/libs/notebook/src/notebook/conf.py
- desktop/libs/notebook/src/notebook/templates/editor2.mako
- desktop/libs/notebook/src/notebook/templates/editor_components.mako
> [frontend] Enable custom name for Hive interpreters

- desktop/core/src/desktop/lib/botserver/views.py
- desktop/core/src/desktop/lib/botserver/views_tests.py
- detect_select_statement -> handle_select_statement
- [PR comment](https://github.com/cloudera/hue/pull/2123#discussion_r635230884)
- Running unit tests
> [slack] Update function name for better readability

- docs/gethue/content/en/posts/2021-05-18-installing-hue-slack-app-in-three-simple-steps.md
- Given the demo workspace link in which now we can login with the demo credentials
- Tried logging in with demo credentials in incognito mode. Worked successfully
> [blog] Update the app try-out section and minor markdown changes

- Makefile
To avoid failures when hue commands like app_reg are executed in
make desktop.
> [build] Install modules just after virtual-env

- desktop/core/src/desktop/js/ko/components/__snapshots__/ko.shareGistModal.test.js.snap
- desktop/core/src/desktop/js/ko/components/ko.shareGistModal.js
> [gist] Readonly the link field in gist modal

- desktop/core/src/desktop/js/ko/components/ko.historyPanel.js
- desktop/core/src/desktop/lib/connectors/types.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
- desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py
- Main focus on how to split the statements in sql_alchemy for execution
- phoenix dialect in
> [importer_direct_upload] supporting phoenix dialect for direct upload

- desktop/libs/indexer/src/indexer/conf.py
- enable_direct_upload = True (default value)
> [importer_direct_upload_on] default value change to 'true'

- docs/gethue/content/en/posts/2021-05-26-improved-hue-importer-select-a-file-choose-a-dialect-create-a-table.md
- blog post for importer direct upload
> [importer_direct_upload_blog] blog post for direct upload in importer is added

- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- enable_direct_upload value change to true in .ini files also.
> [importer_direct_upload] default value to 'true' in ini files

- docs/gethue/content/en/posts/2021-05-26-improved-hue-importer-select-a-file-choose-a-dialect-create-a-table.md
> [importer_direct_upload] link correction

- desktop/libs/indexer/src/indexer/templates/importer.mako
- As sourceType is now an observable property so need to change to sourceType(). 
- this is made observable at -> https://github.com/cloudera/hue/pull/2052/commits/13ce3aa8223f893e2e48d25c0c0f12116fe26283#diff-febde30edf75f1a484457fb976110629dcddf622992cecdb750b3ecde8ff0377R1643
> [importer_direct_upload] changing sourceType to sourceType() as it is now observable

- desktop/core/src/desktop/lib/botserver/views.py
- desktop/core/src/desktop/lib/botserver/views_tests.py
- Help message for better usability
> [slack] Add help message for Slack users

- tools/slack/manifest.yml
> [slack] Update latest app manifest

- desktop/libs/indexer/src/indexer/templates/importer.mako
> [importer_direct_upload_size] putting the limit (200KB) on size of file uploaded

- desktop/core/src/desktop/api_public_urls.py
- desktop/core/src/desktop/lib/botserver/api_tests.py
- desktop/core/src/desktop/lib/botserver/urls.py
- docs/gethue/themes/stack-hue-theme/layouts/partials/home.en.html
- tools/docker/hue/Dockerfile
- Fix unit test with the change in manifest file 0b65573845fc6f0ad519c5fffd7f4ecbc296782a
- Add manifest file in Dockerfile
- Update Slack install link for using CORS by default for public APIs
- Successfully running unit tests
> [slack] Fixes for One Click install

- desktop/core/src/desktop/api_public_tests.py
- desktop/core/src/desktop/api_public_urls.py
- desktop/core/src/desktop/urls.py
- [api] Fix slack API disabling all other URLs
> [api] Fix slack API disabling all other URLs

- desktop/core/src/desktop/api_public.py
- desktop/core/src/desktop/api_public_tests.py
- docs/docs-site/content/developer/api/rest/_index.md
- [api] Make sure request user is wrapped with UserProfile
- [api] Compatibility when connectors are off
- [docs] Document about form data content type
> [api] Compatibility when connectors are off

- desktop/core/ext-py/boto-2.46.1/boto/connection.py
[lib] Fix typo in boto2 request header setting
> [lib] Fix typo in boto2 request header setting

- desktop/core/src/desktop/js/apps/editor/api.ts
- desktop/core/src/desktop/js/apps/editor/components/ko.snippetEditorActions.js
- desktop/core/src/desktop/js/ko/bindings/ace/ko.aceEditor.js
- desktop/core/src/desktop/lib/fsmanager.py
- desktop/libs/aws/src/aws/s3/s3connection.py
- [fs] Stringify the user to get proper username key
- [editor] Port Ace editor v1 to use the new js formatter
- [editor] Port Ace editor v2 to use the new js formatter
> [editor] Port Ace editors to use the new js formatter

- apps/filebrowser/src/filebrowser/views.py
- desktop/core/src/desktop/lib/view_util.py
- desktop/core/src/desktop/settings.py
- docs/docs-site/content/administrator/installation/dependencies/_index.md
- docs/docs-site/content/developer/api/rest/_index.md
- [docs] How to get more recent npm installed
- [api] Adding storage browsing
- [docs] List file API
- [api] Add proper configuration settings
- [api] Provide default fs
> [api] List file

- docs/docs-site/content/administrator/configuration/server/_index.md
- Add the new Slack App Installation section
> [docs] Update Slack App installation section

- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/core/src/desktop/views.py
- desktop/libs/aws/src/aws/s3/s3connection.py
- [core] Avoid exception in 500 stack printing view with Python 2
- [raz] Do not get confusing error message on no value arguments
> [raz] Do not get confusing error message on no value arguments

- desktop/libs/notebook/src/notebook/templates/editor_components.mako
- GH-2331 - Query Editor Shows Done 0 results Though Results are available
- Tested Manually in UI, there is no Impact or issues, Tested all scenario's .
> GH-2331 Query Editor Shows Done 0 results Though Results are available

- docs/docs-site/content/developer/development/_index.md
> [docs] Fix minor typo in parser section

- VERSION
- desktop/libs/librdbms/java/pom.xml
- docs/docs-site/content/administrator/installation/dependencies/_index.md
- docs/docs-site/content/developer/development/_index.md
- docs/docs-site/content/releases/release-notes-4.10.0.md
- docs/gethue/content/en/posts/2021-06-14-release-hue-4-10.md
- docs/gethue/themes/stack-hue-theme/layouts/shortcodes/rawhtml.html
- docs/gethue/themes/stack-hue-theme/layouts/shortcodes/webcomp.html
- maven/pom.xml
- package.json
> [release] 4.10 Release and Blog post

- desktop/core/src/desktop/settings.py
- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- I am using this -> https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile for storing the CSV file.
> [importer_direct_upload] file storage location is changed to tempfile.NamedTemporaryFile 

- desktop/core/src/desktop/lib/raz/raz_client.py
(cherry picked from commit 36dbb94b592799a13b18a421e17b1409847a848c)
> [raz] Propagate the renewer user for DWX

- docs/docs-site/content/administrator/installation/dependencies/_index.md
> [docs] Update Mac Installation section

- desktop/core/src/desktop/lib/botserver/api_tests.py
- Added api namespace for slack install link.
- Successfully running unit tests.
> [slack] Update install link UT with public api url namespace

- desktop/libs/indexer/src/indexer/indexers/sql.py
> [importer_direct_upload] handling the empty rows in csv file

- desktop/libs/indexer/src/indexer/templates/importer.mako
- filtering the is_sql interpreters only in drop down menu
> [importer_direct_upload] filtering the is_sql interpreters only

- docs/docs-site/content/user/_index.md
> [docs] Minor typo fixes in User section

- desktop/core/requirements.txt
- desktop/libs/azure/src/azure/abfs/abfs.py
TypeError: required field "type_ignores" missing from Module
> [py3] Upgrade ipython module to not break the shell command

- desktop/libs/indexer/src/indexer/indexers/flink_sql.py
- desktop/libs/kafka/src/kafka/kafka_api.py
- docs/docs-site/content/developer/api/python/_index.md
- docs/gethue/content/en/posts/2021-06-30-how-to-use-azure-storage-rest-api-with-shared-access-sginature-sas-tokens.md
- [docs] Example of Python API for ADLS
- [ksql] Do not hardcode connector id in metadata API
- [blog] Improve style formatting of SAS blog post
- [importer] Do not hardcode Flink interpreter id
> [importer] Do not hardcode stream interpreter ids

- apps/filebrowser/src/filebrowser/forms.py
- apps/filebrowser/src/filebrowser/views.py
- desktop/core/src/desktop/api_public.py
- desktop/core/src/desktop/api_public_urls.py
- docs/docs-site/content/developer/api/rest/_index.md
- [api] Add /storage/download public operation
- [api] Namespace view a file API
- [api] Add /storage/upload public operation
> [api] Add /storage/download and /upload

- desktop/core/src/desktop/settings.py
- https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys
> [Django_warning] Port to avoid Django DEFAULT_AUTO_FIELD warnings

- desktop/core/src/desktop/js/apps/editor/components/executionAnalysis/ExecutionAnalysisPanel.vue
- desktop/core/src/desktop/js/catalog/api.ts
- package.json
Relies on #2294 
NPM package 4.10.4 already published
> Update the UI to use the new API endpoints

- desktop/core/src/desktop/api_public.py
- desktop/core/src/desktop/api_public_urls.py
- desktop/libs/indexer/src/indexer/indexers/flink_sql.py
- desktop/libs/kafka/src/kafka/kafka_api.py
- docs/docs-site/content/developer/api/rest/_index.md
- Adding /guess_format and /guess_field_types apis
> [api] Add /guess_format and /guess_field_types public operation

- docs/docs-site/content/developer/api/rest/_index.md
- Add /analyze API docs in table and column section
- Update wrong credentials section with 401 unauthorised
> [docs] Update /analyze and wrong credentials in REST API section

- apps/filebrowser/src/filebrowser/forms.py
- desktop/core/src/desktop/js/ko/components/assist/ko.assistPanel.js
- desktop/core/src/desktop/js/onePageViewModel.js
- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- desktop/libs/indexer/src/indexer/urls.py
- drag and drop feature with automatic table creation
> [importer_direct_upload] adding feature of automatic table creation when we drag and drop the local file in left assist

- docs/docs-site/content/developer/api/rest/_index.md
- Update /connector docs for new public APIs
> [docs] Update /connector docs

- desktop/core/src/desktop/lib/tasks/compress_files/compress_in_hdfs.sh
Compressing multiple folders or files causes exception as below, this was tested manually by running the bash script
++++++++++++
sh compress_files_in_hdfs.sh -u=/user/admin -f='Autorizados_fuente.csv TeradataConnectorforHadoopTutorial.pdf' -n=mahesh.zip
compress_files_in_hdfs.sh: line 59: [: Autorizados_fuente.csv: binary operator expected
Created temporary output directory: /tmp/tmp.1Kjq6KYhaw
Files to be compressed: Autorizados_fuente.csv TeradataConnectorforHadoopTutorial.pdf
filename Autorizados_fuente.csv
filename TeradataConnectorforHadoopTutorial.pdf
+ zip -r /tmp/tmp.1Kjq6KYhaw/mahesh.zip 'Autorizados_fuente.csv TeradataConnectorforHadoopTutorial.pdf'
zip warning: name not matched: Autorizados_fuente.csv TeradataConnectorforHadoopTutorial.pdf
zip error: Nothing to do! (try: zip …
> [fb] Compressing multiple files or folder causing compression error

- apps/filebrowser/src/filebrowser/templates/listdir.mako
> [filebrowser] adding delete button to the action group when is_trash_enabled is false

- desktop/core/src/desktop/lib/fs/proxyfs.py
- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/core/src/desktop/middleware.py
- [fb] Avoid custom do_as list_dir
> [raz] Inject proper username in case it is not present

- desktop/core/src/desktop/js/apps/editor/components/sqlScratchpad/SqlScratchpad.vue
Note: we don't display still the json response which might have more info.
> [sql] Surface exception message on login failure

- desktop/core/src/desktop/auth/api_authentications.py
- desktop/core/src/desktop/auth/api_authentications_tests.py
> [api] Change JWT field username -> userId

- desktop/core/src/desktop/auth/api_authentications.py
- desktop/core/src/desktop/auth/api_authentications_tests.py
- Storing token to communicate with external services as the user like Impala etc.
- Running unit tests
> [api] Store jwt access token in UserProfile

- desktop/core/src/desktop/api_public.py
- desktop/core/src/desktop/api_public_urls.py
- docs/docs-site/content/developer/api/rest/_index.md
- adding importer_submit_api to public operation
> [api] adding importer_submit api to public operation

- apps/filebrowser/src/filebrowser/templates/listdir.mako
- desktop/core/requirements.txt
- desktop/core/src/desktop/management/commands/rungunicornserver.py
- desktop/libs/aws/src/aws/s3/s3fs.py
- desktop/libs/aws/src/aws/s3/s3fs_test.py
- [libs] Fix gunicorn and gevent lib compatibility and dependency on six
- [aws] Fix deleting directory action
> [aws] Fix deleting directory action

- desktop/core/src/desktop/js/catalog/api.ts
- package-lock.json
- package.json
- Fix import path in catalog/api
- Ran UTs
- Manually verified the UI is working
> [frontend] Fix import path in catalog/api

- apps/filebrowser/src/filebrowser/templates/listdir.mako
- apps/filebrowser/src/filebrowser/templates/listdir_components.mako
- desktop/core/src/desktop/js/onePageViewModel.js
- adding "open in importer" btn in filebrowser
> [filebrowser] adding 'open in importer' button in filebrowser

- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/core/src/desktop/lib/raz/raz_client_test.py
- Unpolished RAZ ADLS client to get back proper SAS token
- Adding and running unit test
- Below is the ss for debug logs
> [raz] Raz Client for ADLS to submit proper requests to getback SAS token

- desktop/core/src/desktop/lib/rest/raz_http_client.py
- desktop/core/src/desktop/lib/rest/raz_http_client_test.py
- Plug-in the  token in signed_path from  response
- Update UTs
- Running UTs
> [raz] Update Raz Http Client to include actual SAS token

- desktop/core/src/desktop/js/onePageViewModel.js
- changing from window.setTimeout() to waitForObservable
> [importer] auto table creation sometimes failing for waiting 500ms so using 'waitforobservale' function for submit

- desktop/core/src/desktop/lib/view_util.py
> [core] changing 'is' to '==' as it was syntax error

- docs/docs-site/content/developer/api/rest/_index.md
- adding Document small file import API
> [doc] adding Document small file import API

- desktop/core/src/desktop/auth/views.py
- desktop/core/src/desktop/lib/django_test_util.py
- desktop/core/src/desktop/require_login_test.py
- desktop/core/src/desktop/settings.py
- https://django-axes.readthedocs.io/en/latest/2_installation.html
> [Django_axes_warning] adding axes beckend and middleware

- desktop/libs/indexer/src/indexer/api3.py
- adding hasattr(request, 'fs')
> [importer] 'NoneType' object has no attribute 'netnormpath' because of request.fs is not defined

- docs/gethue/content/en/posts/2021-07-26-create-sql-tables-on-the-fly-with-zero-clicks.md
- adding blog post for zero click importer
> [direct_importer] adding blog post for zero click importer]

- desktop/libs/hadoop/src/hadoop/core_site.py
- desktop/libs/hadoop/src/hadoop/core_site_tests.py
- Support auto-detect for ADLS cluster name along with S3
- Running unit tests
> [raz] Auto detect ADLS cluster name from config file

- docs/docs-site/content/administrator/configuration/connectors/_index.md
- removing the extra quotation mark
> [doc] removing the extra quotation mark

- apps/filebrowser/src/filebrowser/views.py
- desktop/core/src/desktop/models.py
- desktop/libs/azure/src/azure/abfs/__init__.py
- desktop/libs/azure/src/azure/abfs/abfs.py
- desktop/libs/azure/src/azure/conf.py
- desktop/libs/hadoop/src/hadoop/core_site.py
- desktop/libs/hadoop/src/hadoop/core_site_tests.py
- Auto-configure default_fs from core-site.xml
- Also, change `get_home_dir_for_ABFS` -> `get_home_dir_for_abfs`
> [raz] Auto-configure home directory for ADLS

- desktop/core/src/desktop/js/onePageViewModel.js
- changing any char other than A-Za-z0-9 to '_' when we drag and drop a file into the left assist.
- in[ importer.mako](https://github.com/cloudera/hue/blob/master/desktop/libs/indexer/src/indexer/templates/importer.mako#L559) file we are checking this.
> [importer] converting any char other than A-Za-z0-9 to '_'

- docs/docs-site/content/administrator/configuration/connectors/_index.md
> [docs] Remove ADLS broken link from connector storage section

- desktop/core/src/desktop/js/jquery/plugins/jquery.filechooser.js
- adding remote_storage_home for filechooser
> [filechooser] adding remote_storage_home in filechooser

- docs/docs-site/content/developer/api/rest/_index.md
- Remove the Authorisation token header field to reduce noise.
> [docs] Refactor public REST APIs curl commands

- apps/filebrowser/src/filebrowser/templates/listdir.mako
- adding min-height=100vh to extend the dropping area
> [filebrowser] expanding the dragenter area so that we can drop file anywhere

- docs/gethue/content/en/posts/2021-08-10-open-in-importer-and-copy-path-options-in-filebrowser.md
> [blog] adding blog post for open in importer and copy path options in filebrowser

- desktop/core/src/desktop/lib/raz/raz_client_test.py
- Check for S3 RAZ request params in the unit tests.
- Successfully modifying and running the unit tests.
> [raz] Add test condition to check for S3 request params

- docs/docs-site/content/developer/api/_index.md
- docs/docs-site/content/developer/components/_index.md
Will enable easier mobile browsing.
Also refactoring Web component package page to emphasize on NPM.
> [docs] Add proper links to the API pages

- desktop/core/src/desktop/js/ko/components/assist/assistDbEntry.js
- desktop/core/src/desktop/js/ko/components/assist/ko.assistDbPanel.js
- desktop/core/src/desktop/templates/global_js_constants.mako
- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/indexers/phoenix_sql.py
- desktop/libs/indexer/src/indexer/indexers/phoenix_sql_tests.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
-  integrating phoenix importer for a CSV file
- merging the code for phoenix dialect for local file and remote file
- improvements for localfile like auto table name
> [importer] integrating phoenix importer for a CSV file

- docs/gethue/content/en/posts/2021-08-10-open-in-importer-and-copy-path-options-in-filebrowser.md
> [blog] adding link to importer and example for copy path

- docs/gethue/content/en/posts/2021-08-17-create-phoenix-tables-in-just-2-steps.md
- https://cdn.gethue.com/uploads/2021/08/phoenix_importer_integration1.gif
-
> [blog] phoenix importer integration

- apps/filebrowser/src/filebrowser/templates/fb_components.mako
- apps/filebrowser/src/filebrowser/templates/listdir_components.mako
- desktop/core/src/desktop/templates/global_js_constants.mako
- preventing bucket listing if RAZ is enabled.
- So we are preventing in 3 ways
1.  cannot click on s3a://
2. path is not editable
3. level up button is disabled
> [filebrowser] Prevent bucket listing when RAZ is enabled

- desktop/core/src/desktop/lib/connectors/types.py
- docs/docs-site/content/administrator/configuration/connectors/_index.md
- [sql] Split Presto and Trino in their own dialect
- [docs] Clarify more about Presto and Trino configs
> [sql] Split Presto and Trino in their own dialect

- apps/filebrowser/src/filebrowser/templates/listdir.mako
-  disabling the 'Open In Importer' option for the folder.
> [filebrowser] disabling the 'Open In Importer' option for folder

- desktop/conf.dist/hue.ini
- desktop/core/src/desktop/middleware.py
- desktop/core/src/desktop/views.py
- docs/docs-site/content/developer/api/rest/_index.md
- [core] Harmonize the main ini file to be indented consistently
- [auth] More explicit debug message when skipping cluster middleware
- [core] Avoid old Hue 3 warning for API calls
- [docs] Clarify when json POST data in API calls will work
> [docs] Clarify when json POST data in API calls will work

- desktop/core/src/desktop/auth/api_authentications.py
Accidentally merged the commit without fixing the class comment in https://github.com/cloudera/hue/pull/2460
> [jwt] Fix DummyCustomAuthentication class comments

- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- desktop/libs/kafka/src/kafka/conf.py
- desktop/libs/kafka/src/kafka/kafka_api.py
- desktop/libs/kafka/src/kafka/kafka_client.py
This is part of a series of commits, with tests following-up next
as well as more polishing of the current inputs of step 1.
The goal of this PR is to make the POCs easier to demo and understand.
All is flagged of by default and is leveraing the previous design and
its past implementation to keep is as simple as possible and easy to
evolve.
> [importer] Prepare import from a Kafka Topic into a Table

- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/core/src/desktop/lib/raz/raz_client_test.py
- desktop/core/src/desktop/lib/rest/raz_http_client.py
- Much better 'container' and 'relative_path' value extraction.
- Added mapping for stats() and listdir() calls.
- Update unit tests for both calls above.
- Updating and running unit tests.
> [raz_adls] Add RAZ req mapping and update tests 

- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/core/src/desktop/lib/raz/raz_client_test.py
- desktop/core/src/desktop/lib/rest/raz_http_client.py
- desktop/libs/azure/src/azure/abfs/abfs.py
- Edit operations are working e.g. chmod
- Stuck on rename operation
> [raz_adls] Add mapping for edit ops and rename ops

- desktop/libs/metadata/src/metadata/optimizer_api.py
- desktop/libs/metadata/src/metadata/optimizer_api_tests.py
> [metadata] Fix serialization of risk API

- desktop/libs/metadata/src/metadata/optimizer_api.py
- desktop/libs/metadata/src/metadata/optimizer_api_tests.py
> [metadata] Private UI Risk API is missing some connector properties

- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/core/src/desktop/lib/raz/raz_client_test.py
- Decouple relative_path from access_type mapping.
- Separate tests for relative_path conditions.
- Cleaner tests with removed redundancy.
- Updating and successfully running unit tests.
> [raz_adls] Improve ADLS mapping and cleaner tests

- desktop/core/src/desktop/lib/thrift_/http_client.py
- desktop/core/src/desktop/lib/thrift_util.py
- desktop/core/src/desktop/lib/thrift_util_test.py
- Add bearer token method in THttpClient
> [jwt] Injecting JWT as bearer token over THttpClient to Impala

- desktop/core/src/desktop/lib/raz/clients.py
- desktop/core/src/desktop/lib/raz/clients_test.py
- desktop/core/src/desktop/lib/raz/raz_client_test.py
- desktop/core/src/desktop/lib/rest/raz_http_client.py
- desktop/libs/azure/src/azure/abfs/abfs.py
- Move it to `AdlsClient().get_url()` so that the core `abfs.py` is not cluttered with Raz related code.
- Update the tests to check the header getting signed with SAS separately.
- Successfully updating and running unit tests.
> [raz_adls] Refactor rename operation section

- docs/docs-site/content/developer/api/_index.md
- docs/docs-site/content/developer/api/cli/_index.md
- docs/docs-site/content/developer/api/python/_index.md
- docs/docs-site/content/developer/development/_index.md
- [libs] Bump to latest ipdb
- [docs] First cli docs
> [docs] First cli docs

- docs/docs-site/content/administrator/configuration/connectors/_index.md
> [docs] Fix missing end tag in HBase connector docs

- docs/gethue/content/en/posts/2021-09-14-sso-for-rest-apis-with-your-custom-jwt-authentication.md
- Blog post for custom JWT Authentication.
- Tested formatting via `hugo serve`.
> [blog] Add blog post for custom JWT Auth backend

- desktop/libs/indexer/src/indexer/templates/importer.mako
- adding remote file option for calling guess_fuled_types also.
> [importer] calling guess_field_types for both 'localfile' and 'remote file' options

- apps/beeswax/src/beeswax/conf.py
- apps/beeswax/src/beeswax/server/hive_server2_lib.py
- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- adding hplsql config,  default is off.
> [hplsql] adding hplsql config to on and off the HPLSQL mode

- desktop/libs/metadata/src/metadata/catalog/atlas_client.py
- #2542  HUE Not picking up atlas information ( CLR-91694 )
- Tested manually, Works well
> GH-2542 HUE Not picking up atlas information (asnaik)

- desktop/core/src/desktop/api_public.py
- desktop/core/src/desktop/api_public_urls.py
- Make `\search_entities_interactive` API public.
> [api] Add Top Search API to public

- apps/beeswax/src/beeswax/models.py
- apps/beeswax/src/beeswax/server/hive_server2_lib.py
- desktop/libs/notebook/src/notebook/connectors/hiveserver2.py
- Solving the session_reuse problem
- adding application='hplsql' for HPLSQL mode
> [hplsql] hplsql_session reuse solution

- apps/beeswax/src/beeswax/server/hive_server2_lib.py
- desktop/libs/notebook/src/notebook/sql_utils.py
- desktop/libs/notebook/src/notebook/sql_utils_tests.py
- adding get_hplsql_statements function to return the hplsql_statement
> [hplsql] modifying the get_statement according to hplsql mode

- apps/beeswax/src/beeswax/server/hive_server2_lib.py
> [beeswax] sorting the tables

- apps/beeswax/src/beeswax/server/hive_server2_lib_tests.py
- adding unit test for this commit -> https://github.com/cloudera/hue/pull/2585/commits/881fa8ce46be23d0944d2aeada60185720a19bb1
> [beeswax] adding unittest for sorting of tables

- desktop/core/src/desktop/js/apps/editor/EditorViewModel.js
- desktop/core/src/desktop/js/apps/notebook/NotebookViewModel.js
- adding HPL/SQL with Hive in editor heading
> [hplsql] adding 'HPL/SQL with 'Hive' in editor heading

- apps/beeswax/src/beeswax/conf.py
- apps/beeswax/src/beeswax/server/hive_server2_lib.py
- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- adding config flag for max_tables in the left assit
> [beeswax] adding config flag for max no of tables in the left assist

- desktop/core/src/desktop/api_public.py
- desktop/core/src/desktop/api_public_urls.py
- APIs like /user_list_for_autocomplete, /get_users_by_id
> [api] Add IAM related public APIs

- apps/jobbrowser/src/jobbrowser/api2.py
- Commit ID reverted: 69267de42b77121a75b96006ddaa6da8ae227f75
> [jobbrowser] Revert queries-hive `No JSON object could be decoded` commit

- apps/beeswax/data/tables/flights.csv
- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/api3_tests.py
- Changing all char to '_' except alphanumeric and '-'
- Hive and Impala don't support any other char except alphanumeric and '-'
- Unit test
- Manual
> [importer] auto formatting table and header name

- docs/gethue/content/en/posts/2021-11-15-create-sql-tables-from-excel-files.md
- blog post on supporting xlsx file in the direct importer
> Blog xlsx direct importer

- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/file_format.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- adding xlsx file for importer
> [importer] adding xlsx file type for importer

- desktop/libs/metadata/src/metadata/catalog/navigator_client.py
- Changing params from tuple to dict in the navigator search APIs
- Might be a regression from RAZ development via this [commit](https://github.com/cloudera/hue/commit/f6ad77498d4ba792495b1d63b0992372c4ea24bb#diff-806a2716ee7e9536d6f5870ed070e66817f154ee1fe348c6377f501cff07b6aaR251)
> [navigator] Change params from tuple to dict

- desktop/core/requirements.txt
- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/api3_tests.py
- desktop/libs/indexer/src/indexer/file_format.py
- adding excel support for remote file importer
- Manually
- Unit test
> [importer] adding excel support for remote file importer

- docs/gethue/content/en/posts/2021-11-15-create-sql-tables-from-excel-files.md
- adding blog for remote excel file importer
> [importer] adding blog post for remote excel file importer

- apps/beeswax/src/beeswax/server/dbms.py
- apps/beeswax/src/beeswax/server/hive_server2_lib.py
- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/core/src/desktop/js/parse/utils.ts
- desktop/libs/notebook/src/notebook/connectors/hiveserver2.py
- Added a new dialect named 'Hplsql'
- Manual
- working on Unittest?
> [Hplsql] adding hplsql dialect

- apps/beeswax/src/beeswax/conf.py
- apps/beeswax/src/beeswax/design.py
- apps/beeswax/src/beeswax/models.py
- apps/beeswax/src/beeswax/server/hive_server2_lib.py
- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/core/src/desktop/js/apps/editor/EditorViewModel.js
- desktop/core/src/desktop/js/apps/notebook/NotebookViewModel.js
- desktop/core/src/desktop/templates/global_js_constants.mako
- desktop/libs/notebook/src/notebook/connectors/hiveserver2.py
- desktop/libs/notebook/src/notebook/sql_utils.py
- desktop/libs/notebook/src/notebook/sql_utils_tests.py
- Removing old unused code of v1 and improving v2 code, getting ideas from the previous v1 commits https://github.com/cloudera/hue/pull/2574
- unittest modified for hplsql statements
> [hplsql] removing v1 code and improving v2 code

- desktop/libs/notebook/src/notebook/connectors/hiveserver2.py
- desktop/libs/notebook/src/notebook/sql_utils.py
- right method for checking key presence
> [hplsql] using right method for checking key presence

- desktop/core/src/desktop/templates/hue_icons.mako
- desktop/libs/notebook/src/notebook/conf.py
- changing the editor name and icon
- ss added
> [hplsql] changing the name from Hplsql to HPL/SQL in editor and icon

- desktop/core/src/desktop/js/ext/ace/mode-hplsql.js
- desktop/core/src/desktop/js/ext/ace/snippets/hplsql.js
- desktop/core/src/desktop/js/ext/aceHelper.ts
- desktop/libs/notebook/src/notebook/templates/editor_components.mako
- tools/ace-editor/lib/ace/mode/hplsql.js
- tools/ace-editor/lib/ace/mode/hplsql_highlight_rules.js
- tools/ace-editor/lib/ace/snippets/hplsql.js
- syntax highlight for hplsql keywords, built-in functions, datatypes.
- manually check with editor.
> [hplsql] syntax highlight for hplsql dialect

- desktop/libs/libsaml/src/libsaml/conf.py
update CDP_LOGOUT_URL
manually
> [core] update Hue SAML LOGOUT URL for CDP

- docs/gethue/content/en/posts/2022-02-01-hplsql-support.md
- updating doc -> statement terminate with forward-slash (/).
> [hplsql] updating the hplsql blog post

- docs/docs-site/content/administrator/configuration/connectors/_index.md
- adding hplsql dialect in Hue docs.
> [hplsq] adding hplsql dialect in Hue docs

- apps/beeswax/src/beeswax/server/hive_server2_lib.py
- apps/beeswax/src/beeswax/server/hive_server2_lib_tests.py
- desktop/core/src/desktop/lib/connectors/types.py
- Adding hplsql as a connector (when we do enable_connector=ture in config file)
- Manually
> [hplsql] adding hplsql as a connector

- desktop/core/src/desktop/js/catalog/api.ts
- desktop/libs/notebook/src/notebook/connectors/base.py
- temporary solution for left assist and table browser
- Manually
> [hplsql] temporary solution for left assist and table browser

- desktop/core/src/desktop/js/catalog/api.ts
- desktop/libs/notebook/src/notebook/api.py
- calling close statement API after sample query
> [core] calling close statement api after sample query

- docs/docs-site/content/developer/development/_index.md
- This change will unblock the CI checks.
- Building docs with Hugo.
> [docs] Remove font awesome dead link

- desktop/core/src/desktop/templates/common_header.mako
> Take the Hue base URL into account when redirecting from the Hue 404 page

- apps/filebrowser/src/filebrowser/templates/listdir_components.mako
- allowing user to go outside home bucket
- Manually
> [RAZ] allowing user to go outside home bucket

- desktop/core/src/desktop/settings.py
> Hue [py3] Fix Hue code lint issues.

- Makefile
- tools/container/build.sh
- tools/container/common.sh
> Hue [py3] reset git state prior to docker build

- tools/container/build.sh
> Hue [py3] Perform any other container build process

- tools/container/build.sh
> Hue [py3] Remove reseting git state step

- .github/workflows/commitflow-py3.yml
(cherry picked from commit e816f6c486ca1a989923b695744a152a54731415)
(cherry picked from commit 534f23b5f723be9b3cd190609203c39bddd4b448)
> Updating Hue package requirement

- tools/container/build.sh
- tools/container/hue/Dockerfile
- Tested on localhost cluster.
> Remove chardet dependancy

- desktop/libs/notebook/src/notebook/api.py
- desktop/libs/notebook/src/notebook/connectors/hiveserver2_tests.py
- snippet dict was not complete so we need to get complete dict from notebook (Document2 object)
- Unit test and manually
> [core] closing older query before running new query

- desktop/libs/azure/src/azure/abfs/upload.py
Tested using ABFSFileUploadHandler, uploaded local file and verified it appears with content.
> Hue - Fix ABFS file upload

- desktop/core/src/desktop/conf.py
- desktop/core/src/desktop/settings.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- supporting large file(10MB) for local importer
- Manually tested in Mysql, Oracle, and Postgres DBs
> [Importer] supporting large file(10MB) for local importer

- desktop/core/requirements.txt
- desktop/libs/indexer/src/indexer/api3.py
- desktop/libs/indexer/src/indexer/api3_tests.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- upgrading libs
- supporting xls file type for local importer.
- removing support of xlsx file in local importer for python2 based Hue as  Hue has build issues with the older versions of pandas and openpyxl and having many bugs in the conversion of datetime deltas.
> [libs] upgrading pandas and openpyxl

- docs/docs-site/content/administrator/installation/dependencies/_index.md
Update gethue.com blog post
Manual
> [doc] Update Python 3.8.10 installation on M1 based Mac

- apps/beeswax/src/beeswax/server/dbms.py
- apps/beeswax/src/beeswax/server/dbms_tests.py
- desktop/libs/notebook/src/notebook/connectors/hiveserver2.py
Jira: CDPD-10924
Added missing condition for connection refused and error logging when there is no HS2 available in ZK.
> Added missing conditions and error logging for Hive HA via ZK

- desktop/libs/azure/src/azure/conf.py
- desktop/libs/indexer/src/indexer/conf.py
- This removes coerce_bool usage warning when server starts.
- After the fix, start the server and then warning will disappear.
> [config] Change config type from bool to coerce_bool

- desktop/core/src/desktop/conf.py
- Removing the MySQL config, large file importer will not work for MySQL directly now, need to add a config.
- We will document it.
> [core] removing mysql config and will add this config in doc

- desktop/core/src/desktop/js/ko/bindings/charts/ko.barChart.js
- adding function `getChartType` to extract chartType in ko.barChart since `options.type()` could return a string or a single string in an array. The previous code alway assumed that the return value was a string.
- added check to build chart on binding update if the chart was missing on the element. Without this the chart would only get rendered once the user manually changed the chart type, and thus not when the "chart panel" was first shown. Because of the bug of reading the type incorrectly this was not a problem before the getChartType fix.
- Small refactoring to improve readability
- Tested partially using unit tests
- Manual testing in the following browsers:
1. Open the hive editor (I was using a nightly build for backend)
2. Get some data, e.g. `SELECT * FROM sample_08 LIMIT 2;` …
> [frontend] fix linechart rendering in barchart KO binding

- apps/spark/src/spark/livy_client.py
- desktop/libs/notebook/src/notebook/connectors/spark_shell.py
- desktop/libs/notebook/src/notebook/connectors/spark_shell_tests.py
- Improve session handling
- Fix failing corner cases
- Add checks for different session states
- Cancel statement improvements
> [sparksql] Improve session reuse and fix corner cases

- Makefile
Fix build issue on Ubuntu20
system build
> [build] Fix build issue on Ubuntu20

- desktop/libs/indexer/src/indexer/conf.py
-  Disabling the direct upload by default
-
> [importer] disabling the direct upload by default

- desktop/libs/hadoop/src/hadoop/fs/webhdfs.py
- Remove unwanted semi-colon.
- Fix variable naming.
> [hdfs] Fix webhdfs code issues

- Makefile
this causes problem in PPC
built a cluster from internal build
> [build] Remove extra create-static from make install

- desktop/libs/notebook/src/notebook/connectors/spark_shell.py
- Add more context to the error along with the traceback.
- Manual testing
> [sparksql] Make error messages friendly and understandable

- desktop/libs/indexer/src/indexer/templates/importer.mako
- Restricting the upload size to 200KB
- 1MB support is not fully solid yet.
> [local importer] restricting the upload size to 200KB

- desktop/core/src/desktop/settings.py
- desktop/libs/indexer/src/indexer/indexers/sql.py
This reverts commit add923995a1209b34c059958926e0d9e859d117a.
- Reverting the large file local importer commit.
> Revert "[Importer] supporting large file(10MB) for local importer"

- desktop/libs/notebook/src/notebook/connectors/spark_shell.py
- desktop/libs/notebook/src/notebook/connectors/spark_shell_tests.py
> [sparksql] Convert unicode values to str

- .circleci/config.yml
- .github/workflows/commitflow-py3.yml
- Makefile
- Makefile.sdk
- Makefile.vars
- apps/Makefile
- apps/help/src/help/tests.py
- apps/oozie/src/oozie/management/commands/oozie_setup.py
- apps/search/src/search/management/commands/search_setup.py
- desktop/Makefile
- desktop/core/requirements.txt
- desktop/core/src/desktop/management/commands/rungunicornserver.py
- desktop/libs/hadoop/src/hadoop/fs/hadoopfs.py
- desktop/libs/notebook/src/notebook/management/commands/notebook_setup.py
- docs/Makefile
- tools/app_reg/pth.py
- tools/cloudera/build_hue_cloudera.sh
- tools/cloudera/build_hue_common.sh
- tools/container/build.sh
- tools/relocatable.sh
- tools/virtual-bootstrap/virtual-bootstrap.py
- build
- oozie
- solr
- notebook
- filemanager
- backend
- tested on CentOS7/Postgres10 and other systems.
> Hue Python3.8 upgrade

- desktop/libs/indexer/src/indexer/templates/importer.mako
- Notifying if file is empty.
- Manually
> [Importer] notifying if file is empty

- apps/oozie/src/oozie/views/dashboard.py
- desktop/libs/liboozie/src/liboozie/submission2.py
- Fix application_path to not add extra slash e.g //user
- Convert byte objects to str at different places
- Manually tested by trying to submit oozie workflow
> [oozie] Fix submitting oozie workflow from HDFS

- desktop/core/requirements.txt
Add python-pam for Python 3 requirement.txt
make apps for Py3 locally
> [py3] Add python-pam 2.0.2

- desktop/core/src/desktop/conf.py
- desktop/core/src/desktop/lib/metrics/file_reporter.py
- desktop/core/src/desktop/lib/metrics/registry.py
- desktop/core/src/desktop/management/commands/rungunicornserver.py
- desktop/core/src/desktop/middleware.py
Fix the issue of metrics log doesn't work in master process when running Gunicorn
Patched and tested on internal cluster
> [core] Fix metrics log when running Gunicorn

- desktop/libs/notebook/src/notebook/connectors/hiveserver2.py
Impala table import is failing intermittently when beeswax max_number_of_sessions != 0
- Disable session close for Impala
- Manually in a real cluster
> Impala table import is failing when multiple sessions are used

- desktop/libs/liboozie/src/liboozie/submission2.py
Jira: CDPD-44349
To validate whether the Jar name used is from S3 or ABFS filesystem and leave it as is.
Manually tested this patch in an internal cluster.
> Oozie MapReduce action should be able to accept s3a and abfs as Jar name

- desktop/libs/indexer/src/indexer/templates/importer.mako
- Same file with contents changed re-upload is working now in local file importer
- changing the value to null just after click
- Manually
> [importer] same file re-upload

- Makefile
- Makefile.vars
- desktop/devtools.mk
- tools/cloudera/build_hue_cloudera.sh
- tools/cloudera/build_hue_common.sh
- Enable IBM Power PC platforms such as PPC RHEL8 and PPC RHEL7 support
- Manual test
> Adding PPC platform support

- apps/impala/src/impala/server.py
> Revert "Impala table import is failing when beeswax max_number_of_sessions != 0"

- contributing-frontend.md
- Created new md file (currently not linked from the main CONTRIBUTING.md file )
> [docs] create react section for CONTRIBUTING.md

- docs/gethue/content/en/posts/2022-10-11-creating-iceberg-tables-in-hue.md
- Blog post got iceberg support in Hue importer
- Manually
> [Blog] adding blog post for iceberg support in Hue importer

- docs/docs-site/content/developer/api/rest/_index.md
- Added new sample response.
- Improved the API description.
> [docs] Update /get_filesystem public API section

- desktop/libs/aws/src/aws/s3/s3fs.py
- Manually tests in local Hue setup. Needs to be tested in E2E Raz cluster setup.
> [filebrowser] Check for s3a:// in remote_storage_home path

- desktop/core/src/desktop/js/ko/components/contextPopover/documentContext.js
- desktop/core/src/desktop/js/ko/components/contextPopover/ko.contextPopover.js
Internal Jira: CDPD-46957
[frontend] Add a download option for document results in the top search bar
> [frontend] Add a download option for document results in the top search bar

- tools/docker/hue/Dockerfile
- perform make apps install together
- fix the conf dir path
- Adding mysqlclient in the dockerfile
- perform make apps install together
- fix the conf dir path
- Adding mysqlclient in the dockerfile
- manual test on ubuntu 20.04 docker
> [Hue] Fix gethue.com issues.

- desktop/libs/notebook/src/notebook/connectors/spark_shell.py
- https://github.com/cloudera/hue/issues/2948
- Manual E2E testing in local Hue setup
> [sparksql] Show result for complex data types in correct format

- desktop/core/src/desktop/lib/raz/clients.py
- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/libs/aws/src/aws/s3/s3connection.py
- Cleanup path to be signed and sent to RAZ for signed headers
- Send xml data for /?delete calls for signing to RAZ for signed headers
> [raz] Fix S3 delete operation

- tools/docker/hue/Dockerfile
-  Fix gethue.com docker image for impala path
- manual
> Fixing gethue.com docker image for impala path

- .github/workflows/commitflow-py3.yml
More details @ https://github.com/actions/runner-images/issues/6002
> [Git] Upgrade Ubuntu version to 20.04

- tools/vue3-webcomponent-wrapper/package.json
> [npm] Publish new vue3-webcomponent-wrapper npm version v0.2.0

- apps/oozie/src/oozie/templates/editor2/workflow_editor.mako
- add condition to prevent an undefined value of the draggable widget from being used
Patch tested by @Akhilsnaik with client data
> [frontent] prevent js workflow error when moving args

- apps/jobbrowser/src/jobbrowser/templates/job_browser.mako
- Exponentially delay log loads
- updateLogs will be true when jobUpdateCounter is at 1, 2, 4, 8, 16, 32, 64, 128, 192, 256....
- Manually tested in a real cluster
> [oozie] UI is very slow to load due to frequent calls to Oozie logs

- desktop/libs/indexer/src/indexer/indexers/sql.py
- fixing encoding issue
- Manually
> [importer] fixing encoding issue in importer for external file creation

- tools/cloudera/build_hue_common.sh
(cherry picked from commit 4cf7caa12614b399a9864a8d0284d4d6739969ec)
- Build script fix
- Tested on Build docker image, Hue builds successfully.
> Fix pip FileNotFoundError on CentOS7 build

- desktop/libs/liboozie/src/liboozie/submission2.py
- For Py3 Hue, when the browser language is set to Korean and someone tries to run an oozie workflow for a shell script containing Korean chars, it was failing with the below error:
```
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 134-135: Body ('작업') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```
- Because of i18n, the xml data is having Korean chars when the browser language is Korean which was not utf-8 encoded. So we are encoding it properly and sending the xml data as bytes instead of str type.
- **NOTE: This issue is not seen in Py2 Hue.**
- Change the chrome browser language to Korean
- Create a new workflow with shell action
- Use any shell script with a simple "echo 안녕하세요"
- Add a workflow description in …
> [oozie] Don't encode request body with latin-1 for HDFS calls in Py3 for workflow shell script having Korean chars

- desktop/core/src/desktop/templates/common_notebook_ko_components.mako
- inserting the "()" around the DOWNLOAD_BYTES_LIMIT / 1024 /1024 for proper conversion
> [mako] proper conversion of DOWNLOAD_BYTES_LIMIT

- VERSION
- desktop/libs/librdbms/java/pom.xml
- docs/docs-site/content/developer/development/_index.md
- docs/docs-site/content/releases/release-notes-4.11.0.md
- docs/gethue/content/en/posts/2023-01-23-release-hue-4.11.md
- maven/pom.xml
> [release] Perform 4.11 release

- docs/gethue/content/en/posts/2023-01-23-release-hue-4.11.md
> [blog] url correction

- desktop/core/src/desktop/api2.py
- desktop/core/src/desktop/api2_tests.py
- topological sorting of the imported document
- Manually
- Unittest
> [core] sorting the document according to the dependencies

- desktop/core/src/desktop/lib/ozone/__init__.py
- desktop/core/src/desktop/lib/ozone/conf.py
> [ozone] Ozone V1 Skeleton

- .github/workflows/autoclose-stale.yml
- update message
- modify close days
- use "Prevent stale" 
> [github] Update auto-close bot and use 'Prevent stale' label

- docs/gethue/content/en/posts/2023-03-01-hue-community-2023.md
> [docs] new blogpost about community

- desktop/core/src/desktop/lib/fs/ozone/__init__.py
- desktop/core/src/desktop/lib/fs/ozone/ofs.py
This commit got missed because of forced push in https://github.com/cloudera/hue/pull/3189
> [ozone] Better naming for abspath var and using rename API for rename operation

- apps/filebrowser/src/filebrowser/templates/listdir_components.mako
- adding warnings for illegal volume and bucket name
- allowed length 3-63
- upper case not allowed
- locally
> [ozone] adding warnings for illegal volume and bucket name

- .gitignore
-  updated .gitignore file.
- manually in git clone folder
> Adding .gitignore items

- desktop/core/base_requirements.txt
- future 0.18.2 -> 0.18.3
- checked all the commits in the 0.18.3 version
- locally
- E2E testing
> [future] upgrading the future lib

- desktop/core/src/desktop/lib/fs/ozone/upload.py
- desktop/core/src/desktop/lib/fs/ozone/upload_test.py
- It was breaking HDFS upload
- Locally via uploading a file
> [ozone] Proper handeling of _get_scheme function in ozone

- apps/filebrowser/src/filebrowser/conf.py
- apps/filebrowser/src/filebrowser/templates/listdir_components.mako
- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/core/src/desktop/templates/global_js_constants.mako
- Config added for Limiting the upload size of the file.
-  -1 indicates no limit.
- If file size is greater than config then UI will show the error.
- Locally via uploading in HDFS and S3 and OZONE
> [Filebrowser] Add config for Limiting the upload size of the file.

- desktop/core/base_requirements.txt
- This change fixes nonzero flag error.
- Thrift server generates exception in Hue, This change fixes non-zero flags exception.
- Manually
> [Build] Download thrift-0.16.0 package from gethue git repo

- .github/workflows/commitflow-py3.yml
- Github actions added for python3.9
- Manually
- In this PR itself we can see Python 3.9 CI (checks)
> [Python3.9] Add github actions for py3.9

- desktop/core/base_requirements.txt
Add cx_Oracle 8.3.0
Created internal cluster with this patch and tested manually
> [core] Add cx_Oracle 8.3.0 in base requirements

- docs/docs-site/content/administrator/configuration/connectors/_index.md
- updated docs connector Athena for pull https://github.com/cloudera/hue/pull/3327
@Harshg999
> [docs] Update urlstring for PyAthena connector with new params

- desktop/conf.dist/log.conf
- desktop/conf/log.conf
- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/core/src/desktop/log/__init__.py
- desktop/core/src/desktop/management/commands/rungunicornserver.py
• Fixing DEBUG/INFO issue in logging.
• Tested manually
> [Backend] Fixing hue debug level issue

- tools/ci/check_for_python_lint.sh
Temporarily disabling lint check
> Temporarily disabling lint check

- desktop/core/src/desktop/conf.py
- Change "false" to False.
- Minor help message text change.
> [conf] Improve DISABLE_LOCAL_STORAGE default value

- docs/docs-site/content/developer/api/rest/_index.md
- Update upstream rest api docs.
- Manually via hugo serve.
> [docs] Add API version and improve custom auth section for public APIs

- desktop/conf.dist/gunicorn_log.conf
- desktop/conf/gunicorn_log.conf
-  Fix log issue
- Manually on the DataHub cluster
> [Backend] Fixing logging issue where it throws import desktop error

- desktop/core/src/desktop/conf.py
- desktop/core/src/desktop/lib/sdxaas/knox_jwt.py
- No need now to use `.replace()` to clean the incoming config.
- Also slight improvements in checks to that we don't do 2 redundant calls to Knox for non-HA mode.
- Running existing unit tests.
- Tested E2E in HA setup.
> [sdxaas] Improve JWT fetching from Knox HA setup

- desktop/core/base_requirements.txt
revert commits that adding database libs
> Revert database libs

- desktop/core/src/desktop/settings.py
This reverts commit 2efc3524912f3c17f839757b529f29f8f0e14e08.
> Revert "[core] Adde Hue LB's to the CSRF_TRUSTED_ORIGINS list (#3348)"

- Makefile
- Makefile.vars
- desktop/core/base_requirements.txt
- desktop/core/requirements.txt
- desktop/core/src/desktop/loglistener.py
- tools/cloudera/build_hue_cloudera.sh
- tools/cloudera/build_hue_common.sh
- Adding the support for redhat9 ppc
- on Redhat9 ppc
> [Core] Adding support for Redhat9 PPC

- desktop/core/base_requirements.txt
- Upgrade Python modules for the security fixes.
- Locally on Macbook localhost
> Upgrading ipython, py and sqlparse library

- .github/workflows/commitflow-py3.yml
- Add documentation CI checks in Github Actions
- This make GA check at par with CircleCI for upstream.
- Check is visible in this PR for Github Actions.
> [CI] Port doc lint check to Github Actions

- desktop/core/src/desktop/management/commands/sync_warehouses.py
Impala unified-analytics (feng) presents a Hive interface and should go in Hive editor rather than Impala editor.
Change-Id: Ifa5d5f40a5f53ccaccdbed49f11354dffbbaa44c
> [compute] Fixed warehouses sync for impala feng

- desktop/libs/azure/src/azure/abfs/abfs.py
This reverts commit aa85b51a5d88b525cae1891113b19adca389644f.
- 
-
> Revert "[ABFS] Fix reading file operation by 1 byte (#3470)"

- desktop/core/src/desktop/management/commands/sync_warehouses.py
- desktop/libs/notebook/src/notebook/connectors/base.py
Added a try/except to log error and continue if one of the namespaces runs into and error.
Change-Id: I25d5ba71e0d6032e513465de1fa616dfe4ea0878
> [core][computes] Improved error handling in sync code

- desktop/libs/aws/src/aws/s3/s3fs.py
- Whenever someone attempt to copy multiple files on Hue File Browser, they can encounter dataloss if they do not wait for the model pop-up to fully load.
- Found the root cause and it's because of a bad call to Hue server which is sending wrong destination path. 
- When the modal pops up to select the destination path, it tries to list down the content of the directory chosen and that takes some extra seconds but the button to move is clickable still. When someone clicks the 'Move' button but the path has not loaded correctly, it sends the wrong path (either the source path or default user home path) instead of actual destination path with the request. 
- This messes up the move operation in the backend where it actually doesn't move stuff to the destination because the path was …
> [s3] Skip move/copy operation if parent path of source is equal to destination path

- desktop/core/ext-py3/boto-2.49.0/boto/gs/bucket.py
- desktop/core/ext-py3/boto-2.49.0/boto/gs/key.py
- desktop/core/ext-py3/boto-2.49.0/boto/utils.py
- Add necessary fix to boto package in ext-py3 for making few GS operations work similar to S3.
- Check review discussions of https://github.com/cloudera/hue/pull/3455 for more details.
- Tested with Hue File browser feature for GCS.
> [gs] Add boto package changes for Hue-GCS feature

- desktop/libs/notebook/src/notebook/templates/editor2.mako
- desktop/libs/notebook/src/notebook/templates/editor_components.mako
This PR resolves issue from #3489
> [editor] Fix icon for SparkSQL snippets

- apps/beeswax/src/beeswax/common.py
- apps/beeswax/src/beeswax/server/dbms.py
Change-Id: I2b9b408e0f342a2134da7c2f65ee6b9cdcc4d340
> [compute] fixes to handle no available compute and other options

- desktop/core/src/desktop/js/ko/components/__snapshots__/ko.jobBrowserLinks.test.js.snap
- desktop/core/src/desktop/js/ko/components/ko.contextSelector.js
- desktop/core/src/desktop/js/ko/components/ko.dropDown.js
- desktop/core/src/desktop/js/ko/components/ko.jobBrowserLinks.js
- desktop/core/src/desktop/templates/global_js_constants.mako
1. Changes on the editor a. renamed compute -> virtual warehouse b. removed cluster selector
2. Removed the mini job-browser when running in computes mode
Change-Id: Ie2fc671487e22376a1d32d2d7635a4fba0c8af08
> Hue at env level hue UI changes

- desktop/libs/azure/src/azure/abfs/abfs.py
- If the number of files + folders exceeds the 5000, a continuation token is provided in the response header `x-ms-continuation` which we are using for subsequent invocations to continue listing the paths.
- Locally
> [ABFS] Fix the ABFS filebrowser listing limit

- desktop/libs/indexer/src/indexer/templates/importer.mako
- Unifying the restriction on column name in importer
- Locally
> [Importer] Standardizing the Column Name Restrictions in the Importer

- desktop/core/src/desktop/js/reactComponents/AlertComponent/AlertComponent.tsx
> [frontend] Fix styling and dismissal of the new error message component

- desktop/core/src/desktop/templates/global_js_constants.mako
- desktop/core/src/desktop/templates/hue.mako
This is part of the overall removal of inline javascript in Hue.
> [frontend] Move global js config from hue.mako to global_js_constants.mako

- docs/docs-site/content/developer/development/_index.md
- Improved visual studio code section
> [docs] Update Visual Studio Code section

- desktop/core/src/desktop/js/apps/jobBrowser/components/impalaQueries/index.d.ts
- desktop/core/src/desktop/js/apps/jobBrowser/components/impalaQueries/query-details/QueryDetails.vue
- desktop/core/src/desktop/js/apps/jobBrowser/components/impalaQueries/query-details/QueryDetailsDiff.vue
- desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserPage.tsx
- desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.tsx
- desktop/core/src/desktop/js/reactComponents/FileChooser/FileChooserModal/FileChooserModal.tsx
- Fixed linting issues
- Linting is passing
> [frontend] fix ts lint warnings

- desktop/core/src/desktop/js/apps/notebook/snippet.js
- desktop/libs/notebook/src/notebook/conf.py
- desktop/libs/notebook/src/notebook/connectors/base.py
- desktop/libs/notebook/src/notebook/connectors/trino.py
- Support Trino editor in Hue using [trino rest client](https://github.com/trinodb/trino-python-client/blob/master/trino/client.py)
- Via Trino Docker image locally
> [Trino] Add V1 support for trino dialect 

- desktop/libs/notebook/src/notebook/connectors/trino.py
- Adding Trino catalog support.
- Examples: Catalog 'C1' with databases 'd1' and 'd2', and Catalog 'C2' with databases 'd2' and 'd3'. For Trino v1, display as 'C1.d1', 'C1.d2', 'C2.d2', 'C2.d3'."
- Locally
> [trino] Adding catalog support

- desktop/core/base_requirements.txt
> [Trino] Add Trino pypi package in requirements

- desktop/libs/aws/src/aws/s3/s3connection.py
- Consolidating both RazS3Connection and SignedUrlS3Connection into one for better readability and improving docstrings.
- Manual testing in live setup.
> [raz] Improve RazS3Connection class for better code readability

- apps/filebrowser/src/filebrowser/templates/listdir_components.mako
- added missing end curly bracket
- tested manually in browser and page was loading correctly
> [frontend] added missing end curly bracket that broke template

- desktop/core/src/desktop/lib/fs/gc/gsconnection.py
- Hue is breaking in live setup because of incorrect init call
- Manually tested in live setup
> [raz][gs] Fix init call for RazGSConnection

- .eslintrc.js
- desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.tsx
- desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx
- desktop/core/src/desktop/js/reactComponents/Pagination/Pagination.tsx
- desktop/core/src/desktop/js/reactComponents/WelcomeTour/WelcomeTour.tsx
- tsconfig.json
> [frontend] Turn all current linting warnings into errors

- desktop/libs/notebook/src/notebook/api.py
- desktop/libs/notebook/src/notebook/api_tests.py
Unit tests and manually tested by saving and reloading a notebook document as well as a  regular editor document.
> [editor] Fix a bug where saving an actual notebook has the incorrect document type

- desktop/core/src/desktop/lib/raz/raz_client.py
- desktop/core/src/desktop/lib/raz/raz_client_test.py
- Improve unit test cases for HA support for RAZ URLs.
- Running updated unit tests.
- E2E testing in live setup.
> [raz] Improve unit tests for Raz HA support

- desktop/core/src/desktop/templates/global_js_constants.mako
Manually tested with job browser blacklisted and not
> [jb] Fix bug that breaks Hue when the Job Browser is blacklisted

- desktop/core/src/desktop/lib/rest/raz_http_client.py
- desktop/core/src/desktop/lib/rest/raz_http_client_test.py
- Earlier we were encoding the url params only for small set of use-cases but it turns out we should always encode the params to cover all use-cases.
- To support the above observation, I'd to override the _make_url method of `HttpClient` class and change its `urlencode` method to use `quote()` method instead of default `quote_plus()`. This was required to fix scenarios of whitespace present in the path which regressed after the above change.
- Tested manually.
- Updating existing unit tests.
- Adding new unit tests.
> [raz][abfs] Improve url params encoding for RAZ ABFS client

- apps/filebrowser/src/filebrowser/settings.py
- We changed the file system names to include more detailed information for end-users.
- manual testing
> [fb] Changed file system name in permission_actions

- desktop/libs/notebook/src/notebook/connectors/trino.py
- desktop/libs/notebook/src/notebook/connectors/trino_tests.py
- Support ldap password script in trino as we were doing in Hive and Impala
- unittest
> [Trino] Support ldap password script in trino

- desktop/core/src/desktop/js/catalog/DataCatalogEntry.test.ts
- desktop/core/src/desktop/js/catalog/DataCatalogEntry.ts
> [tb] Fix an issue where column comments were fetched for individual columns in the Table Browser

- .circleci/config.yml
- .github/workflows/commitflow-py3.yml
- desktop/libs/azure/src/azure/abfs/__init__.py
- tools/ace-editor/demo/kitchen-sink/docs/python.py
- tools/ace-editor/static.py
- Enable pylint script
- Remove tool/ace-editor changes done in pytest PR https://github.com/cloudera/hue/pull/3693
- Remove the assert statement from abfs/__init__.py as it was controlling the main code flow.
-
> [pylint] enable pylint and remove tools/ace-editor changes done in pytest PR

- desktop/core/src/desktop/js/jquery/plugins/jquery.filechooser.js
- Made changes to file uploader in Importer to support chunked file uploads.
Manual testing. Files are getting uploaded, importer was able to guess the format of the files and create tables out of it.
> Importer supports chunked file uploads

- tools/cloudera/build_hue_cloudera.sh
- tools/cloudera/build_hue_common.sh
- Implemented support for Ubuntu 22 with Python 3.10
- Locally
- With cloudera's ubuntu22 docker image
> [ubuntu22] Support Hue on ubuntu22 and sles15 with python3.10

- desktop/core/ext-py3/eventlet-0.30.2/eventlet/greenio/base.py
- desktop/core/ext-py3/eventlet-0.30.2/eventlet/greenio/py3.py
- desktop/core/ext-py3/eventlet-0.30.2/eventlet/timeout.py
- desktop/core/ext-py3/eventlet-0.30.2/tests/__init__.py
- desktop/core/ext-py3/eventlet-0.30.2/tests/backdoor_test.py
- Upstream PR: https://github.com/eventlet/eventlet/pull/715/files
- Support for python3.10
- Patch applied and tested downstream
> [eventlet] Add rudimentary support for Python 3.10

- desktop/core/base_requirements.txt
- Django==3.2.0 to Django==3.2.25
- Only CVEs got fixed so there are no major changes
- Locally
> [cve][django] Upgrade the Django version

- desktop/core/src/desktop/lib/raz/raz_client.py
- These INFO level statements were not providing any context in the Hue logs as most of the RAZ logs are at DEBUG level. Instead, they were only polluting the Hue INFO logs.
- With this change, they will make sense with full DEBUG log context.
- Tested E2E in live setup
> [raz] Change log statements to DEBUG for RAZ HA section

- contributing-frontend.md
This PR is about documenting the data-testid attribute added along with the HTML elements in Hue. The data-testid have been added in the PR:
https://github.com/cloudera/hue/pull/3652
This is just a documentation PR in contributing-frontend.md file and needs no testing.
> [ui-doc] Documenting data-testid attribute in contributing-frontend.md file

- docs/docs-site/content/developer/development/_index.md
- Remove the old CI section which was stale.
- Document all the basic Ruff commands.
- Manually
> [docs] Add new python linting section

- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- Fix external table creation with Parquet, Orc format
- Fix external and managed table creation with Avro format
- Manually
- Unit test
> [Importer] Fix importer for Parquet, ORC, and Avro formats

- desktop/core/src/desktop/lib/thrift_util.py
we were not clearly catching the timeout error from impala query submission. the error response was getting passed to the upper layers that errored out when trying to get json out of it. It lead to a cryptic error on the frontend as well. Now we are generating a clearer log message with the timeout values and config name. The frontend also shows a timeout error message.
> [impala] improved query timeout error logging

- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/core/src/desktop/conf.py
- desktop/core/src/desktop/management/commands/rungunicornserver.py
Add config option for gunicorn server
maunal
> [conf] Make Gunicorn worker timeout and graceful timeout configurable

- docs/docs-site/content/administrator/configuration/connectors/_index.md
- docs/docs-site/content/developer/development/_index.md
- Change few dead links in documentation flagged by CI checks
- Manually and existing documentation CI check
> [docs] Fix dead links

- docs/gethue/content/en/posts/2024-06-26-integrating-trino-editor-in-hue-supporting-data-mesh-and-SQL-federation.md
> [Blog] Trino blog correction

- desktop/libs/azure/src/azure/abfs/upload.py
- ABFS uploads greater than the DEFAULT_WRITE_SIZE (100MB) were failing because the position/size of the uploaded chunk was not passed to the abfs file append method. 
Tested on ABFS. Tried uploading upto 2GB file. The file gets uploaded. Downloaded the uploaded file and verified the md5sum.
> [Taskserver] Enhance ABFS upload logic to handle chunk position tracking

- desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTabContents/StorageBrowserTabContent.tsx
- desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage/StorageBrowserTable/StorageBrowserTable.tsx
- desktop/core/src/desktop/js/utils/constants/common.ts
- desktop/core/src/desktop/js/utils/useDebounce.test.ts
- desktop/core/src/desktop/js/utils/useDebounce.ts
- Implement search feature in storage browser table. 
- Add debounce util function to optimise search.
- Added useDebounce.tests
- Manually
> [ui-storageBrowser]Implement storage browser table search

- desktop/core/src/desktop/js/utils/html/deXSS.test.ts
- desktop/core/src/desktop/js/utils/html/deXSS.ts
- Added a check to handle cases where the input is of type 'object'
- Convert the object to a string using `toString()` and `JSON.stringify()` methods
- Unittest
> [UI] Added a check to handle cases where the input is of type 'object'

- package-lock.json
> [ui-cve] Upgrade tar due to CVE-2024-28863

- desktop/core/src/desktop/templates/job_browser_common.mako
> [ui-jobs] Change "Modified" header for schedules listing to "Next Materialized"

- desktop/core/ext-py3/eventlet-0.30.2/eventlet/support/greendns.py
Fix adapted based on the upstream commit
https://github.com/eventlet/eventlet/commit/51e3c49
> [ext-py][eventlet] Fix Tudoor DoS issue (CVE-2023-29483)

- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- desktop/libs/indexer/src/indexer/templates/importer.mako
- Manual table creation from Hue importer 
- Hive + Impala
- Locally
- Unittest
> [Importer] Fix manual table creation from importer

- .github/workflows/commitflow-py3.yml
- CI added for the python3.11
- Upstream CI
> [Python3.11] Added CI for python3.11

- desktop/core/src/desktop/models.py
- desktop/core/src/desktop/models_tests.py
This takes care of an issue where a copy of a shared document ends up in the original owners home directory and becomes unreachable by the user making the copy. With this change these copied files are now put in the home directory of the user that makes the copy instead. If the file to be copied exists in a shared folder the copy will end up in that same shared folder, a user being able to copy such a document implies that the user is also able to browse that directory.
To reproduce the issue:
1. Log in as user A
2. Share document X in the "My documents" folder with user B
3. Log in as user B
4. Copy document X
5. The document is not visible to user B because it ends up in My Documents of user A which is not shared with user B (the folder)
Manually tested + unit tests
> [doc2] Fix issue where a copy of a shared document in user home becomes unreachable

- apps/beeswax/src/beeswax/server/hive_server2_lib.py
- Modified get_tables_meta to handle cases where more than 10,000 tables exist by implementing a loop to fetch all tables across multiple FetchResult calls.
- Manully
- Unittest (?)
> [Hive][left assist] Enhanced get_tables_meta to correctly fetch and display tables

- desktop/core/src/desktop/js/apps/storageBrowser/InputModal/InputModal.test.tsx
- desktop/core/src/desktop/js/components/Duration.test.ts
- desktop/core/src/desktop/js/components/__snapshots__/Duration.test.ts.snap
- Update tests that could otherwise fail depending on environment and branch
- Running unit tests
> [ui-testing] Improve 2 unit tests

- tools/cloudera/build_hue_cloudera.sh
- tools/cloudera/build_hue_common.sh
- RHEL8 Py3.8 to Py3.9
- RHEL9-ARM64 Py3.9
- Built Hue on Cloudera docker images
- CDH Canary builds
> [Python3.9] Add support for Python 3.9 on RHEL8 and RedHat8-ARM64

- desktop/core/src/desktop/management/commands/sync_warehouses.py
`displayname` -> `displayName`
> [computes] Fixed the typo in picking compute display-name

- apps/filebrowser/src/filebrowser/conf.py
- apps/metastore/src/metastore/conf.py
- These warnings pollute the initial logs generated after every Hue server restart.
- Manually
> [config][cleanup] Fix bool to coerce_bool type conversion warnings

- desktop/core/src/desktop/api_public_tests.py
- desktop/core/src/desktop/api_public_urls_v1.py
- desktop/libs/notebook/src/notebook/api_tests.py
- desktop/libs/notebook/src/notebook/urls.py
- Refactor the URL pattern to accommodate special characters in the table name and column name.
- Locally
- Unittest
> [Core] Refactor the URL pattern to allow special characters in the table and column names.

- desktop/libs/libsaml/src/libsaml/conf.py
- New redirect_url for SAML SSO logout
- Tested manually.
> Fixing redirect_url for Production and Dev/Staging environment

- apps/filebrowser/src/filebrowser/api.py
- apps/filebrowser/src/filebrowser/api_test.py
- Improve error message
- Manually
- Unit tests
> [api] Change error message for new upload public API

- desktop/core/src/desktop/management/commands/sync_warehouses.py
> [computes] typo-fix k8s labels should be in lowercase

- desktop/libs/indexer/src/indexer/indexers/sql.py
- desktop/libs/indexer/src/indexer/indexers/sql_tests.py
- Update Iceberg table syntax for Impala
- Fix the hive unittest for iceberg table
- locally
- Unittest
> [Importer] Update Iceberg table syntax for Impala

- desktop/core/src/desktop/templates/global_js_constants.mako
- Change MAX_FILEEDITOR_SIZE from string to number
- Manually
> [ui-config] Change MAX_FILEEDITOR_SIZE from string to number

- apps/filebrowser/src/filebrowser/api.py
- Port the already existing APIs related to chunked file upload with taskserver.
- **Currently the core logic remains the same which needs to be improved and will be done in future PRs.**
- Manually
> [api] Port chunk upload related APIs to public

- desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserPage.tsx
- desktop/core/src/desktop/js/apps/storageBrowser/StorageBrowserTab/StorageBrowserTab.tsx
- desktop/core/src/desktop/js/reactComponents/PathBrowser/PathBrowser.util.test.ts
- desktop/core/src/desktop/js/reactComponents/PathBrowser/PathBrowser.util.ts
- When the filesystem is changed using the tabs, the home directory should be updated.
- Manually tested and updated the unit tests.
> [ui-storagebrowser] fixes routing between multiple fileSystem

- desktop/core/src/desktop/js/apps/storageBrowser/FileChooserModal/FileChooserModal.tsx
- desktop/core/src/desktop/js/config/types.ts
- desktop/core/src/desktop/js/reactComponents/FileUploadQueue/FileUploadQueue.tsx
- fixes few console warning and types
> [ui-storagebrowser] fixes console warning and types

- desktop/libs/notebook/src/notebook/connectors/trino.py
- desktop/libs/notebook/src/notebook/connectors/trino_tests.py
- Saving session property properly for every user
- Manully
> [Trino] Improve session management and property handling.

- desktop/core/src/desktop/log/api.py
- desktop/core/src/desktop/log/api_test.py
- Return logs content as list of strings.
- Add reverse option for Hue logs. By default, it is set to False.
- Manually
- Added new unit test
> [logs] Add reverse order option for retrieving Hue logs

- desktop/core/src/desktop/js/utils/hooks/useFileUpload/useChunkUpload.ts
- Fixes the chunk upload then file is larger than chunk size.
- issue fixed: the `complete` api call for chunks was getting triggered before the chunks could get uploaded to the server.
> [ui-storagebrowser] fixes chunk upload for new storage browser

- .gitignore
- Add test data path in gitignore
- Locally
> [Pytest] Add test data path in gitignore

- .github/workflows/commitflow-py3.yml
- apps/filebrowser/src/filebrowser/api.py
> [ci] Add write permissions for pull-requests in commitflow workflow

- .github/workflows/commitflow-py3.yml
> [ci] Update permissions for commitflow workflow to enable write access

- desktop/core/src/desktop/management/commands/sync_warehouses.py
> [compute] [discovery] remove old computes before upserting

- desktop/core/src/desktop/conf.py
- Check if oozie is present in INSTALLED_APPS before importing Job model in config_validator
- Manually
> [core] Check if oozie is present in INSTALLED_APPS before importing Job model in config_validator

- desktop/core/src/desktop/api2.py
- desktop/core/src/desktop/api2_tests.py
> [api] Change HttpResponse to JsonResponse in /install_examples API

- desktop/core/src/desktop/management/commands/sync_warehouses.py
We currently dig into Hive and Impala config files to find the ldap groups. The parsing of hive and impala config file is error prone. Even bigger issue is that we expect a comma-separated list of groups but it is not guaranteed. Certain Impala environments can had a ldap-filter there in place of comma-separated list of groups.
This change prioritizes checking the service-discovery configmap to pick the ldapGroups info.
> [compute][discovery] check service-discovery cm for ldapgroup

- tools/scripts/hue.sh
- tools/scripts/python/python_helper.sh
> [multi-python][build] add mysql and pg to path before starting

- Makefile
> [multi-python] removing unset PIP_FIND_LINKS PIP_EXTRA_INDEX_URL

- desktop/conf.dist/hue.ini
- desktop/conf/pseudo-distributed.ini.tmpl
- desktop/libs/libsaml/src/libsaml/conf.py
- add customer config for libsaml redirect URL
- Manual
> [libsaml] Add custom config for libsaml redirect URL

- .github/workflows/pr-comments.yml
This pull request updates the GitHub Actions workflow configuration file `.github/workflows/pr-comments.yml` to improve organization and add a new job for UI tests and coverage reporting. The changes primarily involve renaming existing jobs for clarity and introducing steps for running JavaScript tests with coverage reporting.
* Renamed `pytest-codecov-comment` to `tests-and-coverage` for better clarity in job naming.
* Renamed `python-ut-files-comment` to `python-ut-files-check` for consistency in naming conventions.
* Added a new job `ui-tests-and-coverage` to run JavaScript tests using Jest with coverage reporting. This includes caching npm dependencies, installing packages, running tests with coverage, and adding a Jest coverage summary as a PR comment.
> [ci] Rename jobs in PR comments workflow for clarity and add UI code coverage steps

- tools/docker/hue/Dockerfile
- Python 3.8 -> Python 3.11
- Fixed the multi-python issue
- Manually
- Dockerbuild
> [docker] Upgrade Dockerfile to Python 3.11 and update dependencies

- apps/filebrowser/src/filebrowser/api.py
- apps/filebrowser/src/filebrowser/api_test.py
- apps/filebrowser/src/filebrowser/serializers.py
- apps/filebrowser/src/filebrowser/serializers_tests.py
- apps/filebrowser/src/filebrowser/utils.py
- apps/filebrowser/src/filebrowser/utils_test.py
- desktop/core/src/desktop/api_public.py
- desktop/core/src/desktop/api_public_urls_v1.py
- desktop/core/src/desktop/lib/fs/gc/gs.py
- desktop/core/src/desktop/lib/fs/gc/upload.py
- desktop/core/src/desktop/lib/fs/ozone/ofs.py
- desktop/core/src/desktop/lib/fs/ozone/upload.py
- desktop/core/src/desktop/lib/fs/proxyfs.py
- desktop/core/src/desktop/middleware.py
- desktop/libs/aws/src/aws/s3/s3fs.py
- desktop/libs/aws/src/aws/s3/upload.py
- desktop/libs/azure/src/azure/abfs/abfs.py
- desktop/libs/azure/src/azure/abfs/upload.py
- desktop/libs/hadoop/src/hadoop/fs/upload.py
- desktop/libs/hadoop/src/hadoop/fs/webhdfs.py
This PR introduces a new unified file upload REST API that provides a consistent interface for uploading files across multiple cloud storage providers. The implementation replaces the legacy upload handlers with modern, streaming-based handlers that offer improved performance, better error handling, and enhanced security.
- **Endpoint**: `/api/v1/storage/upload/file/`
- **Class**: `UploadFileAPI` using Django REST Framework
- **Method**: POST with multipart/form-data support
- **Parameters**:
- `destination_path` (required): Target path for the upload
- `overwrite` (optional, default: false): Whether to overwrite existing files
- Introduced `get_upload_handler()` method in all filesystem interfaces
- Dynamic handler selection based on storage type and destination path
- Consistent …
> [api][filebrowser] Refactor and improve file upload public API core design

- desktop/core/src/desktop/api2.py
- desktop/core/src/desktop/api2_tests.py
Problem
- Calling `.get()` on app configs from disabled apps returns an `AttributeError` because those configs are unbound Config objects (no `.get()`), causing `/desktop/api2/get_config` to fail and the UI to render blank. 
- See Issue: #4210 and PR Comment: https://github.com/cloudera/hue/pull/4172#issuecomment-3131175423
Solution
- Introduce `_safe_conf_get()` that returns:
- the bound value via `.get()` if available,
- otherwise the declared default/dynamic default,
- otherwise `None`.
- Apply to optional configs read by `get_config()`:
- filebrowser.conf: restrict_file_extensions, concurrent_max_connection, file_upload_chunk_size, show_download_button, enable_extract_uploaded_archive
- metastore.conf: allow_sample_data_from_views
Outcomes
- get_config no longer crashes when …
> [api][config] Make get_config resilient to blacklisted apps via safe config access

- tools/cloudera/build_hue_common.sh
Change-Id: I63885e9ee008c8afc81d4ac0a9f5c3d8f20f57b2 (cherry picked from commit bdec35fe603937c6d8ee6d67457978cb8dabb3a2) (cherry picked from commit 08480ccd34ba262fbf21f4ee4e1d34f0dd207973)
> [core] fix again the build on redhat8-arm64 because of 3e646de44fa17760d44366a6e458ee3c29c0def2

- desktop/core/src/desktop/js/apps/admin/Overview/Overview.scss
- desktop/core/src/desktop/js/apps/admin/Overview/OverviewTab.tsx
- desktop/core/src/desktop/js/types/types.ts
- desktop/core/src/desktop/settings.py
- desktop/core/src/desktop/templates/global_js_constants.mako
- Needed as we are supporting multi-python feature
- Manually
> [ui- Quick Start] Logging Python version in the logs and display it on Quick Start page

- apps/useradmin/src/useradmin/metrics.py
- desktop/core/src/desktop/metrics.py
Fix the issue happened on Ubuntu. RHEL cluster doesn't have same issue!
```
File "/opt/cloudera/parcels/CDH/lib/hue/apps/useradmin/src/useradmin/metrics.py", line 37, in active_users
).count()
File "/opt/cloudera/parcels/CDH/lib/hue/build/env/lib/python3.11/site-packages/django/db/models/query.py", line 412, in count
return self.query.get_count(using=self.db)
File "/opt/cloudera/parcels/CDH/lib/hue/build/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 528, in get_count
number = obj.get_aggregation(using, ['__count'])['__count']
File "/opt/cloudera/parcels/CDH/lib/hue/build/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation
result = compiler.execute_sql(SINGLE)
File …
```
> [metrics] Fix lost connection due to cx_Oracle database error

- desktop/core/src/desktop/js/api/utils.ts
- desktop/core/src/desktop/js/apps/editor/components/aceEditor/AceLocationHandler.ts
- desktop/core/src/desktop/js/apps/editor/components/aceEditor/acePredict.ts
- desktop/core/src/desktop/js/apps/editor/components/aceEditor/autocomplete/AutocompleteResults.ts
- desktop/core/src/desktop/js/apps/editor/execution/executionLogs.ts
- desktop/core/src/desktop/js/apps/editor/execution/sqlExecutable.test.ts
- desktop/core/src/desktop/js/apps/jobBrowser/knockout/JobBrowserViewModel.js
- desktop/core/src/desktop/js/catalog/DataCatalogEntry.ts
- desktop/core/src/desktop/js/catalog/api.ts
- desktop/core/src/desktop/js/catalog/dataCatalog.ts
- desktop/core/src/desktop/js/sql/reference/sqlUdfRepository.ts
- desktop/core/src/desktop/js/sql/reference/typeUtils.ts
- desktop/core/src/desktop/js/sql/sqlUtils.ts
- desktop/core/src/desktop/js/utils/html/getFileBrowseButton.ts
- desktop/core/src/desktop/js/utils/html/onHueLinkClick.ts
- desktop/core/src/desktop/js/utils/string/parseHivePseudoJson.ts
- desktop/core/src/desktop/js/utils/url/changeURL.ts
- desktop/core/src/desktop/js/utils/url/changeURLParameter.ts
- replacing indexOf with more appropriate util functions like `startsWith` and `includes`.
> [ui-core] replace indexOf with more readable util functions

- desktop/core/src/desktop/lib/fs/s3/clients/auth/raz.py
- desktop/core/src/desktop/lib/fs/s3/clients/aws.py
- desktop/core/src/desktop/lib/fs/s3/clients/base.py
- desktop/core/src/desktop/lib/fs/s3/clients/generic.py
- desktop/core/src/desktop/lib/fs/s3/conf_utils.py
- desktop/core/src/desktop/lib/raz/clients.py
This pull request delivers a comprehensive fix for the RAZ authentication failures (`SignatureDoesNotMatch`) in the new boto3-based S3 filesystem. It also significantly enhances the S3 client's configuration capabilities, particularly around SSL, making it more robust for enterprise environments.
Users encountered persistent `SignatureDoesNotMatch` (403 Forbidden) errors when performing basic S3 operations with RAZ enabled:
-   **Listing bucket contents** (`ListObjectsV2`) would fail, especially at the bucket root.
-   **Creating directories or uploading files** (`PutObject`) would consistently fail.
This PR addresses the root causes of these failures and improves the underlying client architecture.
-   **GET Request Fix**: We discovered that URL query parameters with empty values (like …
> [S3] Fix RAZ Authentication Failures and Enhance S3 Client Configuration
